### ISSUE TITLE
vmoperator alway disable prometheus converter

### ISSUE THREAD

**Issue by wappam** [VictoriaMetrics/helm-charts#102]
Bug on chart https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-operator

The deployment of the operator is always disabling the prometheus converter. 

My values.yaml
```
operator:
  # -- By default, operator converts prometheus-operator objects.
  disable_promethues_converter: "false"
  # -- By default, operator creates psp for its objects.
  psp_auto_creation_enabled: "false"
  # -- Enables ownership reference for converted prometheus-operator objects,
  # it will remove corresponding victoria-metrics objects in case of deletion prometheus one.
  enable_converter_ownership: "false"
```
After deploying the spec of the deployment:
```
spec:
      containers:
      - args:
        - --zap-log-level=info
        - --enable-leader-election
        command:
        - manager
        env:
        - name: WATCH_NAMESPACE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: victoria-metrics-operator
        - name: VM_ENABLEDPROMETHEUSCONVERTER_PODMONITOR
          value: "false"
        - name: VM_ENABLEDPROMETHEUSCONVERTER_SERVICESCRAPE
          value: "false"
        - name: VM_ENABLEDPROMETHEUSCONVERTER_PROMETHEUSRULE
          value: "false"
        - name: VM_ENABLEDPROMETHEUSCONVERTER_PROBE
          value: "false"
        - name: VM_PSPAUTOCREATEENABLED
          value: "false"
        - name: VM_ENABLEDPROMETHEUSCONVERTEROWNERREFERENCES
          value: "false"
        image: victoriametrics/operator:v0.5.0
        imagePullPolicy: IfNotPresent
        name: victoria-metrics-operator
```
The expected behaviour:

- VM_ENABLEDPROMETHEUSCONVERTER_PODMONITOR set to "true"
- VM_ENABLEDPROMETHEUSCONVERTER_SERVICESCRAPE set to "true"
- VM_ENABLEDPROMETHEUSCONVERTER_PROMETHEUSRULE set to "true"
- VM_ENABLEDPROMETHEUSCONVERTER_PROBE set to "true"

Even when commenting out `operator.disable_promethues_converter` in the value file it is still set the "false".

I notice the change after upgrading the chart from 0.1.1 to 0.1.2.

Thanks
