### ISSUE TITLE
How to properly setup remoteWrite credentials in vmagent

### ISSUE THREAD

**Issue by evertonspader-tomtom** [VictoriaMetrics/helm-charts#1021]
What is the proper way to set up the `remoteWrite` credentials using environment variables? I can get a successful connection using
```yaml
extraArgs:
  remoteWrite.url: https://<username>:<password>@<prometheus_endpoint>
```
But, of course, for security reasons, this is not ideal. So I am trying to use [environment variables](https://github.com/VictoriaMetrics/VictoriaMetrics?tab=readme-ov-file#environment-variables) as it's in the values file [here](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-agent/values.yaml#L98).

So I added the following:
```yaml
extraArgs:
  remoteWrite.url: <prometheus_endpoint>
  envflag.enable: "true"
  envflag.prefix: "VM_"

env:
  - name: VM_remoteWrite_basicAuth_username
    valueFrom:
      secretKeyRef:
        name: prometheus-secret
        key: username
  - name: VM_remoteWrite_basicAuth_password
    valueFrom:
      secretKeyRef:
        name: prometheus-secret
        key: password
```

But it doesn't seem to pick up the credentials as now I see a 401 in the export requests. What am I missing here?
```shell
{"ts":"2024-05-14T09:21:16.539Z","level":"error","caller":"VictoriaMetrics/app/vmagent/remotewrite/client.go:461","msg":"unexpected status code received after sending a block with size 1398 bytes to \"1:secret-url\" during retry #4: 401; response body=\"{\\\"status\\\":\\\"error\\\",\\\"error\\\":\\\"authentication error: invalid authentication credentials\\\"}\"; re-sending the block in 16.059 seconds"}
```
