### ISSUE TITLE
Back-off restarting failed container config-reloader on ipv6-only cluster

### ISSUE THREAD

**Issue by StellaV** [VictoriaMetrics/helm-charts#1074]
Hi all,

We installed the Victoria Metrics helm chart (chart version 0.23.x) on an IPv6-only cluster and right now both the vmagent and vmalertmanager are failing their readiness probes with the same error:

```
Readiness probe failed: Get "http://[1234:abcd:11:111:1111::1]:8435/health": dial tcp [1234:abcd:11:111:1111::1]:8435: connect: connection refused
```

As far as I see, this is the config-reloader (victoriametrics/operator:config-reloader-v0.43.0) and if I look at the logs, it appears to be listening on 127.0.0.1 only:

```
2024-06-18T07:33:27.256Z	info	VictoriaMetrics@v1.97.1/lib/httpserver/httpserver.go:101	starting http server at http://127.0.0.1:8435/
2024-06-18T07:33:27.256Z	info	VictoriaMetrics@v1.97.1/lib/httpserver/httpserver.go:102	pprof handlers are exposed at http://127.0.0.1:8435/debug/pprof/
2024-06-18T07:33:30.261Z	info	operator/internal/config-reloader/main.go:196	reload config ok.
2024-06-18T07:33:55.568Z	info	operator/internal/config-reloader/main.go:98	received stop signal, stopping config-reloader
2024-06-18T07:33:55.568Z	info	operator/internal/config-reloader/main.go:103	config-reloader stopped
```

Is there a way to overwrite this? Or am I missing another issue that's causing the failure?

Thanks in advance,

Stella

**Comment by zekker6** [comment]
Hello @StellaV 
You need to enable IPv6 support by adding `enableTCP6: true` to `extraArgs` section of each component. 
By default, all components only use IPv4 address and that's why health check is not passing.

**Comment by StellaV** [comment]
Hi @zekker6 ,

Thanks for the speedy answer! I added your suggestion, but it doesn't seem to make a difference for the error. I use the victoria-metrics-k8s-stack chart.

```
  vmsingle:
    spec:
      extraArgs:
        enableTCP6: "true"
     ....
  vmagent:
    spec:
      extraArgs:
        enableTCP6: "true"
      ....
  vmalert:
    spec:
      extraArgs:
        enableTCP6: "true"
```

Do you have any other ideas? :)

- Stella

**Comment by f41gh7** [comment]
Hello, tcp6 also must be enabled for config-reloader containers.

 It should be possible with the latest version of chart and operator ( it may require CRD update):

```yaml
  alertmanager:
   spec:
      configReloaderExtraArgs:
         enableTCP6: "true"
         reload-url: http://localhost:9093/-/reload

  vmsingle:
    spec:
      extraArgs:
        enableTCP6: "true"
     ....
  vmagent:
    spec:
      configReloaderExtraArgs:
         enableTCP6: "true"
         reload-url: http://localhost:8429/-/reload
      extraArgs:
        enableTCP6: "true"
      ....
  vmalert:
    spec:
      configReloaderExtraArgs:
         enableTCP6: "true"
         reload-url: http://localhost:8080/-/reload
      extraArgs:
        enableTCP6: "true"
```

**Comment by f41gh7** [comment]
Unfortunately, tcp6 is still a challenging thing for applications. 

 I think, we have to create some global trigger for helm chart, that enables tcp6 support for each component.

**Comment by StellaV** [comment]
Hi @f41gh7. 

A global "enableTCP6" config would also be very nice in future releases.

Thanks for the proposed workaround, which seems to solve my issue completely! Here's the config I used:

```
  alertmanager:
   spec:
      configReloaderExtraArgs:
         enableTCP6: "true"
         reload-url: http://localhost:9093/-/reload
  vmsingle:
    spec:
      extraArgs:
        enableTCP6: "true"
  vmagent:
    spec:
      configReloaderExtraArgs:
         enableTCP6: "true"
         reload-url: http://localhost:8429/-/reload
      extraArgs:
        enableTCP6: "true"
  vmalert:
    spec:
      extraArgs:
        enableTCP6: "true"
```

This works perfectly for vmalertmanager and vmagent, which use the victoriametrics/operator:config-reloader-v0.43.0 image. VMalert uses a different reload image, so it didn't need the extra reloader config.

Thanks again!

Stella
