### ISSUE TITLE
Failing the existingClaim for multiple replica of VMStorage

### ISSUE THREAD

**Issue by hanumanhuda** [VictoriaMetrics/helm-charts#1082]
Values for vmstorage
```
vmstorage:
  replicaCount: 2
  persistentVolume:
    enabled: true
    accessModes: ReadWriteMany
    existingClaim: test-pvc
    mountPath: /storage
    size: 500Gi
```
We can provide a single pvc for the vmstorage and all the pods are trying to use the same volume, therefore failing with below errors, however we can't provide multiple PVC for the same. Also can't we use the same volume for all the pods and have different subdirectory at pod level.

Error
```
"msg":"opening storage at \"/storage\" with -retentionPeriod=1"}
{"ts":"2024-06-26T08:38:04.642Z","level":"panic","caller":"VictoriaMetrics/lib/fs/fs.go:345","msg":"FATAL: cannot create lock file: cannot acquire lock on file \"/storage/flock.lock\": resource temporarily unavailable; make sure a single process has exclusive access to \"/storage\""}
```
