### ISSUE TITLE
[victoria-metrics-k8s-stack] filter out by rule name is broken now

### ISSUE THREAD

**Issue by IgorIgnatevSky** [VictoriaMetrics/helm-charts#1123]
Hi in the last release 0.23.6, rules-related changes broke filtering out rules by name in defaultRules.disabled.[rule name]: true

values config eq:

```
   defaultRules:
      disabled:
        TooManyScrapeErrors: true
        TooHighChurnRate24h: true
        KubeHpaMaxedOut: true
        KubeMemoryOvercommit: true
```

Expected that these 4 rule names would be disabled and previously it worked, now all rules are enabled.

**Comment by Haleygo** [comment]
Hi,
rule templates has been changed since [v0.23.6](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.24.0) in https://github.com/VictoriaMetrics/helm-charts/pull/1093 to provide more features like additional labels to specific group/rule. Now, you can disable them with below values:
```
## -- Create default rules for monitoring the cluster
defaultRules:
  create: true

  # -- Per rule properties
  rules:
    TooManyScrapeErrors:
      create: false
    TooHighChurnRate24h:
      create: false
...
```
