### ISSUE TITLE
operator fails to start due to manager not in $PATH

### ISSUE THREAD

**Issue by cathelijne** [VictoriaMetrics/helm-charts#1127]
Helm chart 0.24.*, deploying from argocd.

```  
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-metrics-k8s-stack
    targetRevision: 0.24.*
```

```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "manager": executable file not found in $PATH: unknown
```

kube server: v1.27.7+k3s2
argocd: v2.10.12+cb6f5ac
operator: v0.46.3

reverting back to helm release 0.23.5 works fine

<img width="923" alt="Screenshot 2024-07-08 at 12 46 33" src="https://github.com/VictoriaMetrics/helm-charts/assets/3843328/1e6c2fc2-bb57-4920-a540-11dc23420e6f">
(sorry for reporting by screenshot, I had already pushed the revert commit for argo to use when it dawned on me I should probably report this)
