### ISSUE TITLE
After updating to version 0.23.6, defaultRules.disable in values stopped working

### ISSUE THREAD

**Issue by dmytropoltorak** [VictoriaMetrics/helm-charts#1135]
I disabled some DefaultRules a long time ago and starting this Monday I started getting alerts again for rules that are disabled, for example
```
spec:
  values:
    defaultRules:
      disabled:
        etcdHighNumberOfFailedGRPCRequests: true
```

How can I fix this problem?
