### ISSUE TITLE
[victoria-metrics-k8s-stack]: add global license configuration for components

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/helm-charts#1161]
Currently, it's needed to specify license configuration per each component:

```yaml
vmalert:
  spec:
   image:
     tag: tag: v1.101.0-enterprise
   license:
     keyRef:
      name: secret-license
      key: license
vmagent:
  spec:
   image:
     tag: tag: v1.101.0-enterprise
   license:
     keyRef:
      name: secret-license
      key: license
vmcluster:
  spec:
   image:
     tag: tag: v1.101.0-enterprise
   license:
     keyRef:
      name: secret-license
      key: license
vmcluster:
  enabled: true
  license:
    keyRef:
      name: secret-license
      key: license
  spec:
    vmstorage:
      image:
        tag: v1.101.0-enterprise-cluster

extraObjects:
  apiVersion: v1 
  kind: Secret
  metadata:
    name: secret-license
    namespace: CHART_NAMESPACE
  stringData:
   license: |-
     ACTUAL_LICENSE
```

 It'd be great to have a single option for templating.
