### ISSUE TITLE
Fix error with missing "-" in configmap victoria-metrics-agent chart

### ISSUE THREAD

**Issue by kevinvirs** [VictoriaMetrics/helm-charts#117]
https://golang.org/pkg/text/template/
victoria-metrics-agent/templates/configmap.yaml
>     {{ toYaml .Values.config | nindent 4 }}

with values:
```
config:
  global:
    scrape_interval: 10s
    external_labels:
      cluster: k8s

  # scrape self by default
  scrape_configs:
```
configmap result:
```
apiVersion: v1
data:
  scrape.yml: |2

        cluster: k8s
      external_labels: null
    global:
      scrape_interval: 10s
    scrape_configs:
      ...
```
after fix:

>     {{- toYaml .Values.config | nindent 4 }}
```
apiVersion: v1
data:
  scrape.yml: |
    global:
      external_labels:
        cluster: k8s-dv
      scrape_interval: 10s
    scrape_configs:
      ...
```
