### ISSUE TITLE
Cleanup job created with invalid image

### ISSUE THREAD

**Issue by BryanFauble** [VictoriaMetrics/helm-charts#1196]
When removing the helm chart deployed through terraform a job is created with this spec.containers:

```
    spec:
      containers:
      - args:
        - delete
        - vmagents,vmalertmanagers,vmalerts,vmauths,vmclusters,vmsingles
        - --all
        - --ignore-not-found=true
        image: bitnami/kubectl:1.30+
```

However, the image is not in a valid format that can run within AWS EKS. Events on the pod:
```
│ Events:                                                                                                                                                                                                                                          │
│   Type     Reason         Age                    From                                 Message                                                                                                                                                    │
│   ----     ------         ----                   ----                                 -------                                                                                                                                                    │
│   Normal   Scheduled      9m6s                   default-scheduler                    Successfully assigned victoria-metrics/victoria-metrics-k8s-stack-scrapers-victoria-metrics-operagms7p to ip-***.ec2.internal                            │
│   Warning  Failed         6m54s (x12 over 9m6s)  kubelet, ip-***.ec2.internal  Error: InvalidImageName                                                                                                                                    │
│   Warning  InspectFailed  3m56s (x26 over 9m6s)  kubelet, ip-***.ec2.internal  Failed to apply default image tag "bitnami/kubectl:1.30+": couldn't parse image name "bitnami/kubectl:1.30+": invalid reference format    
```
