### ISSUE TITLE
Ability fo expose syslog.listenAddr for external logs

### ISSUE THREAD

**Issue by trudzkimedo** [VictoriaMetrics/helm-charts#1200]
Hello,
Apologies if this actually was answered but I was unable to find it in docs nor in past issues.

I'm looking to expose Victoria metrics and logs to be able to ingest external sources.
While in Metrics, i could use Prometheus external scrape config, with probably no need to modify VictoriaMetric helm, I do not see any functionality of that for VictoiraLogs.

Could I ask for feature that syslog.* command line parameters are configurable and desired service is exposed.

Thanks.

**Comment by tiny-pangolin** [comment]
you can specify the command line flags for syslog under `server.extraArgs` along with any other command line options for victorialogs. 

```yaml
server:
  extraArgs:
    syslog.listenAddr.tcp: ':514'
    syslog.listenAddr.udp: ':514'
```
