### ISSUE TITLE
[victoria-metrics-k8s-stack] Problem with the New Probe Refactoring

### ISSUE THREAD

**Issue by alihoda** [VictoriaMetrics/helm-charts#1247]
```
Error: Failed to render chart: exit status 1: Error: UPGRADE FAILED: template: victoria-metrics-k8s-stack/charts/victoria-metrics-operator/templates/deployment.yaml:99:30: executing "victoria-metrics-k8s-stack/charts/victoria-metrics-operator/templates/deployment.yaml" at <include "vm.probe" (dict "app" .Values "type" "readiness")>: error calling include: template: victoria-metrics-k8s-stack/charts/victoria-metrics-operator/charts/victoria-metrics-common/templates/_probe.tpl:6:4: executing "vm.probe" at <tpl (toYaml $probe) .>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: failureThreshold: 3
    httpGet:
      path: '{{ include "vm.probe.http.path" . }}'
      port: probe
      scheme: '{{ include "vm.probe.http.scheme" . }}'
    initialDelaySeconds: 5
    periodSeconds: 15
    timeoutSeconds: 5: "BasePath" is not a value

    Error: plugin "diff" exited with error
```

I am using vm-k8s-stack 0.24.2 and am now trying to use version 0.25.0, but I am having a problem with the new probes. I cannot find `vm.probe.http.path` and `vm.probe.http.scheme` anywhere in the template files, neither in the vm-k8s-stack chart nor in the vm-operator chart (I have deployed the new CRD).
How can I get over it? I can pass values manually but it seems in the commit for #1212 many of the vm components had effected!!

**Comment by AndrewChubatiuk** [comment]
Upgrading to Helm 3.14+ should resolve this issue

**Comment by vadym-replianchuk** [comment]
I have the same issue even after updating the helm to the latest version.

The victoria-metrics-k8s-stack chart (0.24.5) is installed by FluxCD. During the upgrade to the 0.25.0 version I revieve the following error:
```
Helm upgrade failed for release monitoring/victoria-metrics with chart victoria-metrics-k8s-stack@0.25.2: template: victoria-metrics-k8s-stack/charts/victoria-metrics-operator/templates/deployment.yaml:99:30: executing "victoria-metrics-k8s-stack/charts/victoria-metrics-operator/templates/deployment.yaml" at <include "vm.probe" (dict "app" .Values "type" "readiness")>: error calling include: template: victoria-metrics-k8s-stack/charts/victoria-metrics-operator/charts/victoria-metrics-common/templates/_probe.tpl:6:4: executing "vm.probe" at <tpl (toYaml $probe) .>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: failureThreshold: 3
httpGet:
  path: '{{ include "vm.probe.http.path" . }}'
  port: probe
  scheme: '{{ include "vm.probe.http.scheme" . }}'
initialDelaySeconds: 5
periodSeconds: 15
timeoutSeconds: 5: "BasePath" is not a value
```

I tried to overwrite the values ​​for readiness tests for the following ones, but the error did not disappear:
```
probe:
  readiness:
    httpGet:
      path: /health
      scheme: HTTP
      port: probe
```

Can you help me please?

helm version:
```
version.BuildInfo{Version:"v3.15.4", GitCommit:"fa9efb07d9d8debbb4306d72af76a383895aa8c4", GitTreeState:"clean", GoVersion:"go1.22.6"}
```

kubectl version:
```
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3
```
