### ISSUE TITLE
[victoria-metrics-k8s-stack] Scraping services not getting correct labels

### ISSUE THREAD

**Issue by nebula-it** [VictoriaMetrics/helm-charts#1248]
In the latest release `0.25.0`, the Services created for `kubeScheduler`, `kubeControllerManager` etc do not get the label `app:`

# How to reproduce
Run
```
helm template vm-stack vm/victoria-metrics-k8s-stack -n victoria-metrics --version '0.24.5' > vm-stack-0.24.5.yaml
helm template vm-stack vm/victoria-metrics-k8s-stack -n victoria-metrics --version '0.25.0' > vm-stack-0.25.0.yaml
```
This is the output in `vm-stack-0.24.5.yaml`
```
# Source: victoria-metrics-k8s-stack/templates/servicemonitors/kube-scheduler.yaml
apiVersion: v1
kind: Service
metadata:
  name: vm-stack-victoria-metrics-k8s-stack-kube-scheduler
  namespace: kube-system
  labels:
    app: vm-stack-victoria-metrics-k8s-stack-kube-scheduler
    jobLabel: kube-scheduler
    helm.sh/chart: victoria-metrics-k8s-stack-0.24.5
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/instance: vm-stack
    app.kubernetes.io/version: "v1.102.1"
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10259
      protocol: TCP
      targetPort: 10259
  selector:
    component: kube-scheduler
  type: ClusterIP
```
This is the output in `vm-stack-0.25.0.yaml`
```
# Source: victoria-metrics-k8s-stack/templates/servicemonitors/kube-scheduler.yaml
apiVersion: v1
kind: Service
metadata:
  name: vm-stack-victoria-metrics-k8s-stack-kube-scheduler
  namespace: kube-system
  labels: 
    helm.sh/chart: victoria-metrics-k8s-stack-0.25.0
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/instance: vm-stack
    app.kubernetes.io/version: "v1.102.1"
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10259
      protocol: TCP
      targetPort: 10259
  selector: 
    component: kube-scheduler
  type: ClusterIP
```
The one on `vm-stack-0.25.0.yaml` is missing 
```
  labels:
    app: vm-stack-victoria-metrics-k8s-stack-kube-scheduler
   ```
