### ISSUE TITLE
[victoria-metrics-k8s-stack] Add `routePrefix` to VM Components

### ISSUE THREAD

**Issue by alihoda** [VictoriaMetrics/helm-charts#1260]
Hi. It would be nice if vm-k8s-stack has a option like `routePrefix` in *kube-prometheus-stack* that helps to set a root path for each components and so just use one domain for entire stack.
I currently should handle it with `ingress.annotations`:

```
ingress:
  select:
    path: /s/?(.*)
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/use-regex: "true"
```

As it seems, it is a little messy!! And if use something like anchors to reuse it for other ingresses, then for grafana and vmalertmanger you can not use it because they support the root path option. In the end you need to repeat the necessary annotations for these two!!

**Comment by AndrewChubatiuk** [comment]
could you please elaborate more about this case?
which services do you want to have ingress for?
in a final configuration do you expect all services to be behind a single ingress? (i'm not aware if nginx ingress supports multiple ingresses with the same host:port, but different paths, like alb controller does)

**Comment by alihoda** [comment]
> could you please elaborate more about this case? which services do you want to have ingress for? in a final configuration do you expect all services to be behind a single ingress? (i'm not aware if nginx ingress supports multiple ingresses with the same host:port, but different paths, like alb controller does)


In the `vm-k8s-stack`, specifically for `vmcluster`, we typically have Ingress resources for `vminsert`, `vmstorage`, and `vmselect`, with `vmselect` being the most crucial. Additionally, in both single and cluster modes, `vmagent` and `vmalert` also have Ingress options, mainly to provide detailed insights beyond what is available in Grafana dashboards.

For our scenario, the goal is to use a single domain, `vm.example.com`, with Ingress paths for three key services: `vmselect`, `vmagent`, and `vmalert` (we also have VMAlertMnager and Grafana for that domain too but they are handled with `routePrefix` and `grafana.ini.server.root`). The desired paths are as follows:

- `/s` for `vmselect`
- `/a` for `vmagent`
- `/al` for `vmalert`

In the `kube-prometheus-stack`, there is a `routePrefix` option (used by components like AlertManager and Prometheus) that allows for rewriting URLs, making it easier to manage multiple services under a single domain. This feature can be seen in the `values.yaml` file of both [vm-k8s-stack](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml#L474) and [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L3751).

Implementing a similar `routePrefix` option in `vm-k8s-stack` would simplify configuration, reducing the need to manage multiple, repetitive annotations across different Ingress resources, especially when dealing with services like Grafana and VMAlertManager, which already support root path customization. This would allow for cleaner, more maintainable Ingress configurations, all while using a single domain with distinct paths for each service.

**Comment by AndrewChubatiuk** [comment]
hey @alihoda
All VM components have ability to set a custom path prefix using:
```
<vm-component>:
  spec:
    extraArgs:
      http.pathPrefix: /prefix
```
The only exception is alertmanager, which has a special property for this case: `alertmanager.spec.routePrefix`
Additionally I've added a PR, which allows to use prefix from cmd args for vm components and `routePrefix` of alertmanager as a default path for each component in ingress

**Comment by AndrewChubatiuk** [comment]
starting 0.25.17 you can set
```
vmagent:
  extraArgs:
    http.pathPrefix: /agent
  ingress:
    enabled: true
    hosts: [anyhost.com]
```
this will automatically add `/agent` path to ingress paths

**Comment by alihoda** [comment]
> hey @alihoda 
> starting 0.25.17 you can set
> ```
> vmagent:
>   spec:
>     extraArgs:
>       http.pathPrefix: /agent
>   ingress:
>     enabled: true
>     hosts: [anyhost.com]
> ```
> this will automatically add `/agent` path to ingress, which you can override using `vmagent.ingress.path`
> are you okay with such approach?
> 

That sounds good. That's what I was looking for.
Thanks.

**Comment by alihoda** [comment]
> hey @alihoda starting 0.25.17 you can set
> 
> ```
> vmagent:
>   spec:
>     extraArgs:
>       http.pathPrefix: /agent
>   ingress:
>     enabled: true
>     hosts: [anyhost.com]
> ```
> 
> this will automatically add `/agent` path to ingress, which you can override using `vmagent.ingress.path` are you okay with such approach?

I've faced a problem with this `http.pathPrefix`. I have something like this:

```
vmcluster:
  spec:
    vmselect:
      extraArgs:
        http.pathPrefix: /s
        
  ingress:
    select:
      enabled: true
      hosts:
        - example.com
 ```

Now there is an ingress for vmselect with `/s` path, so vmui is on `/s/0/vmui`. The problem is for `/s/0/prometheus` which is using for Grafana, return this error: `requestURI: /s/0/prometheus; unsupported path requested: "/s/0/prometheus"`!!
Is there anything that I'm doing wrong?
