### ISSUE TITLE
[victoria-metrics-k8s-stack] Add `enableFeatures` to VMAlertManager

### ISSUE THREAD

**Issue by alihoda** [VictoriaMetrics/helm-charts#1262]
Hi! Is it possible to add `enableFeatures` option to the VMAlertManager CRD? We need the `receiver-name-in-metrics` and already have it in our *kube-prometheus-stack* and want to migrate from that to VMCluster.

**Comment by AndrewChubatiuk** [comment]
hey, you can pass it using
```
alertmanager:
  spec:
    extraArgs
      enable-feature: [receiver-name-in-metrics]
```
