### ISSUE TITLE
[victoria-metrics-k8s-stack] I can't pass env variables to the operator sub-chart

### ISSUE THREAD

**Issue by mkotsalainen** [VictoriaMetrics/helm-charts#1267]
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml#L19

I'm using latest version 0.25.0

I need to pass VM_PROMETHEUSCONVERTERADDARGOCDIGNOREANNOTATIONS option to the operator but I can't do it since the env parameter to the subchart isn't exposed - even though the comment actually talks about env variables. Maybe I'm missing something in how helm works?

thanks

**Comment by mkotsalainen** [comment]
I wsa confused. It is possible to pass variables to subcharts. Like so:

```
victoria-metrics-k8s-stack:
  victoria-metrics-operator:
    env:
      - name: VM_PROMETHEUSCONVERTERADDARGOCDIGNOREANNOTATIONS
        value: "true"
```

**Comment by AndrewChubatiuk** [comment]
hey @mkotsalainen 
have you tried to pass it like this
```
victoria-metrics-operator:
  env:
    - name: VM_PROMETHEUSCONVERTERADDARGOCDIGNOREANNOTATIONS
       value: "true"
       
```
