### ISSUE TITLE
Bug: VMAlertmanager Ingress error in k8s-stack (after latest update)

### ISSUE THREAD

**Issue by mhkarimi1383** [VictoriaMetrics/helm-charts#1270]
Hi

Getting Error below

```shell
Error: template: victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/ingress.yaml:44:19: executing "victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/ingress.yaml" at <.>: wrong type for value; expected string; got []interface {}
```

with values

```yaml
....
alertmanager:
  enabled: true
  spec:
    selectAllByDefault: true
    externalURL: https://monitoring.example.com/alertmanager
    routePrefix: "/alertmanager/"
  monzoTemplate:
    enabled: true
  ...
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
      nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
      nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
      nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-Access-Token"
      nginx.ingress.kubernetes.io/use-regex: "true"
      cert-manager.io/cluster-issuer: example-issuer
    labels: {}
    path: /alertmanager/
    pathType: Prefix
    hosts:
      - monitoring.example.com
    tls:
      - secretName: alertmanager-ingress-tls
        hosts:
          - monitoring.example.com
...
```

I have also tried commenting entire ingress section (just `enable: true`) but helm template command gives me the same error

```shell
helm template monitoring vm/victoria-metrics-k8s-stack --values ./values.yaml --debug --version 0.25.1 -n monitoring
```
