### ISSUE TITLE
No match between VMServiceScrape and Service for coreDNS, kubeScheduler and kubeControllerManager in latest victoria-metrics-k8s-stack chart

### ISSUE THREAD

**Issue by barthy1** [VictoriaMetrics/helm-charts#1282]
When I did update of victoria-metrics-k8s-stack  installation to the latest available chart version (0.25.2) I noticed that the targets for coreDNS, kubeScheduler and kubeControllerManager are 0/0 now.

After some investigation I figured out, that in the corresponding VMServiceScrape template there is hardcoded selector.matchLabels `app: {{ $fullname }}`
For instance for coreDNS
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "victoria-metrics-k8s-stack.labels" . | nindent 4 }}
spec:
  {{- omit .Values.coreDns.spec "selector" "namespaceSelector" | toYaml | nindent 2 }}
  selector:
    matchLabels:
      app: {{ $fullname }}
      app.kubernetes.io/instance: {{ default .Release.Name .Values.argocdReleaseOverride | trunc 63 | trimSuffix "-" }}
  namespaceSelector:
    matchNames:
      - "kube-system"
```

However in the corresponding Service same label is not generated. I see some code, that pretends to do it, but I can see in my actual deployment and even with `helm template` test that there is no label `app: {{ $fullname }}` in the service.
For example for coreDns template is

```
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  namespace: kube-system
  {{- $extraLabels := dict "app" $fullname "jobLabel" "coredns" }}
  {{- $ctx := merge (deepCopy $global) (dict "extraLabels" $extraLabels) }}
  labels: {{ include "victoria-metrics-k8s-stack.labels" $ctx | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.coreDns.service.port }}
      protocol: TCP
      targetPort: {{ .Values.coreDns.service.targetPort }}
  {{- with .Values.coreDns.service.selector }}
  selector: {{ toYaml . | nindent 4 }}
  {{- end}}
{{- end }}
```
The output with `helm template`

```
# Source: victoria-metrics-k8s-stack/templates/servicemonitors/coredns.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-victoria-metrics-k8s-stack-coredns
  namespace: kube-system
  labels:
    helm.sh/chart: victoria-metrics-k8s-stack-0.25.0
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.102.1"
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 9153
      protocol: TCP
      targetPort: 9153
  selector:
    k8s-app: kube-dns
```

So, there is `app: {{ $fullname }}` in the spec.selector.matchLabels of VMServiceScrape, but no such label in the Service and it leads to the lack of metrics for coreDNS, kubeScheduler and kubeControllerManager
