### ISSUE TITLE
Broken dependencies in vmauth chart 0.5.0

### ISSUE THREAD

**Issue by cwstrommer** [VictoriaMetrics/helm-charts#1287]
The chart includes `victoria-metrics-common` as a relative file dependency, as follows:
```
dependencies:
- name: victoria-metrics-common
  repository: file://../victoria-metrics-common
  version: 0.0.*
```
However, this breaks things when doing the following:
```
helm fetch vm/victoria-metics-auth
tar xzf victoria-metrics-auth-0.5.0.tgz
cd victoria-metrics-auth/
helm dep up
```
The dependency should instead be something like
```
dependencies:
- name: victoria-metrics-common
  repository: https://victoriametrics.github.io/helm-charts/
  version: 0.0.*
```
