### ISSUE TITLE
[victoria-metrics-k8s-stack] resources being deleted and re-created in infinite loop

### ISSUE THREAD

**Issue by AurimasNav** [VictoriaMetrics/helm-charts#1319]
As per picture below, pod and controllerrevision are being deleted and re-created in an infinite loop, while pvc is always in processing.
![image](https://github.com/user-attachments/assets/46ef2b86-2166-405c-8683-480b5350623c)

argocd version: 2.12.2
k3s version: v1.30.4+k3s1

helm via kustomize
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []
namespace: victoriametrics

helmGlobals:
  chartHome: charts
helmCharts:
- name: victoria-metrics-k8s-stack
  version: 0.25.3
  repo: https://victoriametrics.github.io/helm-charts
  releaseName: victoria-metrics-k8s-stack
  includeCRDs: true
  namespace: victoriametrics
  valuesFile: values.yaml
```

application.yaml
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-k8s-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: victoriametrics
  project: default
  source:
    path: gitops/victoria-metrics-k8s-stack
    repoURL: https://github.com/AurimasNav/k8s-at-home.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: victoria-metrics-k8s-stack-victoria-metrics-operator-validation
      namespace: kube-system
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: victoria-metrics-k8s-stack-victoria-metrics-operator-admission
      jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
```
