### ISSUE TITLE
Issue with Applying Global Relabeling Configurations in Victoria Metrics Using VMScrapeConfig

### ISSUE THREAD

**Issue by Demmyart** [VictoriaMetrics/helm-charts#1330]
Hi,

I have several serviceScrape entities that are working fine. However, I want to add an additional relabel config to them globally. I expected that adding a VMScrapeConfig would apply these relabeling rules across all serviceScrapes and its targets. While I can see in the operator logs that the scrapeConfig is being recognized, when I check the labels in the vmagent targets, these rules are not applied, they don't even exist.
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: new-le-scrape-config
spec:
  relabelConfigs:
    - source_labels: [__meta_kubernetes_endpoints_label_example]
      target_label: example
    - source_labels: [__meta_kubernetes_endpoints_label_example2]
      target_label: example2
    - source_labels: [__meta_kubernetes_endpoints_label_example3]
      target_label: example3
```
 In the operator logs, I see the following entry:

`{"level":"info","ts":"2024-08-26T15:20:03Z","logger":"controller.VMAgent","msg":"selected scrapeConfigs","vmagent":{"name":"victoria-metrics-k8s-stack","namespace":"vm"},"controller":"vmagent.crud","namespace":"vm","vmagent":"vmagent-victoria-metrics-k8s-stack","scrapeConfigs":"vm/b2ct-le-scrape-config","namespace":"vm","vmagent":"victoria-metrics-k8s-stack"}`

Should I provide some additional configuration to ensure that these relabeling rules are applied to existing serviceScrapes?

Additionally, I tried adding the relabeling configuration directly to the vmagent Helm chart's values file as follows:

```
 extraScrapeConfigs:
    - job_name: "some-labels"
      relabel_configs:
      - source_labels: [__meta_kubernetes_endpoints_label_example]
        target_label: example
      - source_labels: [__meta_kubernetes_endpoints_label_example2]
        target_label: example2
      - source_labels: [__meta_kubernetes_endpoints_label_example3]
        target_label: example3
```
        
However, I encountered the same issue—these relabeling rules do not appear on the targets.

Any guidance on what I might be missing would be greatly appreciated.

```
          - helm_name: victoria-metrics-k8s-stack
            targetRevision: 0.25.2
```
