### ISSUE TITLE
[victoria-metrics-k8s-stack] How to expose Grafana?

### ISSUE THREAD

**Issue by lexfrei** [VictoriaMetrics/helm-charts#134]
Hi!
How should I expose grafana? There is no ingress section in values, so it's not clear for me.

**Comment by f41gh7** [comment]
Hello, this chart uses grafana official chart, so you have to change its parameters. Link for it https://github.com/grafana/helm-charts/tree/main/charts/grafana

 Example of usage, change values.yaml at k8s-stack chart for grafana:

```yaml
#values.yaml
grafana:
  ingress:
    enabled: true
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    labels: {} 
    hosts:
      - chart-example.local
```
