### ISSUE TITLE
standard dashboard work incompletly on rke2 with cilium

### ISSUE THREAD

**Issue by didlawowo** [VictoriaMetrics/helm-charts#1376]
### Describe the bug

i'm using helm with vm K8s stack chart
grafana come with dashboard but some are not working correctly

<img width="1847" alt="image" src="https://github.com/VictoriaMetrics/helm-charts/assets/12622760/97356f95-2951-4fa1-b3e3-c5070f46c016">

<img width="1847" alt="image" src="https://github.com/VictoriaMetrics/helm-charts/assets/12622760/6ee73f99-da58-457d-9637-5219a041fed2">

<img width="1847" alt="image" src="https://github.com/VictoriaMetrics/helm-charts/assets/12622760/42b5c7f4-09c0-4397-87a7-3c7a5a7fc37a">

### To Reproduce

just install stack k8s

### Version

latest

**Comment by AndrewChubatiuk** [comment]
hey @didlawowo 
finally found time to test a case in this issue locally as we are not using RKE2 at all
was able to reproduce issues with scraping kube-scheduler, kube-controller-manager and etcd metrics.
All these services required additional configurations to become scrapable by vmagent

1. In /etc/rancher/rke2/config.yaml had to add several values
```
etcd-expose-metrics: true
kube-scheduler-arg:
  - bind-address=0.0.0.0               # haven't checked how to pass there address from pod metadata instead
kube-controller-manager-arg:
  - bind-address=0.0.0.0               # haven't checked how to pass there address from pod metadata instead
```
2. additional values for k8s-stack
```
kubeControllerManager:
  vmScrape:
    spec:
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
          scheme: https
          tlsConfig:
            caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            serverName: localhost          # maybe I've misconfigured something, but there was an issue until this value was set
            insecureSkipVerify: true        # haven't tried to pass automatically generated certificates in agent nodes
kubeEtcd:
  service:
    port: 2381
    targetPort: 2381
  vmScrape:
    spec:
      endpoints:  
        - port: http-metrics
          scheme: http
kubeScheduler:
  vmScrape:
    spec:
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          tlsConfig:
            caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            serverName: 127.0.0.1
            insecureSkipVerify: true                # haven't tried to pass automatically generated certificates in agent nodes
```
