### ISSUE TITLE
[victoria-metrics-k8s-stack]: vmalert notifier config broken in 0.25.6

### ISSUE THREAD

**Issue by QuentinBtd** [VictoriaMetrics/helm-charts#1378]
Hello,

Here is my config for VM alert (truncated)

```yaml
vmalert:
  spec:
    notifier:
      url: 'http://alertmanager.monitoring.svc:9093'
```

It works with 0.25.5, but not in 0.25.6.

I tried adding this, same result.

```yaml
  additionalNotifierConfigs:
    static_configs:
      - targets:
          - 'http://alertmanager.monitoring.svc:9093'
```

Here is my helm logs

```
template: victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/vmalert.yaml:12:9: executing "victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/vmalert.yaml" at <include "vm.alert.spec" .>: error calling include: template: victoria-metrics-k8s-stack/templates/_helpers.tpl:236:45: executing "vm.alert.spec" at <concat $vmAlertRemotes.notifiers (.Values.vmalert.spec.notifiers | default list)>: error calling concat: runtime error: invalid memory address or nil pointer dereference 
```

FYI, in my case, alertmanager is deployed outside of this chart.
```yaml
alertmanager:
  enabled: false
```
