### ISSUE TITLE
0.24.11 Annotation Too Long

### ISSUE THREAD

**Issue by P-n-I** [VictoriaMetrics/helm-charts#1409]
Just applied 0.24.11 to our cluster and getting this error:
```
ConfigMap "pi-monitoring-vmstack-node-exporter-full" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

**Comment by AndrewChubatiuk** [comment]
are you using argocd?

**Comment by P-n-I** [comment]
Yup

**Comment by AndrewChubatiuk** [comment]
you can try to set:
```
grafana:
  sidecar:
    dashboards:
      additionalDashboardAnnotations
        argocd.argoproj.io/sync-options: ServerSideApply=true
```
