### ISSUE TITLE
[victoria-metrics-k8s-stack] Why is prometheus-node-exporter not a VMNodeScrape?

### ISSUE THREAD

**Issue by towolf** [VictoriaMetrics/helm-charts#1430]
The node_exporter is a subchart and comes with its own ServiceMonitor. This is disabled and the vmstack chart adds its own VMServiceScrape in `templates/servicemonitors/nodeexporter.yaml`

However in a VMServiceScrape, we don't have access to node labels, which would be desirable to be able to configure to route metrics to certain remoteWrite endpoints.

We overrode the config like this and would like to know whether a configurable VMNodeScrape wouldn't be better for upstream.

```yaml
    prometheus-node-exporter:
      service:
        enabled: false
      vmServiceScrape:
        # we deploy our own VMNodeScrape for this below in extraObjects
        enabled: false
...
    extraObjects:
      - apiVersion: operator.victoriametrics.com/v1beta1
        kind: VMNodeScrape
        metadata:
          name: prometheus-node-exporter
        spec:
          relabelConfigs:
            - source_labels: [__address__]
              action: replace
              regex: ([^:]+):.*
              replacement: $1:9100
              target_label: __address__
            - source_labels: [__meta_kubernetes_node_name]
              target_label: node
            - source_labels: [__address__]
              target_label: instance
            - source_labels: [__meta_kubernetes_node_label_kubernetes_io_instance_type]
              target_label: instance_type
            - source_labels: [__meta_kubernetes_node_label_tenant]
              target_label: tenant
            - source_labels: [__meta_kubernetes_node_label_game_server]
              target_label: game-server
          metricRelabelConfigs:
            - source_labels: [job]
              replacement: node-exporter
              target_label: job
            - action: drop
              regex: /var/lib/kubelet/pods.+
              source_labels:
              - mountpoint
```

**Comment by AndrewChubatiuk** [comment]
hey @towolf
you can change scrape type to node scrape like this
```
prometheus-node-exporter:
      service:
        enabled: false
      vmScrape:
        kind: VMNodeScrape
        spec:
          jobLabel: job
          endpoints: []
          relabelConfigs:
            - source_labels: [__address__]
              action: replace
              regex: ([^:]+):.*
              replacement: $1:9100
              target_label: __address__
            - source_labels: [__meta_kubernetes_node_name]
              target_label: node
            - source_labels: [__address__]
              target_label: instance
            - source_labels: [__meta_kubernetes_node_label_kubernetes_io_instance_type]
              target_label: instance_type
            - source_labels: [__meta_kubernetes_node_label_tenant]
              target_label: tenant
            - source_labels: [__meta_kubernetes_node_label_game_server]
              target_label: game-server
          metricRelabelConfigs:
            - source_labels: [job]
              replacement: node-exporter
              target_label: job
            - action: drop
              regex: /var/lib/kubelet/pods.+
              source_labels:
              - mountpoint
```
but to unset endpoints completely I've added PR https://github.com/VictoriaMetrics/helm-charts/pull/1431 to fix it
