### ISSUE TITLE
[victoria-metrics-k8s-stack] Enabling Sigv4 auth for Grafana?

### ISSUE THREAD

**Issue by knuurr** [VictoriaMetrics/helm-charts#1450]
We're using `victoria-metrics-k8s-stack` chart to deploy our self-managed Grafana. However we're also maintaining our legacy AWS-managed Prometheus endpoint, which I can't migrate yet, and I need our instance to be able to query it.

In AWS-managed Grafana I see there was Sigv4 authentication enabled. I also wanted mirror how it was done there on our new instance, but it seems I can't get Sigv4 authentication method to show up in UI, so I can't configure authentication this way.

What changes in values for Helm chart do I need to intrduce to be able to enable Sigv4 to successfully query our AWS-managed Prometheus?

**Comment by AndrewChubatiuk** [comment]
k8s-stack chart uses official grafana helm chart as a dependency, which values are available under `grafana` key in k8s-stack chart. Looks like this is a right documentation, which should help to setup
https://aws.amazon.com/blogs/mt/getting-started-amazon-managed-service-for-prometheus/
values, which are recommended in an article to be set for a chart to k8s-stack can be passed as

```
grafana:
  serviceAccount:
     name: "iamproxy-service-account"
    annotations:

        eks.amazonaws.com/role-arn: "${IAM_PROXY_PROMETHEUS_ROLE_ARN}"
  grafana.ini:
    auth:
      sigv4_auth_enabled: true
```

**Comment by knuurr** [comment]
Here are changes I introduced already to our values file:

```lml
            grafana:
              enabled: true
              extraEnvVars:
                - name: AWS_SDK_LOAD_CONFIG
                  value: "true"
                - name: GF_AUTH_SIGV4_AUTH_ENABLED
                  value: "true"
                  
              grafana.ini:
                auth.sigv4_auth_enabled: 'true'
```
For env variables, I took it from here: [Set up Grafana open source or Grafana Enterprise for use with Amazon Managed Service for Prometheus
](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-query-standalone-grafana.html#:~:text=To%20enable%20SigV4%20on%20Grafana,Grafana%20to%20enable%20SigV4%20support.)

And yet when creating new datasource manually through UI, in "Authentication methods" I don't see any Sigv4 option.

I intentionally skipped part about IAM roles, as we decided to go for IAM Secret keys approach.


We're also provisioning some datasources through ConfigMaps and helm charts. I also tried to provision data source through this approach, so I took working example of another data source and modified it to try this way.

(we use Helm charts + Argo CD for this)

```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clusterName }}-aws-managed-prometheus-data-source
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  {{ .Values.clusterName }}-aws-managed-prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: aws-managed-prometheus
        type: prometheus
        url: <AWS prometheus URL>
        jsonData:
          sigV4Auth: true
          sigV4AuthType: "default"
          sigV4Region: "us-east-1"
          httpMethod: POST
          
```

But with this method this datasource doesn't even appear in UI on the list, while this approach works for our other Prometheus datasource.


What could be wrong here?

**Comment by AndrewChubatiuk** [comment]
> in "Authentication methods" I don't see any Sigv4 option

you specified invalid parameter name, it should be  
```
grafana:
  grafana.ini:
    auth:
      sigv4_auth_enabled: true
```

you can set your own datasources using
```
grafana:
  additionalDataSources:
  - name: aws-managed-prometheus
      type: prometheus
      url: http://localhost:9999
      jsonData:
        sigV4Auth: true
        sigV4AuthType: "default"
        sigV4Region: "us-east-1"
        httpMethod: POST
```
