### ISSUE TITLE
[victoria-metrics-k8s-stack] custom alertmanager configSecret not used by chart

### ISSUE THREAD

**Issue by sando38** [VictoriaMetrics/helm-charts#1461]
Hi,

using `victoria-metrics-k8s-stack` with version `0.25.15` and a custom alertmanager config, included via `configSecret`. The secret is not parsed, when I use the `values.yml` template as in the repository.

```yaml
alertmanager:
  enabled: true
  spec:
  configSecret: ""
```

When I adjust the indentation to the below format, it works.

```yaml
alertmanager:
  enabled: true
  spec:
    configSecret: ""
```
