### ISSUE TITLE
Splitting data streams with vmagent helm chart 

### ISSUE THREAD

**Issue by todorovski** [VictoriaMetrics/helm-charts#1531]
Hi,

I'm using the vmagent helm chart (v0.10.11) and need to split incoming data streams between multiple destinations.
Vmagent supports [splitting data streams among multiple systems](https://docs.victoriametrics.com/vmagent/index.html#splitting-data-streams-among-multiple-systems). However, I can't find a way to configure this splitting behavior through helm chart. 
Using extraArgs, I can specify only one `remoteWrite.url` and one `remoteWrite.urlRelabelConfig`.

Any suggestions on how to achieve this?
Thanks!

**Comment by AndrewChubatiuk** [comment]
hey @todorovski
In extraArgs for each key you can set either string or array value.

**Comment by AndrewChubatiuk** [comment]
hey again
I've added a [PR](https://github.com/VictoriaMetrics/helm-charts/pull/1532)
it allows setting all `remoteWrite.*` flags using `remoteWrite` chart param
in PRs description you can see how it's expected to work

**Comment by todorovski** [comment]
> hey @todorovski In extraArgs for each key you can set either string or array value.
> 
> ```
> extraArgs:
>   remoteWrite.urlRelabelConfig:
>     - /etc/vmagent/config1.yaml
>     - /etc/vmagent/config2.yaml
> ```

Thanks for the suggestion! This will do the job, I just need to ensure that the values in the `remoteWrite.url` and `remoteWrite.urlRelabelConfig` arrays are correctly ordered, so that each urlRelabelConfig corresponds to its respective URL.

**Comment by todorovski** [comment]
> hey again I've added a [PR](https://github.com/VictoriaMetrics/helm-charts/pull/1532) it allows setting all `remoteWrite.*` flags using `remoteWrite` chart param in PR's description you can see how it's expected to work

This looks great! 
Thank you @AndrewChubatiuk for the prompt response!

**Comment by AndrewChubatiuk** [comment]
released in 0.13.0

**Comment by todorovski** [comment]
> hey @todorovski In extraArgs for each key you can set either string or array value.
> 
> ```
> extraArgs:
>   remoteWrite.urlRelabelConfig:
>     - /etc/vmagent/config1.yaml
>     - /etc/vmagent/config2.yaml
> ```

Hello @AndrewChubatiuk,

I tried this approach and set up the following configuration:

```
extraArgs:
  remoteWrite.url:
    - http://vminsert-1:8480/insert/0/prometheus/
    - http://vminsert-2:8480/insert/0/prometheus/
    - http://vminsert-3:8480/insert/0/prometheus/
  remoteWrite.urlRelabelConfig:
    - /relabel-config/relabel-1.yml
    - /relabel-config/relabel-2.yml
    - /relabel-config/relabel-3.yml
```

It works as expected with a Deployment, but not with a StatefulSet, due to a difference in how the `extraArgs` are resolved between the two.

Here’s how the vmagent remoteWrite command-line flags are being resolved with StatefulSet:
```
  args:
    - -remoteWrite.url=[http://vminsert-1:8480/insert/0/prometheus/ http://vminsert-2:8480/insert/0/prometheus/ http://vminsert-3:8480/insert/0/prometheus/]
    - -remoteWrite.urlRelabelConfig=[/relabel-config/relabel-1.yml /relabel-config/relabel-2.yml /relabel-config/relabel-3.yml]

```
<br/>
And here's the error I encounter:

```
VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:204	cannot load relabel configs: cannot load relabel configs from -remoteWrite.urlRelabelConfig="[/relabel-config/relabel-1.yml /relabel-config/relabel-2.yml /relabel-config/relabel-3.yml]": cannot read `relabel_configs` from "[/relabel-config/relabel-1.yml /relabel-config/relabel-2.yml /relabel-config/relabel-3.yml]": cannot read "[/relabel-config/relabel-1.yml /relabel-config/relabel-2.yml /relabel-config/relabel-3.yml]": open [/relabel-config/relabel-1.yml /relabel-config/relabel-2.yml /relabel-config/relabel-3.yml]: no such file or directory

```

<br/>
When using a Deployment, the vmagent remoteWrite command-line flags are resolved correctly as:
          
```
  args:
    - -remoteWrite.url=http://vminsert-1:8480/insert/0/prometheus/
    - -remoteWrite.url=http://vminsert-2:8480/insert/0/prometheus/
    - -remoteWrite.url=http://vminsert-3:8480/insert/0/prometheus/
    - -remoteWrite.urlRelabelConfig=/relabel-config/relabel-1.yml
    - -remoteWrite.urlRelabelConfig=/relabel-config/relabel-2.yml
    - -remoteWrite.urlRelabelConfig=/relabel-config/relabel-3.yml
```

**Comment by AndrewChubatiuk** [comment]
now it's better to use
```
remoteWrite:
  - url: http://vminsert-1:8480/insert/0/prometheus/
     urlRelabelConfig: /relabel-config/relabel-1.yml
  - url: http://vminsert-2:8480/insert/0/prometheus/
    urlRelabelConfig: /relabel-config/relabel-2.yml
  - url: http://vminsert-3:8480/insert/0/prometheus/
    urlRelabelConfig: /relabel-config/relabel-3.yml
```
