### ISSUE TITLE
bug: etcd monitoring does not work properly on vanilla kubeadm v1.31.1

### ISSUE THREAD

**Issue by gecube** [VictoriaMetrics/helm-charts#1543]
Good day!

I am using the latest chart version of `victoria-metrics-k8s-stack`:

```bash
root@master-1:~# helm ls -A | grep victoria
victoria-logs-single      	monitoring-system        	2       	2024-09-30 18:07:35.47983054 +0000 UTC 	deployed	victoria-logs-single-0.6.4       	v0.29.0    
victoria-metrics-k8s-stack	monitoring-system        	9       	2024-09-30 20:56:38.409079006 +0000 UTC	deployed	victoria-metrics-k8s-stack-0.26.0	v1.102.1   
victoria-metrics-operator 	victoria-metrics-operator	1       	2024-09-30 18:00:02.135494903 +0000 UTC	deployed	victoria-metrics-operator-0.35.2 	v0.48.3   
```

I found that etcd monitoring does not work with the defaults as static manifest looks like:

```bash
root@master-1:~# cat /etc/kubernetes/manifests/etcd.yaml 
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/etcd.advertise-client-urls: https://49.13.236.131:2379
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://49.13.236.131:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --experimental-initial-corrupt-check=true
    - --experimental-watch-progress-notify-interval=5s
    - --initial-advertise-peer-urls=https://49.13.236.131:2380
    - --initial-cluster=master-1=https://49.13.236.131:2380
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://49.13.236.131:2379
    - --listen-metrics-urls=http://0.0.0.0:2381
    - --listen-peer-urls=https://49.13.236.131:2380
    - --name=master-1
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    image: registry.k8s.io/etcd:3.5.15-0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 0.0.0.0
        path: /livez
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: etcd
    readinessProbe:
      failureThreshold: 3
      httpGet:
        host: 0.0.0.0
        path: /readyz
        port: 2381
        scheme: HTTP
      periodSeconds: 1
      timeoutSeconds: 15
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 0.0.0.0
        path: /readyz
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
  hostNetwork: true
  priority: 2000001000
  priorityClassName: system-node-critical
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
status: {}
root@maste
```

So it could be clearly seen that etcd exposes metrics on 2381 plain HTTP port. We need to change the section in helm chart:

https://github.com/VictoriaMetrics/helm-charts/blob/de4356f1f1e35e3a5d1af9e3f21c3654400767e6/charts/victoria-metrics-k8s-stack/values.yaml#L1115

to the next values:

```yaml
...
    kubeEtcd:
      enabled: true
      endpoints: []
      service:
        enabled: true
        port: 2381
        targetPort: 2381
        selector:
          component: etcd
      vmScrape:
        spec:
          jobLabel: jobLabel
          namespaceSelector:
            matchNames: [kube-system]
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: http
...
```
