### ISSUE TITLE
bug:victoria-metrics-k8s-stack failed to update object status: VMSingle.operator.victoriametrics.com

### ISSUE THREAD

**Issue by tjwallace** [VictoriaMetrics/helm-charts#1562]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: 0.27.0

**Describe the bug**
After upgrading from `0.25.17` to `0.27.0` the VM operator cannot reconcile.

```
k -n monitoring describe vmsingles.operator.victoriametrics.com victoria-metrics
Name:         victoria-metrics
Namespace:    monitoring
Labels:       app.kubernetes.io/instance=victoria-metrics
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=victoria-metrics-k8s-stack
              app.kubernetes.io/version=v1.104.0
              helm.sh/chart=victoria-metrics-k8s-stack-0.27.0
              helm.toolkit.fluxcd.io/name=victoria-metrics
              helm.toolkit.fluxcd.io/namespace=monitoring
Annotations:  meta.helm.sh/release-name: victoria-metrics
              meta.helm.sh/release-namespace: monitoring
              operator.victoriametrics/last-applied-spec:
                {"image":{"tag":"v1.103.0"},"replicaCount":1,"storage":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"50Gi"}},"stora...
API Version:  operator.victoriametrics.com/v1beta1
Kind:         VMSingle
Metadata:
  Creation Timestamp:  2024-07-12T20:35:09Z
  Finalizers:
    apps.victoriametrics.com/finalizer
  Generation:        7
  Resource Version:  110342617
  UID:               c818f197-6aaa-43be-91a3-028b1f034991
Spec:
  Extra Args:
    dedup.minScrapeInterval:      30s
    Max Labels Per Timeseries:    90
    search.minStalenessInterval:  5m
    vmalert.proxyURL:             http://vmalert-victoria-metrics.monitoring.svc.cluster.local:8080
  Image:
    Tag:  v1.104.0
  License:
  Port:           8429
  Replica Count:  1
  Resources:
    Limits:
      Memory:  2Gi
    Requests:
      Cpu:           500m
      Memory:        512Mi
  Retention Period:  120d
  Storage:
    Access Modes:
      ReadWriteOnce
    Resources:
      Requests:
        Storage:         50Gi
    Storage Class Name:  ceph-block
Status:
  Available Replicas:    0
  Replicas:              0
  Single Status:         expanding
  Unavailable Replicas:  0
  Updated Replicas:      0
Events:
  Type     Reason              Age        From                       Message
  ----     ------              ----       ----                       -------
  Normal   ReconcileEvent      <unknown>  victoria-metrics-operator  starting object update
  Normal   ReconcileEvent      <unknown>  victoria-metrics-operator  starting object update
  Warning  ReconcilationError  <unknown>  victoria-metrics-operator  failed to update object status: VMSingle.operator.victoriametrics.com "victoria-metrics" is invalid: [status.availableReplicas: Required value, status.replicas: Required value, status.unavailableReplicas: Required value, status.updatedReplicas: Required value]
```

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
    # VM Operator deployment
    victoria-metrics-operator:
      enabled: true
      operator:
        disable_prometheus_converter: false # Ensure we keep enabled the converter to sync prom rules to VM rules
        enable_converter_ownership: true # Required to allow VM to remove VM rules it imports if a prometheus rule is deleted

    # Single-binary vm cluster
    vmsingle:
      enabled: true
      spec:
        extraArgs:
          dedup.minScrapeInterval: 30s
          maxLabelsPerTimeseries: "90"
          search.minStalenessInterval: 5m
          vmalert.proxyURL: http://vmalert-victoria-metrics.monitoring.svc.cluster.local:8080
        retentionPeriod: 60d
        storage:
          storageClassName: ceph-block
          resources:
            requests:
              storage: 50Gi
          accessModes:
            - ReadWriteOnce
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 2Gi
      ingress:
        enabled: true
        ingressClassName: internal
        hosts:
          - victoria-metrics.${PUBLIC_DOMAIN}

    # VM Alerting (however, this just watches & passes alerts to alertmanager)
    vmalert:
      enabled: true
      spec:
        replicaCount: 2
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 256Mi
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: vmalert
        extraArgs:
          external.url: https://vmalert.${PUBLIC_DOMAIN}
        notifiers:
          - url: http://alertmanager.monitoring.svc.cluster.local:9093
      ingress:
        enabled: true
        ingressClassName: internal
        hosts:
          - vmalert.${PUBLIC_DOMAIN}

    # VM Data scraping
    vmagent:
      enabled: true
      spec:
        replicaCount: 1
        shardCount: 2
        scrapeInterval: 30s
        externalLabels:
          cluster: main
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 512Mi
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: vmagent
      ingress:
        enabled: true
        ingressClassName: internal
        hosts:
          - vmagent.${PUBLIC_DOMAIN}

    # Extra slack templates
    monzoTemplate:
      enabled: false

    # Scrape configs
    kubelet:
      enabled: true
      spec:
        interval: 30s
        # drop high cardinality label and useless metrics for cadvisor and kubelet
        metricRelabelConfigs:
          - action: labeldrop
            regex: (uid|pod_uid|id)
          - action: labeldrop
            regex: (name)
          - action: drop
            source_labels: [__name__]
            regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
          - action: drop
            source_labels: [__name__]
            regex: (container_tasks_state|container_memory_failures_total)
          - action: drop
            source_labels: [__name__]
            regex: (container_blkio_device_usage_total)
          - action: drop
            source_labels: [__name__]
            regex: (prober_probe_duration_seconds_bucket)
        relabelConfigs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - sourceLabels: [__metrics_path__]
            targetLabel: metrics_path
          - targetLabel: "job"
            replacement: "kubelet"
    kubeApiServer:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeProxy:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false

    # Enable deployment of kube-state-metrics
    kube-state-metrics:
      enabled: false

    # Enable deployment of prometheus-node-exporter
    prometheus-node-exporter:
      enabled: false

    # Enable deployment of grafana
    defaultDashboardsEnabled: false
    grafana:
      enabled: false

    # Enable deployment of alertmanager
    alertmanager:
      enabled: false

    # Prepared sets of default rules
    # Adjust to what scraping functions you have enabled
    # i.e. if you dont have kubeapisever setup & enabled, disable
    #   the kubeApiserver rules below
    defaultRules:
      create: true
      groups:
        etcd: &skipRule
          create: false
        general: &createRule
          create: true
        k8s: *createRule
        kubeApiserver: *createRule
        kubeApiserverAvailability: *createRule
        kubeApiserverBurnrate: *createRule
        kubeApiserverHistogram: *createRule
        kubeApiserverSlos: *createRule
        kubelet: *createRule
        kubePrometheusGeneral: *createRule
        kubePrometheusNodeRecording: *createRule
        kubernetesApps: *createRule
        kubernetesResources: *createRule
        kubernetesStorage: *createRule
        kubernetesSystem: *createRule
        kubeScheduler: *skipRule
        kubeStateMetrics: *createRule
        network: *createRule
        node: *createRule
        vmagent: *createRule
        vmsingle: *createRule
        vmhealth: *createRule
        alertmanager: *skipRule
```
```
