### ISSUE TITLE
bug:Victoria-metrics-operator-clean pod doesn't start

### ISSUE THREAD

**Issue by mdesouky** [VictoriaMetrics/helm-charts#1566]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.27.0.

**Describe the bug**
After installing `victoria-metrics-k8s-stack` `v0.27.0` I get the operator clean pod stuck in pending with the following error message
```
victoria-metrics-k8s-stack-victoria-metrics-operator-cleang94g9   0/1     InvalidImageName   0          3m59s
```
```yaml
containerStatuses:
  - image: bitnami/kubectl:1.30+
    imageID: ""
    lastState: {}
    name: kubectl
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: 'Failed to apply default image tag "bitnami/kubectl:1.30+": couldn''t
          parse image name "bitnami/kubectl:1.30+": invalid reference format'
        reason: InvalidImageName
```

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
victoria-metrics-operator:
  enabled: false
  serviceMonitor:
    enabled: true
  crd:
    create: false
    cleanup:
      enabled: true
      image:
        repository: bitnami/kubectl
        pullPolicy: IfNotPresent
        tag: 1.30
  operator:
    disable_prometheus_converter: true
    useCustomConfigReloader: true
```

**Comment by mdesouky** [comment]
Even when I set tag to `""`
```
crd:
    cleanup:
      enabled: true
      image:
        pullPolicy: IfNotPresent
        repository: bitnami/kubectl
        tag: ""
    create: false
  enabled: true
```
still the same error
