### ISSUE TITLE
bug:  #1553 introduced a regression by producing an invalid VMCluster spec

### ISSUE THREAD

**Issue by Mareo** [VictoriaMetrics/helm-charts#1587]
**Chart name and version**
chart:  victoria-metrics-k8s-stack
version: since v0.27.1

**Describe the bug**
#1553 introduced a regression into the VMCluster template by adding `vminsert` and `vmstorage` keys to the wrong map : https://github.com/VictoriaMetrics/helm-charts/pull/1553/files#diff-95592edf818384aca3ab100b3164575a5eb6e4e67c65d662ef0b6aed2bf6bcdfR380

The resulting template is (abbreviated for clarity):

```yaml
 kind: VMCluster
 spec:
   vmselect:
     vminsert:
       image:
         tag: v1.104.0-cluster
     vmstorage:
       image:
         tag: v1.104.0-cluster
   vmsinsert:
     [...]
   vmstorage:
     [...]
```

instead of:

```yaml
 kind: VMCluster
 spec:
   vmselect:
     [...]
   vminsert:
     image:
       tag: v1.104.0-cluster
     [...]
   vmstorage:
     image:
       tag: v1.104.0-cluster
     [...]
```

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
vmcluster:
  enabled: true
```
