### ISSUE TITLE
bug: VictoriaLogs - missing records (but present in Loki)

### ISSUE THREAD

**Issue by arseny-zinchenko** [VictoriaMetrics/helm-charts#1598]
**Chart name and version**
Helm chart: victoria-logs-single. version: v0.6.3
Docker image: victoriametrics/victoria-logs:v0.35.0-victorialogs
Grafana VictoriaLogs Data source version: 0.5.0

**Describe the bug**
We have a log records with a big `body` field.
They are written to the Loki, but can't be found in VMLogs.

**Loki query**: `{app="backend-api", namespace="prod-backend-api-ns"} |= "b4c2ecd2-000b-46e5-a448-0983963c0688"`
- returns desired records

![image](https://github.com/user-attachments/assets/8e66781d-607d-42aa-a68f-b9f2480bbe28)

**VMlogs query**: `app:="backend-api" namespace:="prod-backend-api-ns" "b4c2ecd2-000b-46e5-a448-0983963c0688"`
- returns noting

![image](https://github.com/user-attachments/assets/05caa98f-3858-46e4-95a0-c0744669078a)

If query by an Amazon X-Ray ID related to the records, then:

**Loki query**: `{app="backend-api", namespace="prod-backend-api-ns"} |= "Root=1-670e6e90-2e398c1005aa39f076ec1428"`
- returns 8 results, including the record with the big `body` field

![image](https://github.com/user-attachments/assets/4e088549-5946-44e5-ab10-d0efc09fde6c)

**VMlogs query**: `app:="backend-api" namespace:="prod-backend-api-ns" "b4c2ecd2-000b-46e5-a448-0983963c0688"`
- returns 7 results, and no record with the big `body` field
![image](https://github.com/user-attachments/assets/9ad4a36e-cc6f-415c-a548-b7bc7957ed2c)

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
  grafana:
    enabled: true
   ...
    env:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "victorialogs-datasource"
    ...
    plugins:
     ...
      - https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.5.0/victorialogs-datasource-v0.5.0.zip;victorialogs-datasource
```
