### ISSUE TITLE
feature:Please enable loading Grafana dashboards from ConfigMap and Grafana marketplace again

### ISSUE THREAD

**Issue by ascknx** [VictoriaMetrics/helm-charts#1616]
**Chart name and version, where you feel a lack of requested feature**
chart: victoria-metrics-k8s-stack
version: v0.27.6

**Is your feature request related to a problem? Please describe.**
This [PR](https://github.com/VictoriaMetrics/helm-charts/pull/1604) removed the possibility to load Grafana dashboards from both ConfigMap and Grafana Marketplace

**Describe the solution you'd like**
Please enable it again

**Describe alternatives you've considered**
Use the original Grafana chart

**Comment by AndrewChubatiuk** [comment]
we're not going to support this as it's not recommended by grafana chart
you can do it by adding
```
grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      nodeexporter:
        gnetId: 1860
        revision: 37
        datasource: VictoriaMetrics
```
