### ISSUE TITLE
bug [Victoria-metrics-k8s-stack]: Can't custom service selector (component scraping)

### ISSUE THREAD

**Issue by pierreblais** [VictoriaMetrics/helm-charts#1619]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.27.4

**problem**
I'm not able to scrape neither kubeControllerManager, kubeEtcd nor kubeScheduler because my Kubernetes ControllerManager, etcd and Scheduler doesn't have `component` label set. So the three following SVC are pointing no pods:

- vmks-victoria-metrics-k8s-stack-kube-controller-manager
- vmks-victoria-metrics-k8s-stack-kube-etcd
- vmks-victoria-metrics-k8s-stack-kube-scheduler

I have tried to override selector:

```yaml
# Component scraping kube scheduler
kubeScheduler:
  # -- Enable KubeScheduler metrics scraping
  enabled: true
  # If using kubeScheduler.endpoints only the port and targetPort are used
  service:
    # -- Enable service for KubeScheduler metrics scrape
    enabled: true
    # -- KubeScheduler service port
    port: 10259
    # -- KubeScheduler service target port
    targetPort: 10259
    # -- KubeScheduler service pod selector
    selector:
      app.kubernetes.io/component: kube-scheduler
      app.kubernetes.io/name: kube-scheduler
```

But `component` label still set as default values, so I have also override it:

```yaml 
# Component scraping kube scheduler
kubeScheduler:
  # -- Enable KubeScheduler metrics scraping
  enabled: true
  # If using kubeScheduler.endpoints only the port and targetPort are used
  service:
    # -- Enable service for KubeScheduler metrics scrape
    enabled: true
    # -- KubeScheduler service port
    port: 10259
    # -- KubeScheduler service target port
    targetPort: 10259
    # -- KubeScheduler service pod selector
    selector:
      component: ""
      app.kubernetes.io/component: kube-scheduler
      app.kubernetes.io/name: kube-scheduler
```

Even like that the  SVC still not able to give traffic to pods. 

**Describe the solution you'd like**
I we provide custom selector, the default one should be added.

Maybe, that's an issue for operator project ?
