### ISSUE TITLE
vmalertmanager ingress service name is hardcoded

### ISSUE THREAD

**Issue by fujin** [VictoriaMetrics/helm-charts#163]
Hi folks,

When using the `victoria-metrics-k8s-stack` chart, and `alertmanager.spec.serviceSpec.spec.type = NodePort` (expected for an GKE L7Lb Ingress), an additional service is created like `{{CRD_TYPE}}-{{CRD_NAME}}-additional-service.`

When trying to make the vmalertmanager Ingress use that service however, we are met with a few issues:
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/ingress.yaml#L4

The first one (obviously) being that GKE ingress wants the service to be NodePort or Loadbalancer, but it's included on the Ingress spec, so generates warning like this:
```  Warning  Translate  9m19s (x26 over 61m)  loadbalancer-controller  Translation failed: invalid ingress spec: service "monitoring/vmalertmanager-monitoring" is type "ClusterIP", expected "NodePort" or "LoadBalancer"```

The second one being that when the `additional-service` is in place, `extraPath` must be used to point to it, like this:
```
  alertmanager:
    ingress:
      extraPaths:
        - path: "/*"
          pathType: "ImplementationSpecific"
          backend:
            # TODO(fujin): Fix this hardcoding? Creates an additional service if we use 'serviceSpec'
            serviceName: vmalertmanager-monitoring-additional-service
            servicePort: 9093
```

Keen to hear your thoughts on how best to put Ingress in front of vmalertmanager Ingress. I may just create an Ingress object out of the chart.

**Comment by f41gh7** [comment]
Hello, for me it looks like, its possible to define new variable for service name at `values.yaml`. And introduce templated example at `_helpers.tpl`.

  Something like: `alertmanager.spec.serviceName` or just checking for non-empty:  `if alertmanager.spec.serviceSpec`.

**Comment by arcud** [comment]
In addition to the workaround suggested by @fujin, using the new Ingress API specs, I added the following to get it to work:

```yaml
alertmanager:
  spec:
    serviceSpec:
      spec:
        type: NodePort
```

and

```yaml
alertmanager:
  ingress:
    extraPaths:
      - path: "/*"
        pathType: "ImplementationSpecific"
        backend:
          service:
            name: "vmalertmanager-{{ .fullnameOverride }}-additional-service"
            port:
              number: 9093
```

Not great that an additional-service is created. Would be good to override the default service's type to `NodePort` to be able to support the GKE L7 load balancer Ingress.

**Comment by AndrewChubatiuk** [comment]
to override default service you can use
```
alertmanager:
  spec:
    serviceSpec:
      useAsDefault: true
      spec:
        type: NodePort
```
