### ISSUE TITLE
bug: Service name change and ServiceAccount name change when migrating from chart v0.13.7 to v0.14.6

### ISSUE THREAD

**Issue by sydevinfra** [VictoriaMetrics/helm-charts#1637]
**Chart name and version**
chart: victoria-metrics-cluster
version: v0.13.7-v0.14.6

**Describe the bug**
When upgrade the cluster from version v1.103.0 (chart v0.13.7) to version v1.105.0 (v0.14.6), there was an error on the StatefulSet for vmstorage.
It was looking for the service account "<_ReleaseName_>-victoria-metrics-cluster" which did not exists.
I was able to edit the StatefulSet to change the following values and the pods were able to start
```yaml
      serviceAccountName: vmstorage
      serviceAccount: vmstorage
```

Also the name of all services changed, and I had to update them in vmagent / vmalert / grafana / ...
Not a big deal but a warning would be nice :)

**Custom values**
```yaml
vmselect:
  name: vmselect
  image:
    tag: v1.105.0-cluster

  extraArgs:
    search.maxQueryLen: 65536

  ingress:
    enabled: true
    ingressClassName: nginx-internal
    annotations:
      kubernetes.azure.com/tls-cert-keyvault-uri: <_REDACTED_>
    hosts:
      - name: <_REDACTED_>
        path: /
        port: http
    tls:
    - secretName: keyvault-vmselect-vmselect
      hosts:
        - <_REDACTED_>

vminsert:
  name: vminsert
  image:
    tag: v1.105.0-cluster

vmstorage:
  name: vmstorage
  image:
    tag: v1.105.0-cluster
  retentionPeriod: 40d
  persistentVolume:
    storageClass: default
    size: 20Gi
```
