### ISSUE TITLE
Enable https to vmauth

### ISSUE THREAD

**Issue by sachinar** [VictoriaMetrics/helm-charts#164]
Hi Team,

How we will be able to enable https for vmauth url for remote_write. We tried tls but no luck. Even documentation is not there for https

**Comment by f41gh7** [comment]
Hello,

  Correct me, if I'm wrong. You are using vmauth with following config:

```yaml
config:
   users:
      - username: "local-single-node"
        password: "***"
        url_prefix: "https://localhost:8428"
```

 and it doesn't work?
