### ISSUE TITLE
feature: Add chart values allowing a pre-defined admin user and Grafana secret, prior chart install

### ISSUE THREAD

**Issue by fmunteanu** [VictoriaMetrics/helm-charts#1657]
**Chart name and version, where you feel a lack of requested feature**
chart: victoria-metrics-k8s-stack
version: v0.27.6

**Is your feature request related to a problem? Please describe.**
Currently the Helm chart will create a `vmks-grafana` secret with random `admin` user credentials. Updating the secret will not refresh the `admin-password`, since the service is already running.

**Describe the solution you'd like**
There are settings in [Grafana Helm chart](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L445C1-L454C30):

```
# Administrator credentials when not using an existing secret (see below)
adminUser: admin
# adminPassword: strongpassword

# Use an existing secret for the admin user.
admin:
  ## Name of the secret. Can be templated.
  existingSecret: ""
  userKey: admin-user
  passwordKey: admin-password
```

Implementing these missing values will allow end-user to create their own custom secret and define a different admin user.

**Comment by fmunteanu** [comment]
Actually, creating the secret prior chart install and passing the new keys/values into `victoria-metrics-k8s-stack` `values.yaml` works, somehow the values are passed to Grafana helm chart:

```
grafana:
  admin:
    existingSecret: vmks-grafana
```

Secret:

```
apiVersion: v1
kind: Secret
metadata:
  name: vmks-grafana
  namespace: kube-system
stringData:
  admin-password: password
  admin-user: admin
type: Opaque
```
