### ISSUE TITLE
Grafana Default Dashboards - No Data

### ISSUE THREAD

**Issue by stephenrob** [VictoriaMetrics/helm-charts#170]
I've deployed a VictoriaMetrics Cluster using the operator and have this working fine.

I've just deployed the grafana dashboards using the following values file to generate the dashboards using the k8s-stack helm chart and output them to a file using dry run and the following command.

```
helm install victoria-metrics-k8s-stack vm/victoria-metrics-k8s-stack -f values.yaml -n cluster-monitoring --dry-run > /tmp/vm-k8s.yaml
```

**values.yaml**
```
grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
      createVMReplicasDatasources: false
    dashboards:
      enabled: true
      multicluster: true

  additionalDataSources: []

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      victoriametrics:
        url: https://raw.githubusercontent.com/VictoriaMetrics/VictoriaMetrics/master/dashboards/victoriametrics.json
      vmagent:
        url: https://raw.githubusercontent.com/VictoriaMetrics/VictoriaMetrics/master/dashboards/vmagent.json
      nodeexporter:
        gnetId: 1860
        revision: 22
        datasource: VictoriaMetrics

  defaultDashboardsEnabled: true
```

This generates the dashboards fine and allows them to be loaded in to grafana. The problem is some of the metrics don't show any data unless the metric query is modified.

An example is Cluster Memory Utilisation on the Kubernetes / Computer Resources / Cluster dashboard:

With the metrics query as generated:

```
1 - sum(:node_memory_MemAvailable_bytes:sum{cluster="$cluster"}) / sum(node_memory_MemTotal_bytes{cluster="$cluster"})
```

The result is:

![CleanShot 2021-07-05 at 17 11 30](https://user-images.githubusercontent.com/4558793/124498847-f6d5f180-ddb4-11eb-9469-704a2f1d2c00.png)

When the metrics query is changed to:

```
1 - sum(node_memory_MemAvailable_bytes{cluster="$cluster"}) / sum(node_memory_MemTotal_bytes{cluster="$cluster"})
```

Then the result is

![CleanShot 2021-07-05 at 17 19 03](https://user-images.githubusercontent.com/4558793/124498984-28e75380-ddb5-11eb-9826-151408d80714.png)

Which seems accurate for the current use on our monitoring cluster.

There are many dashboards that have the same problem where the query syntax needs changing, Is this something specific to the VictoriaMetrics chart and datasource or is this an upstream issue with the kube-prometheus dashboards and how they are sync'd using `sync_grafana_dashboards.py`
