### ISSUE TITLE
bug: Invalid URL for VMAlert remoteWrite when remoteWriteVMAgent is set to true

### ISSUE THREAD

**Issue by filipbnkd** [VictoriaMetrics/helm-charts#1706]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: 0.28.2

**Describe the bug**

When you set `remoteWriteVMAgent` to `true` for vmalert component it renders invalid URL for remote write. URL has double `/` at the begging of the path, e.g. `http://vmagent-vm-stack.monitoring.svc:8429//api/v1/write`

Here is screenshot from diff in ArgoCD
![Screenshot 2024-11-07 at 12 13 38](https://github.com/user-attachments/assets/4d58b8b0-3e16-422b-925d-4040563656b3)

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
vmsingle:
  enabled: false

vmcluster:
  enabled: true

vmalert:
  enabled: true
  remoteWriteVMAgent: true

vmagent:
  enbled: true
```

```sh
> helm template vm/victoria-metrics-k8s-stack -f values.yaml | grep "url: http://vmagent"
url: http://vmagent-release-name-victoria-metrics-k8s-stack.monitoring.svc:8429//api/v1/write
```
