### ISSUE TITLE
[victoria-metrics-k8s-stack] bug: etcd dashboard doesn't work in multicluster setups

### ISSUE THREAD

**Issue by maxpain** [VictoriaMetrics/helm-charts#1713]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.28.2

**Describe the bug**
<img width="1162" alt="image" src="https://github.com/user-attachments/assets/b32c6225-ba23-43ee-b0e2-1ee99d197aeb">

<img width="775" alt="image" src="https://github.com/user-attachments/assets/de395939-aca5-4ed6-9e74-576ab50eb512">

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
vmagent:
  spec:
    externalLabels:
      cluster: hetzner-hel

grafana:
  sidecar:
    dashboards:
      searchNamespace: ALL
      multicluster: true
```
