### ISSUE TITLE
VMagent Cluster ExternalLabel

### ISSUE THREAD

**Issue by Twisterrr** [VictoriaMetrics/helm-charts#1715]
Hello,

I am monitoring my 4 Kubernetes clusters. On my main cluster I have the K8S victoria metrics stack installed with as label on my main cluster in :
```yml 
externalLabels:
 cluster: main
```
However, on VMagent values the variable doesn't exist, and I can't manage to do the same thing on my other clusters. 
What can I do ?

**Comment by Twisterrr** [comment]
@AndrewChubatiuk Yes, it's done

**Comment by AndrewChubatiuk** [comment]
please check the docs
https://docs.victoriametrics.com/operator/api/#vmagentspec
vmagentspec has externalLabels, which can be set like this
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent-select-all
spec:
  # ...
  externalLabels:
    label: value
```

**Comment by Twisterrr** [comment]
I've tried both ways but neither works (see below):
![image](https://github.com/user-attachments/assets/3f844a36-48fb-4b96-9702-f882c84e95f3)
![image](https://github.com/user-attachments/assets/ee5866f6-c619-4f4d-a1a6-46d2717eb2ab)

As you can see on VMUI, only my main cluster (which has a vmagent since the stack-K8s) appears and not my “test” cluster.
![image](https://github.com/user-attachments/assets/9d2c943a-394e-4d8b-b1ec-8407090c0bcb)

**Comment by AndrewChubatiuk** [comment]
![image](https://github.com/user-attachments/assets/918be6ac-fc2c-4282-9e8a-cd26c093f13a)
Is this configuration for victoria-metrics-agent chart?

**Comment by AndrewChubatiuk** [comment]
regarding agent, which is created by CR
![image](https://github.com/user-attachments/assets/12f39837-21de-4c4b-89a4-ff5ee41779b8)
have you check it's logs?
can you find it's metrics in a cluster?

**Comment by Twisterrr** [comment]
in fact, I retrieve the metrics from my cluster and insert them into the VM DB. But no label is detected. And I didn't see any “error” in my vmagent pod on my test cluster.

**Comment by AndrewChubatiuk** [comment]
which is a version of vmagent, operator and k8s-stack chart?

**Comment by Twisterrr** [comment]
Vmagent : 0.14.4
K8s-Stack : 0.25.0

**Comment by AndrewChubatiuk** [comment]
in victoria-metrics-vmagent chart you should be able to pass external labels using `config.global.exernal_labels`

**Comment by AndrewChubatiuk** [comment]
hey @Twisterrr 
can you confirm you've tried setting `config.global.exernal_labels`?

**Comment by Twisterrr** [comment]
Hey @AndrewChubatiuk,
I have it on victoriametrics-stack but on vmagent-chart its not working

**Comment by AndrewChubatiuk** [comment]
i mean not `externalLabels.cluster`, but `config.global.exernal_labels`

**Comment by Twisterrr** [comment]
Well, I tried that : 
![image](https://github.com/user-attachments/assets/161f86c9-f8b4-4da5-9e09-e631810b593d)

But still nothing with this query : 
![image](https://github.com/user-attachments/assets/9a36e4fe-acb4-4355-b0a3-ae13231f8d48)

**Comment by Hela98** [comment]
Hello, I've encountered the same issue. I tried configuring the labels using extraArgs in the Helm chart as 
`extraArgs:
  remoteWrite.label: [ env=dev ]` , 
I've also tried setting external_labels in the global section, as shown in your screenshots: `config:
  global:
    external_labels:
      env: dev
` 
However, this approach didn’t work either, and I'm still unable to see the metrics with the env=dev label in the queries.

**Comment by AndrewChubatiuk** [comment]
@Hela98 @Twisterrr 
by default victoria-metrics-agent chart doesn't scrape neither vmcluster nor vmsingle metrics you need add a custom scrape configuration like this (agent, which is deployed by victoria-metrics-agent scrapes single deployed by victoria-metrics-single). 
```
extraScrapeConfigs:
  - job_name: vmsingle
    kubernetes_sd_configs: 
      - role: service
    relabel_configs:
        - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
          regex: victoria-metrics-single
          action: keep
        - target_label: __address__
          target_label: instance
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_service_name]
          target_label: service
```
If you deploy VMAgent using operator CR you also need to pass extra option to scrape all targets by default
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: example
spec:
  externalLabels:
    cluster: test
  selectAllByDefault: true
```
```
