### ISSUE TITLE
[victoria-logs-single] bug: duplicate entries for key [name="VECTOR_SELF_NODE_NAME"]

### ISSUE THREAD

**Issue by maxpain** [VictoriaMetrics/helm-charts#1727]
```Could not determine release state: unable to determine cluster state: DaemonSet/logging/vls-vector dry-run failed: failed to create typed patch object (logging/vls-vector; apps/v1, Kind=DaemonSet): .spec.template.spec.containers[name="vector"].env: duplicate entries for key [name="VECTOR_SELF_NODE_NAME"]```

I checked the generated `DaemonSet`, and indeed, it has a duplicated `VECTOR_SELF_NODE_NAME` key:
```yaml
containers:
- name: vector
  image: timberio/vector:0.42.0-distroless-libc
  args:
    - '--config-dir'
    - /etc/vector/
  env:
    - name: VECTOR_LOG
      value: info
    - name: VECTOR_SELF_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: VECTOR_SELF_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: VECTOR_SELF_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: VECTOR_SELF_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
```

This key is already included here:
https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/_pod.tpl#L67
