### ISSUE TITLE
bug: Alertmanager deployment does not respect alertmanager.configMap value

### ISSUE THREAD

**Issue by cwstrommer** [VictoriaMetrics/helm-charts#1734]
**Chart name and version**
chart: victoria-metrics-alert
version: v0.12.4

**Describe the bug**
In our environment we manage the alertmanager routes and receiver configuration externally, and reference it via `alertmanager.configMap` when we render the Helm chart.  Version `0.12.4` retains `alertmanager.configMap` in the values, but does not respect it because the Deployment spec changed from

```yaml
        - name: config
          configMap:
            name: {{ include "vmalert.alertmanager.configname" . }}
```
to
```yaml
        - name: config
          configMap:
            name: {{ $fullname }}-config
```
This causes the pod to fail with
```
  Warning  FailedMount      98s (x53 over 93m)  kubelet       MountVolume.SetUp failed for volume "config" : configmap "victoria-metrics-alert-alertmanager-config" not found
```

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
alertmanager:
  podMetadata:
    annotations:
      checksum/external-config: a40ca23bddd5c80ab3cf63c7dcb80844
  configMap: victoria-metrics-alert-external-config
```
