### ISSUE TITLE
bug: victoria-metrics-agent  v0.14.7 incorrect args passed (incorrect order/value)

### ISSUE THREAD

**Issue by vhajdukd** [VictoriaMetrics/helm-charts#1754]
**Chart name and version**
chart: victoria-metrics-agent
version: v0.14.7

**Describe the bug**
When defining specific `remoteWrite.url` overrides / properties - those are appended to the global section instead of retaining the order of properties. This is a groundbreaking issue when working with multiple remoteWrites in a single configuration.

Example at the bottom.

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
image:
  tag: v1.105.0
fullnameOverride: vmagent-general

deployment:
  enabled: false
statefulset:
  enabled: true

persistence:
  enabled: true
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  size: 4Gi

serviceAccount:
  create: true

service:
  enabled: true
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8429'
  labels: {}
  type: NodePort

resources:
  limits:
    cpu: 1750m
    memory: 1.5Gi
  requests:
    cpu: 1200m
    memory: 1Gi
    ephemeral-storage: 4Gi

rbac:
  create: true
  pspEnabled: true

podDisruptionBudget:
  enabled: true
  minAvailable: 40%
  selector:
    matchLabels:
      app.kubernetes.io/instance: vmagent-general

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: vmagent-general
          topologyKey: kubernetes.io/hostname
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: vmagent-general

remoteWrite:
  - url: http://vminsert-general.monitoring.svc.cluster.local/insert/0/prometheus/api/v1/write
    urlRelabelConfig: /relabel_configs/general_relabel.yaml
  - url: http://vminsert-jailhouse.monitoring.svc.cluster.local/insert/0/prometheus/api/v1/write
    urlRelabelConfig: /relabel_configs/jailhouse_relabel.yaml
    showURL: true
    disableOnDiskQueue: true
    dropSamplesOnOverload: true

extraArgs:
  promscrape.streamParse: true
  promscrape.suppressScrapeErrors: true
  promscrape.suppressDuplicateScrapeTargetErrors: true
  loggerErrorsPerSecondLimit: 20
  promscrape.discovery.concurrency: 200
  promscrape.maxDroppedTargets: 100000
  influxSkipSingleField: true
  usePromCompatibleNaming: true
  remoteWrite.queues: 64
  maxConcurrentInserts: 4

extraVolumes:
  - name: relabel-config
    configMap:
      name: vmagent-relabeling
extraVolumeMounts:
  - name: relabel-config
    mountPath: /relabel_configs

config:
  global:
    scrape_interval: 30s
    scrape_timeout: 5s
  scrape_configs: []
```

# Broken config result from the chart:
```
          args: 
            - --envflag.enable=true
            - --envflag.prefix=VM_
            - --influxSkipSingleField
            - --loggerErrorsPerSecondLimit=20
            - --loggerFormat=json
            - --maxConcurrentInserts=4
            - --promscrape.config=/config/scrape/scrape.yml
            - --promscrape.discovery.concurrency=200
            - --promscrape.maxDroppedTargets=100000
            - --promscrape.streamParse
            - --promscrape.suppressDuplicateScrapeTargetErrors
            - --promscrape.suppressScrapeErrors
            - --remoteWrite.disableOnDiskQueue
            - --remoteWrite.dropSamplesOnOverload
            - --remoteWrite.queues=64
            - --remoteWrite.showURL
            - --remoteWrite.tmpDataPath=/tmpData
            - --remoteWrite.url=http://vminsert-general.monitoring.svc.cluster.local/insert/0/prometheus/api/v1/write
            - --remoteWrite.url=http://vminsert-jailhouse.monitoring.svc.cluster.local/insert/0/prometheus/api/v1/write
            - --remoteWrite.urlRelabelConfig=/relabel_configs/general_relabel.yaml
            - --remoteWrite.urlRelabelConfig=/relabel_configs/jailhouse_relabel.yaml
            - --usePromCompatibleNaming
```

Expected config from the chart:
```
          args: 
            - --envflag.enable=true
            - --envflag.prefix=VM_
            - --influxSkipSingleField
            - --loggerErrorsPerSecondLimit=20
            - --loggerFormat=json
            - --maxConcurrentInserts=4
            - --promscrape.config=/config/scrape/scrape.yml
            - --promscrape.discovery.concurrency=200
            - --promscrape.maxDroppedTargets=100000
            - --promscrape.streamParse
            - --promscrape.suppressDuplicateScrapeTargetErrors
            - --promscrape.suppressScrapeErrors
            - --remoteWrite.queues=64
            - --remoteWrite.tmpDataPath=/tmpData
            - --remoteWrite.url=http://vminsert-general.monitoring.svc.cluster.local/insert/0/prometheus/api/v1/write
            - --remoteWrite.urlRelabelConfig=/relabel_configs/general_relabel.yaml
            - --remoteWrite.url=http://vminsert-jailhouse.monitoring.svc.cluster.local/insert/0/prometheus/api/v1/write
            - --remoteWrite.disableOnDiskQueue
            - --remoteWrite.dropSamplesOnOverload
            - --remoteWrite.showURL
            - --remoteWrite.urlRelabelConfig=/relabel_configs/jailhouse_relabel.yaml
            - --usePromCompatibleNaming
```
Order matters in this case.

**Comment by AndrewChubatiuk** [comment]
try updating your config to 
```
remoteWrite:
  - url: http://vminsert-general.monitoring.svc.cluster.local/insert/0/prometheus/api/v1/write
    urlRelabelConfig: /relabel_configs/general_relabel.yaml
    showURL: false
    disableOnDiskQueue: false
    dropSamplesOnOverload: false
  - url: http://vminsert-jailhouse.monitoring.svc.cluster.local/insert/0/prometheus/api/v1/write
    urlRelabelConfig: /relabel_configs/jailhouse_relabel.yaml
    showURL: true
    disableOnDiskQueue: true
    dropSamplesOnOverload: true
```
in what you called "broken result" order the is correct, problem there is that `showURL: true`, `disableOnDiskQueue: true` and `dropSamplesOnOverload: true` is applied to both remote writes as each if these flags is passed only once

**Comment by vhajdukd** [comment]
Hi,

This is the result for:
```
remoteWrite:
  - url: http://vminsert-general.monitoring.svc.cluster.local/insert/0/prometheus/api/v1/write
    urlRelabelConfig: /relabel_configs/general_relabel.yaml
    showURL: false
    disableOnDiskQueue: false
    dropSamplesOnOverload: false
  - url: http://vminsert-jailhouse.monitoring.svc.cluster.local/insert/0/prometheus/api/v1/write
    urlRelabelConfig: /relabel_configs/jailhouse_relabel.yaml
    showURL: true
    disableOnDiskQueue: true
    dropSamplesOnOverload: true
```

result:
```
          args: 
            - --envflag.enable=true
            - --envflag.prefix=VM_
            - --influxSkipSingleField
            - --loggerErrorsPerSecondLimit=20
            - --loggerFormat=json
            - --maxConcurrentInserts=4
            - --promscrape.config=/config/scrape/scrape.yml
            - --promscrape.discovery.concurrency=200
            - --promscrape.maxDroppedTargets=100000
            - --promscrape.streamParse
            - --promscrape.suppressDuplicateScrapeTargetErrors
            - --promscrape.suppressScrapeErrors
            - remoteWrite.disableOnDiskQueue
            - --remoteWrite.disableOnDiskQueue
            - remoteWrite.dropSamplesOnOverload
            - --remoteWrite.dropSamplesOnOverload
            - --remoteWrite.queues=64
            - remoteWrite.showURL
            - --remoteWrite.showURL
            - --remoteWrite.tmpDataPath=/tmpData
            - --remoteWrite.url=http://vminsert-general.monitoring.svc.cluster.local/insert/0/prometheus/api/v1/write
            - --remoteWrite.url=http://vminsert-jailhouse.monitoring.svc.cluster.local/insert/0/prometheus/api/v1/write
            - --remoteWrite.urlRelabelConfig=/relabel_configs/general_relabel.yaml
            - --remoteWrite.urlRelabelConfig=/relabel_configs/jailhouse_relabel.yaml
            - --usePromCompatibleNaming
```

Which seems to be completely wrong as params are not even passed as arguments.
