### ISSUE TITLE
bug: kubeEtcd metrics not available in Grafana

### ISSUE THREAD

**Issue by fmunteanu** [VictoriaMetrics/helm-charts#1761]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.28.3

**Describe the bug**
I'm running K3s (3 cp + 5 workers), which embeds `etcd` into their binary. I recently migrated from `kube-prometheus-stack` and for some reason, the `etcd` metrics are not available In Grafana. All other dashboards work as expected, I was not experiencing this issue with `kube-prometheus-stack` helm chart.

![image](https://github.com/user-attachments/assets/fc3452ff-25b1-4db4-90a6-e9620d5edd39)

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
kubeEtcd:
  enabled: true
  endpoints:
  - 192.168.4.2
  - 192.168.4.3
  - 192.168.4.4
```

All `kubeEtcd` chart values:

```
kubeEtcd:
  enabled: true
  endpoints:
  - 192.168.4.2
  - 192.168.4.3
  - 192.168.4.4
  service:
    enabled: true
    port: 2379
    selector:
      component: etcd
    targetPort: 2379
  vmScrape:
    spec:
      endpoints:
      - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        port: http-metrics
        scheme: https
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      jobLabel: jobLabel
      namespaceSelector:
        matchNames:
        - kube-system
```

All helm chart custom values:

```
# helm get values vmks -n kube-system
USER-SUPPLIED VALUES:
alertmanager:
  config:
    inhibit_rules:
    - equal:
      - cluster
      - namespace
      - alertname
      source_matchers:
      - severity="critical"
      target_matchers:
      - severity=~"info|warning"
    - equal:
      - cluster
      - namespace
      - alertname
      source_matchers:
      - severity="warning"
      target_matchers:
      - severity="info"
    - equal:
      - cluster
      - namespace
      source_matchers:
      - alertname="InfoInhibitor"
      target_matchers:
      - severity="info"
    route:
      group_by:
      - alertgroup
      - job
      group_interval: 5m
      group_wait: 30s
      repeat_interval: 12h
  spec:
    configReloaderResources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
    podAntiAffinity: hard
    replicaCount: 2
    resources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
defaultDashboards:
  defaultTimezone: utc
  enabled: true
global:
  cluster:
    dnsDomain: cluster.local.
  clusterLabel: default
grafana:
  admin:
    existingSecret: vmks-grafana
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
  sidecar:
    resources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
kubeControllerManager:
  endpoints:
  - 192.168.4.2
  - 192.168.4.3
  - 192.168.4.4
kubeEtcd:
  endpoints:
  - 192.168.4.2
  - 192.168.4.3
  - 192.168.4.4
kubeProxy:
  enabled: true
  endpoints:
  - 192.168.4.2
  - 192.168.4.3
  - 192.168.4.4
kubeScheduler:
  endpoints:
  - 192.168.4.2
  - 192.168.4.3
  - 192.168.4.4
prometheus-operator-crds:
  enabled: true
victoria-metrics-operator:
  operator:
    enable_converter_ownership: true
    prometheus_converter_add_argocd_ignore_annotations: true
vmalert:
  spec:
    configReloaderResources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
    resources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
vmcluster:
  enabled: true
  spec:
    replicationFactor: 2
    retentionPeriod: 72h
    vminsert:
      replicaCount: 2
      resources:
        limits:
          cpu: null
          memory: 144Mi
        requests:
          cpu: 10m
          memory: 144Mi
    vmselect:
      replicaCount: 2
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
      storage:
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
            storageClassName: longhorn
    vmstorage:
      replicaCount: 2
      resources:
        limits:
          cpu: null
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 1Gi
      storage:
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: longhorn
vmsingle:
  enabled: false
```

**Comment by fmunteanu** [comment]
Hi @AndrewChubatiuk, thank you for the good pointers. I see a bunch of `kube-controller-manager`, `kube-etcd`, `kube-proxy` and `kube-scheduler` related warnings into `vmagent` logs. I don't have `kube-proxy` enabled in my cluster and is also disabled into helm chart.

[vmagent-vmks-victoria-metrics-k8s-stack-bf64497b8-p7r4x.log](https://github.com/user-attachments/files/17770467/vmagent-vmks-victoria-metrics-k8s-stack-bf64497b8-p7r4x.log)

Unhealthy targets, I highlighted `etcd`:

![image](https://github.com/user-attachments/assets/ffe22710-3875-49e3-93ba-059939170281)

I'm running K3s, which embeds `etcd` into their binary, I don't see any `etcd` pods in my cluster. Not sure how to verify your related ask. Thank you for taking the time to read all this.

**Comment by AndrewChubatiuk** [comment]
you've mentioned that prometheus-k8s-stack works, so it makes sense to try to change a target port (`kubeEtcd.service.targetPort: 2381`) and to remove component label (`kubeEtcd.service.selector.component: null`)

**Comment by fmunteanu** [comment]
I kube-promethus-stack, I had the following relevant settings:

```
kubeEtcd:
  endpoints:
  - 192.168.4.2
  - 192.168.4.3
  - 192.168.4.4
prometheus:
  prometheusSpec:
    enableAdminAPI: true
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    replicaExternalLabelName: replica
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
```

Not sure if there are any related settings in VM. I will try your above mentioned settings.

**Comment by fmunteanu** [comment]
@AndrewChubatiuk after implementing your suggested settings, I get a different error message:

![image](https://github.com/user-attachments/assets/cb857de0-4589-4add-a00c-a0f491687662)

> cannot perform request to "https://192.168.4.2:2381/metrics": Get "https://192.168.4.2:2381/metrics": http: server gave HTTP response to HTTPS client

Chart settings:

```
kubeEtcd:
  enabled: true
  endpoints:
  - 192.168.4.2
  - 192.168.4.3
  - 192.168.4.4
  service:
    enabled: true
    port: 2381
    selector: {}
    targetPort: 2381
  vmScrape:
    spec:
      endpoints:
      - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        port: http-metrics
        scheme: https
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      jobLabel: jobLabel
      namespaceSelector:
        matchNames:
        - kube-system
```

**Comment by AndrewChubatiuk** [comment]
also need to change a `scheme` to `http`

**Comment by fmunteanu** [comment]
@AndrewChubatiuk instead of using `http`, I've enabled `https`:

```
kubeEtcd:
  endpoints:
  - 192.168.4.2
  - 192.168.4.3
  - 192.168.4.4
  serviceMonitor:
    https: true
    insecureSkipVerify: true
    scheme: https
    serverName: localhost
```

However, `insecureSkipVerify` setting is completely ignored:

> cannot perform request to "https://192.168.4.2:2379/metrics": Get "https://192.168.4.2:2379/metrics": tls: failed to verify certificate: x509: certificate signed by unknown authority

![image](https://github.com/user-attachments/assets/294d0106-a85e-4492-8b34-1ff4fe72586b)

This happens only for `kubeEtcd`, I don't have this issue with `kubeControllerManager`, for example. See the [related issue](https://github.com/VictoriaMetrics/helm-charts/issues/1765) I opened.

What is the actual `kubeEtcd.serviceMonitor` template used by VMKS?

**Comment by AndrewChubatiuk** [comment]
@fmunteanu please check my answer [here](https://github.com/VictoriaMetrics/helm-charts/issues/1765#issuecomment-2480462202)

**Comment by fmunteanu** [comment]
Thank you @AndrewChubatiuk, I followed your instructions and I have another minor block on `kubeEtcd` only:

```
kubeEtcd:
  endpoints:
    - 192.168.4.2
    - 192.168.4.3
    - 192.168.4.4
  vmScrape:
    spec:
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
          scheme: https
          tlsConfig:
            caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecureSkipVerify: true
            serverName: localhost
```

The above configuration produces this error:

> cannot perform request to "https://192.168.4.2:2379/metrics": Get "https://192.168.4.2:2379/metrics": remote error: tls: certificate required

![image](https://github.com/user-attachments/assets/418ca98b-6b21-4ac5-9c9a-709824413a89)

K3s stores all etcd related certificates into:

```
# ls -lah /var/lib/rancher/k3s/server/tls/etcd
total 48K
drwxr-xr-x 2 root root 4.0K Nov 16 00:01 .
drwx------ 4 root root 4.0K Nov 16 00:01 ..
-rw-r--r-- 1 root root 1.2K Nov 16 00:01 client.crt
-rw------- 1 root root  227 Nov 16 00:01 client.key
-rw-r--r-- 1 root root  566 Nov 16 00:01 peer-ca.crt
-rw------- 1 root root  227 Nov 16 00:01 peer-ca.key
-rw-r--r-- 1 root root 1.3K Nov 16 00:01 peer-server-client.crt
-rw------- 1 root root  227 Nov 16 00:01 peer-server-client.key
-rw-r--r-- 1 root root  574 Nov 16 00:01 server-ca.crt
-rw------- 1 root root  227 Nov 16 00:01 server-ca.key
-rw-r--r-- 1 root root 1.3K Nov 16 00:01 server-client.crt
-rw------- 1 root root  227 Nov 16 00:01 server-client.key
```

Does the above error requires an additional certificate to be defined into `tlsConfig`?

**Comment by AndrewChubatiuk** [comment]
you need to mount client cert, key and ca into vmagent and specify in a tlsConfig section `keyFile`, `certFile` and `caFile` or put them into secrets and set `ca`, `cert`, `keySecret` k8s secret selectors. another option is to disable tls and use http scheme to scrape metrics

**Comment by fmunteanu** [comment]
I think the recommended way is to create a `vmks-etcd-tls-configuration` secret where I store the related etcd `ca.crt`, `tls.crt` and `tls.key` b64encoded data, similar to `vmks-victoria-metrics-operator-validation` secret. I created the following secret:

```
# kubectl describe secret vmks-etcd-tls-configuration -n kube-system
Name:         vmks-etcd-tls-configuration
Namespace:    kube-system
Labels:       app.kubernetes.io/instance=vmks
              app.kubernetes.io/name=vmks-etcd-tls-configuration
Annotations:  <none>

Type:  kubernetes.io/tls

Data
====
ca.crt:   570 bytes
tls.crt:  1270 bytes
tls.key:  227 bytes
```

I was looking at the [documentation](https://docs.victoriametrics.com/operator/api/#tlsconfig) and I'm not sure how to define the related secret data, into `tlsConfig`. If you could give me few quick pointers, it will be much appreciated.

```
kubeEtcd:
  endpoints:
    - 192.168.4.2
    - 192.168.4.3
    - 192.168.4.4
  vmScrape:
    spec:
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
          scheme: https
          tlsConfig:
            ca: DEFINE ca.crt data from vmks-etcd-tls-configuration secret HERE
            cert: DEFINE tls.crt data from vmks-etcd-tls-configuration secret HERE
            keySecret: DEFINE tls.key data from vmks-etcd-tls-configuration secret HERE
            insecureSkipVerify: true
            serverName: localhost
```

**Comment by fmunteanu** [comment]
I did some research and `etcd` metrics are available via plaintext on the dedicated 2379 metrics port. The 2380 client port is only used by `etcd` grpc API clients, while Prometheus `http` API is using 2381 port. I'm going to use the `http` scheme to scrape metrics, as this is the general consensus.

```
kubeEtcd:
  endpoints:
    - 192.168.4.2
    - 192.168.4.3
    - 192.168.4.4
  service:
    port: 2381
    targetPort: 2381
  vmScrape:
    spec:
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
          scheme: http
```

**Comment by fmunteanu** [comment]
@AndrewChubatiuk I forgot to mention, since the most common installation is to use the dedicated 2381 port, should I do a PR for it?

**Comment by AndrinGautschi** [comment]
For future visitors: https://github.com/VictoriaMetrics/helm-charts/issues/1761#issuecomment-2480920020 is not everything. First of all, you have to enable k3s metrics (this is usually done with some [start up parameters on k3s](https://docs.k3s.io/reference/metrics?_highlight=metrics#k3s-cluster-management-metrics)). Then, if you, like me, have installed the vm-stack into one namespace (via `kustomize build ...  --enable-helm | kubectl apply -f -` for example), you will have to make sure vmScrape goes looking for the service in the correct namespace. The following worked for me:

```yaml
kubeEtcd:
  enabled: true
  # Since we use k3s, etcd is bundled into a binary instead of running as a pod. Therefore, we have to query the control plane nodes directly.
  endpoints: ["192.168.4.2", "192.168.4.3", "192.168.4.4"] # your own control plane node ips
  service:
    enabled: true
    port: 2381
    targetPort: 2381
  vmScrape:
    spec:
      namespaceSelector:
        matchNames:
          - yournamespace
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
          scheme: http
```

**Comment by fmunteanu** [comment]
@AndrinGautschi thank you, I will add it to my Helm chart [configuration](https://github.com/axivo/k3s-cluster/blob/main/roles/victoria-metrics/templates/values.j2) also, since this is an actual template variable:

```yaml
kubeEtcd:
{% if k3s_map.server.ha is falsy %}
  enabled: false
{% endif %}
  endpoints:
    {{ k3s_map_server.ips | to_nice_yaml | indent(4) | trim }}
  service:
    port: 2381
    targetPort: 2381
  vmScrape:
    spec:
      endpoints:
        - port: http-metrics
          scheme: http
      namespaceSelector:
        matchNames:
          - {{ victoriametrics_vars.kubernetes.namespace }}
```

You don't need the `bearerTokenFile` with a http scheme. As a side note `vmalert` `notifier` needs also a `namespaceSelector` definition.

For K3s, is best you use a [`config.yaml`](https://github.com/axivo/k3s-cluster/blob/main/roles/k3s/templates/config.j2) file where you define `etcd-expose-metrics: true`.

@AndrewChubatiuk please let me know if I missed any other `namespaceSelector` definitions, I went through Helm chart and could not see any specifics, other than the 2 cases mentioned.
