### ISSUE TITLE
bug: vmagent reports kubeControllerManager certificate is valid for localhost, not kubernetes

### ISSUE THREAD

**Issue by fmunteanu** [VictoriaMetrics/helm-charts#1765]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.28.3

**Describe the bug**
I'm running K3s (3 cp + 5 workers), which embeds `kube-controller-manager` into their binary. Port 10257 is properly exposed on all 3 control planes, example on a node:

```
# ss -tulpn | grep 10257
tcp   LISTEN 0      4096        192.168.4.2:10257      0.0.0.0:*    users:(("k3s-server",pid=5355,fd=215))
```

Looking at the unhealthy targets, I see the following error message:

> cannot perform request to "https://192.168.4.2:10257/metrics": Get "https://192.168.4.2:10257/metrics": tls: failed to verify certificate: x509: certificate is valid for localhost, not kubernetes

![image](https://github.com/user-attachments/assets/7927b0ca-fe5f-42ea-b19e-4d8f234960aa)

Setting the `serviceMonitor.serverName` to `localhost` should fix the issue, but it is not:

```
  serviceMonitor:
    https: true
    insecureSkipVerify: true
    serverName: localhost
```

K3s X509v3 Subject Alternative Names:

```
# hostname
apollo
# echo | openssl s_client -showcerts -connect localhost:6443 2>/dev/null | openssl x509 -text | grep DNS
                DNS:apollo, DNS:boreas, DNS:cerus, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, DNS:localhost, IP Address:10.43.0.1, IP Address:127.0.0.1, IP Address:192.168.4.10, IP Address:192.168.4.2, IP Address:192.168.4.3, IP Address:192.168.4.4, IP Address:0:0:0:0:0:0:0:1
```

I'm honestly out of ideas. it looks like `serverName` is completely ignored. Is this [template](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/servicemonitor.yaml) the source of truth for `kubeControllerManager.serviceMonitor` settings used in VMKS?

These are the current `kubeControllerManager` settings I'm using:
```yaml
kubeControllerManager:
  enabled: true
  endpoints:
  - 192.168.4.2
  - 192.168.4.3
  - 192.168.4.4
  service:
    enabled: true
    port: 10257
    selector:
      component: kube-controller-manager
    targetPort: 10257
  serviceMonitor:
    https: true
    insecureSkipVerify: true
    serverName: localhost
  vmScrape:
    spec:
      endpoints:
      - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        port: http-metrics
        scheme: https
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          serverName: kubernetes
      jobLabel: jobLabel
      namespaceSelector:
        matchNames:
        - kube-system
```

**Comment by AndrewChubatiuk** [comment]
there're no `kubeControllerManager.serviceMonitor` and `kubeEtcd.serviceMonitor` sections. Use `kubeControllerManager.vmScrape` and `kubeEtcd.vmScrape` instead. As it's described in a [doc](https://docs.victoriametrics.com/helm/victoriametrics-k8s-stack/) both `vmScrape` section accept parameters from [VMServiceScrapeSpec](https://docs.victoriametrics.com/operator/api/#vmservicescrapespec). You can set `insecureSkipVerify` at `kubeEtcd.vmScrape.endpoints[0].tlsConfig.insecureSkipVerify` and `kubeControllerManager.vmScrape.endpoints[0].tlsConfig.insecureSkipVerify`

**Comment by fmunteanu** [comment]
Thank you @AndrewChubatiuk, I understand now how everything works. I was originally confused because the `grafana` and `prometheus-community` repos being required by VMKS.

The following configuration fixes all issues, I added into my custom values.yaml:

```
kubeControllerManager:
  endpoints:
    - 192.168.4.2
    - 192.168.4.3
    - 192.168.4.4
  vmScrape:
    spec:
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
          scheme: https
          tlsConfig:
            caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecureSkipVerify: true
            serverName: localhost
```

The only disadvantage I see is being forced to add all settings. This could create problems in the long term, if VM devs add new keys/values. With the current format, if I define only `tlsConfig`, it will overwrite all related default settings:

```
kubeControllerManager:
  endpoints:
    - 192.168.4.2
    - 192.168.4.3
    - 192.168.4.4
  vmScrape:
    spec:
      endpoints:
        - tlsConfig:
            insecureSkipVerify: true
            serverName: localhost
```

I'm not sure if there is a better way to write the configuration into custom values.yaml, in order to avoid this issue.
