### ISSUE TITLE
bug: horizontalPodAutoscaler values are ignored in vmcluster

### ISSUE THREAD

**Issue by fmunteanu** [VictoriaMetrics/helm-charts#1769]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.28.4

**Describe the bug**
The `horizontalPodAutoscaler` values are ignored in vmcluster, see below the related custom values for `vmstorage`:

```
vmcluster:
  enabled: true
  spec:
    replicationFactor: 2
    vmstorage:
      horizontalPodAutoscaler:
        enabled: true
        maxReplicas: 4
        metrics:
        - resource:
            name: memory
            target:
              averageUtilization: 90
              type: Utilization
          type: Resource
        minReplicas: 2
      resources:
        limits:
          cpu: null
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 1Gi
      storage:
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: longhorn
vmsingle:
  enabled: false
```

I lowered in purpose the resources memory limit, to test the autoscaling. Also, how does `replicationFactor` relates to autoscaling, should I set it to 1? Thank you for letting me know what am I missing.
