### ISSUE TITLE
bug: ingress in vmauth not working when defined public and private

### ISSUE THREAD

**Issue by szibis** [VictoriaMetrics/helm-charts#1777]
**Chart name and version**
chart: victoria-metrics-auth
version: v0.7.6

**Describe the bug**
ingress:
  enabled: true
ingressInternal:
  enabled: true

Cannot be used for public ingress and internal ingress at same time. After the recent cleanup, probably https://github.com/VictoriaMetrics/helm-charts/pull/1668

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ $publicdomain }}
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: {{ $publicCertArn }}
    alb.ingress.kubernetes.io/load-balancer-name: metrics-public
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":8427}]'
    alb.ingress.kubernetes.io/success-codes: 200-302
  extraLabels: {}
  hosts:
    - name: {{ $publicdomain }}
      path: /
      port: 8427
  ingressClassName: alb
  # -- pathType is only for k8s >= 1.1=
  pathType: Prefix

ingressInternal:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ $internaldomain }}
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: {{ $internalCertArn }}
    alb.ingress.kubernetes.io/load-balancer-name: metrics-internal
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":8427}]'
    alb.ingress.kubernetes.io/success-codes: 200-302
  extraLabels: {}
  hosts:
    - name: {{ $internaldomain }}
      path: /
      port: 8427
  ingressClassName: alb
  # -- pathType is only for k8s >= 1.1=
  pathType: Prefix
```
