### ISSUE TITLE
bug: VictoriaLogs Helm, Ingress, and "<$host.path>: can't evaluate field path in type interface {}" error

### ISSUE THREAD

**Issue by arseny-zinchenko** [VictoriaMetrics/helm-charts#1779]
**Chart name and version**
```
- name: victoria-logs-single
  version: ~0.8.0
  repository: https://victoriametrics.github.io/helm-charts
```

**Describe the bug**
When configuring an Ingress for the VMLogs with the following values:
```
    ingress:
      enabled: true
      annotations: 
        alb.ingress.kubernetes.io/group.name: ops-1-30-internal-alb
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:***:certificate/76ed3092-0da5-45a0-aa54-27afad80d8b8
        #alb.ingress.kubernetes.io/success-codes: '401'
      hosts: 
        - vmlogs.monitoring.1-30.ops.example.co
```

Helm returns an error:
```
template: atlas-victoriametrics/charts/victoria-logs-single/templates/server-ingress.yaml:27:37: executing "atlas-victoriametrics/charts/victoria-logs-single/templates/server-ingress.yaml" at <$host.path>: can't evaluate field path in type interface {}
```

The workaround is to add `name` and `path` keys:
```
        - name: vmlogs.monitoring.1-30.ops.example.co
          path: /
```
Because [server-ingress.yaml](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-logs-single/templates/server-ingress.yaml#L28) is defined as:
```
    {{- range $host := $ingress.hosts }}
    {{- $paths := ternary (list $host.path) $host.path (kindIs "string" $host.path) }}
    - host: {{ tpl $host.name $ }}
      http:
        paths:
          {{- range $path := $paths }}
          - path: {{ $path }}
```

But in the [Parameters](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-logs-single#parameters) it's not mentioned, also VMSigle Ingress is configured without the `path` value.
