### ISSUE TITLE
bug:Issues when upgrading victoria-metrics-k8s-stack from 0.24.5 to 0.25.17

### ISSUE THREAD

**Issue by knuurr** [VictoriaMetrics/helm-charts#1786]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.24.5 and 0.25.17

**Describe the bug**
I'm trying to upgrade workloads to newest version. I inherited environment running victoria-metrics-k8s-stack v0.24.5 and wanted to bring it first to v0.25.x before going further. Our deployment is managed with Argo CD through ApplicationSet.

Steps performed:

1. While still on v0.24.5, I performed CRD update with command:
```shell
helm show crds vm/victoria-metrics-k8s-stack --version 0.25.17 | kubectl apply -f - --server-side --force-conflicts
```
2. Update Helm chart to version 0.25.17 in ApplicationSet manifest

When on version 0.25.17 and performing sync in Argo CD, operation fails with following message.

`Sync operation to 0.25.17 failed: one or more objects failed to apply, reason: Service "victoria-metrics-victoria-metrics-operator" is invalid: spec.ports[2].name: Duplicate value: "webhook",Deployment.apps "victoria-metrics-victoria-metrics-operator" is invalid: spec.template.spec.containers[0].image: Required value (retried 2 times).`

Not really sure what is the issue. I read changelogs between my version and destination version, didn't notice any bigger steps to take other than updating CRDs.

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
fullnameOverride: vm
nameOverride: vm

vmsingle:
  enabled: false

prometheus-node-exporter:
  enabled: true
  rbac:
    pspEnabled: false

victoria-metrics-operator:
  rbac:
    pspEnabled: false
  # https://github.com/VictoriaMetrics/helm-charts/issues/1508#issuecomment-2355675530
  admissionWebhooks:
    enabled: false

vmcluster:
  enabled: true
  spec:
    replicationFactor: 2
    retentionPeriod: "3d"
    vmstorage:
      replicaCount: 2
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 100Gi
      resources:
        limits:
          cpu: 200m
          memory: 1500Mi
        requests:
          cpu: 100m
          memory: 500Mi                
    vminsert:
      replicaCount: 2
      resources:
        limits:
          cpu: 600m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
    vmselect:
      replicaCount: 2
      resources:
        limits:
          cpu: 600m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi

vmagent:
  ingress:
    enabled: true
    annotations:
      # ...
    hosts: [# ...]
  extraScrapeConfigs:
      # ....

grafana:
  enabled: true
  extraEnvVars:
    - name: AWS_SDK_LOAD_CONFIG
      value: "true"
    - name: GF_AUTH_SIGV4_AUTH_ENABLED
      value: "true"
  assertNoLeakedSecrets: false
  sidecar:
    dashboards:
      provider:
        foldersFromFilesStructure: true
      folderAnnotation: "grafana_folder"
    datasources:
      enabled: true
    notifiers:
      enabled: true
    alerts:
      enabled: true
  rbac:
    pspEnabled: false
  ingress:
    enabled: true
    annotations:
      # ....
    hosts: [ ... ]
  persistence:
    type: pvc
    enabled: true
    size: 30Gi
  grafana.ini:
    log:
      mode: 'console'
      level: 'info'
    database:
      wal: true
    auth:
      sigv4_auth_enabled: 'true'
    auth.okta:
      # ...
    server:
      # ...
  additionalDataSources:
    - name: CloudWatch
      type: cloudwatch
      jsonData:
        authType: default
        defaultRegion: <region>
```
