### ISSUE TITLE
bug: Victoria logs single and vectoria metrics single charts are interffering with each other

### ISSUE THREAD

**Issue by davigottt** [VictoriaMetrics/helm-charts#1788]
**Chart name and version**
chart: victoria-metrics-single
version: 0.12.6
chart: victoria-metrics-agent
version: 0.14.7
chart: victoria-logs-single
version: 0.8.1

**Describe the bug**
The charts are interfering witch each other.
![image](https://github.com/user-attachments/assets/8457ec1b-5587-4381-be14-397e70e0f8d9)
The victoria metrics  kubernetes service is using wrong selectors. Had it happen the other way around too.

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
victoria-logs-single:
  server:
    name: CENSOREDNAME-victoria-logs
    persistentVolume:
      enabled: true
  vector:
    enabled: true
victoria-metrics-single:
  server:
    enabled: true
    name: CENSOREDNAME-victoria-logs
    persistentVolume:
      enabled: true
      accessModes:
        - ReadWriteOnce
      storageClassName: "efs-sc"
      mountPath: /storage
      size: 5Gi # ignored for AWS EFS
```
