### ISSUE TITLE
bug: It is not possible to disable the generation of unauthorizedAccessConfig in VMauth

### ISSUE THREAD

**Issue by tropnikovvl** [VictoriaMetrics/helm-charts#1793]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: 0.28.4

**Describe the bug**
Currently, it is not possible to disable the creation of unauthorizedAccessConfig in VMauth or fully customize it, such as restricting public access to certain components.

I would like to create VMuser and independently determine which user has access to which components, but this functionality is not working at the moment (this is because unauthorizedAccessConfig exists.).

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
extraObjects:
- kind: VMUser
  apiVersion: operator.victoriametrics.com/v1beta1
  metadata:
    name: vm-user
    namespace: vm
  spec:
    username: vm-user
    password: vm-password
    targetRefs:
      - crd:
          kind: VMSingle
          name: vms-victoria-metrics-k8s-stack
          namespace: vm
        paths: ["/.*"]
```
