### ISSUE TITLE
bug: Alertmanager config not used by VMAlertmanager anymore

### ISSUE THREAD

**Issue by BapRx** [VictoriaMetrics/helm-charts#1805]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: 0.29.0

**Describe the bug**

The Alertmanager configuration generated is not referenced by the VMAlertmanager object since [this commit](https://github.com/VictoriaMetrics/helm-charts/commit/b96a73cdc18fa25d43b8a8910e1105e6bd3222d3#diff-95592edf818384aca3ab100b3164575a5eb6e4e67c65d662ef0b6aed2bf6bcdfL374-R236).

![image](https://github.com/user-attachments/assets/6b215533-ddd1-426f-8a2b-907a2dd7a8c3)

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
alertmanager:
  config:
    route:
      group_interval: 2m
      group_wait: 1m
      receiver: blackhole

      routes:
        - receiver: blackhole
          matchers:
            - alertname =~ "KubeProxyDown|KubeSchedulerDown|KubeControllerManagerDown"
        - receiver: healthcheck
          matchers:
            - alertname = Watchdog
          repeat_interval: 10s
```

With these values, a secret named `victoria-metrics-alertmanager` is created which used to be referenced in the `.spec.configSecret` field of VMAlertmanager but that's not the case since the release v0.29.0.

Since this version, the `.spec.configSecret` now has the value `vmalertmanager-victoria-metrics`.
