### ISSUE TITLE
bug: Alertmanager v0.27.0 msteams_configs: field webhook_url_secret not found in type config.plain

### ISSUE THREAD

**Issue by Prates23** [VictoriaMetrics/helm-charts#1812]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.29.1

**Describe the bug**

When I try to use the msteams configuration with Alertmanager v0.27.0 based on this documentation https://docs.victoriametrics.com/operator/api/?highlight=msteams#msteamsconfig I get the following error on the vmalertmanager-victoria-metrics-k8s-stack pod (alertmanager container) 

```sh
yaml: unmarshal errors:\n line 37: field webhook_url_secret not found in type config.plain
```
**Custom values**
Please provide only custom values (excluding default ones):
```yaml
  config:
    global:
      resolve_timeout: 5m
    templates:
      - "/etc/vm/configs/**/*.tmpl"
    route:
      group_by: ['...']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: "msteams"
      routes:
        - matchers:
            - alertname=~"Watchdog|InfoInhibitor|KubePodCrashLooping|KubeAggregatedAPI.*|KubernetesDiskPressure|NodeDiskIOSaturation|TooHighMemoryUsage|NodeSystemSaturation|TooManyScrapeErrors|NodeCPUHighUsage|KubernetesMemoryPressure"
          receiver: 'msteams'
    receivers:
      - name: 'null'
      - name: 'msteams'
        msteams_configs:
          - webhook_url_secret:
                name: am-secret
                key: url
            send_resolved: true
            title: |-
              [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
              {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
                {{" "}}(
                {{- with .CommonLabels.Remove .GroupLabels.Names }}
                  {{- range $index, $label := .SortedPairs -}}
                    {{ if $index }}, {{ end }}
                    {{- $label.Name }}="{{ $label.Value -}}"
                  {{- end }}
                {{- end -}}
                )
              {{- end }}
            text: >-
              {{ range .Alerts -}}
              *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

              *Description:* {{ .Annotations.description }}

              *Details:*
                {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
              {{ end }}
      
```
I appreciate if someone can help. Thanks!

**Comment by AndrewChubatiuk** [comment]
hey @Prates23 
`alertmanager.config` uses Secret, not VMAlertmanagerConfig. so all possible values for msteams_config are available here
https://prometheus.io/docs/alerting/latest/configuration/#msteams_config

**Comment by Prates23** [comment]
@AndrewChubatiuk  thanks for the quick response. That was my original approach. It also didn't work. It works having only the **webhook_url** but if I switch to **webhook_url_file** I get the same error, but of course it complains for webhook_url_file not found in type config.plain. I even exec inside the container and I checked that the secret file was there. This was the configuration I used


```yaml
alertmanager:
  enabled: true
  spec:
    port: "9093"
    selectAllByDefault: true
    image:
      tag: v0.27.0
    externalURL: ""
    routePrefix: /
    volumes:
      - name: secret-data
        secret:
          secretName: alertmanager
    volumeMounts:
      - name: secret-data
        readOnly: true
        mountPath: "/etc/alertmanager/secrets"

  config:
    global:
      resolve_timeout: 5m
    templates:
      - "/etc/vm/configs/**/*.tmpl"
    route:
      group_by: ['...']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: "msteams"
      routes:
        - matchers:
            - alertname=~"Watchdog|InfoInhibitor|KubePodCrashLooping|KubeAggregatedAPI.*|KubernetesDiskPressure|NodeDiskIOSaturation|TooHighMemoryUsage|NodeSystemSaturation|TooManyScrapeErrors|NodeCPUHighUsage|KubernetesMemoryPressure"
          receiver: 'msteams'
    receivers:
      - name: 'null'
      - name: 'msteams'
        msteams_configs:
          - webhook_url_file: /etc/alertmanager/secrets/teams_url  
            send_resolved: true
            title: |-
              [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
              {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
                {{" "}}(
                {{- with .CommonLabels.Remove .GroupLabels.Names }}
                  {{- range $index, $label := .SortedPairs -}}
                    {{ if $index }}, {{ end }}
                    {{- $label.Name }}="{{ $label.Value -}}"
                  {{- end }}
                {{- end -}}
                )
              {{- end }}
            text: >-
              {{ range .Alerts -}}
              *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

              *Description:* {{ .Annotations.description }}

              *Details:*
                {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
              {{ end }}
```
