### ISSUE TITLE
question: Should multiple vmselect pods write to same storage volume?

### ISSUE THREAD

**Issue by fmunteanu** [VictoriaMetrics/helm-charts#1816]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.28.4

**Describe the bug**
I'm using `longhorn` storage class for vmselect and vmstorage. With HPA enabled for vmselect, I see new volumes created on scale-up, then on scale-down, volumes are detached. Using logic, multiple vmselect pods should write to a single volume, not multiple. Is this considered a good practice for VM?

I'm going to create a RWX longhorn class and set the access mode to ReadWriteMany, which should fix the issue.

I'm also curious why VMKS chart sets the minimum number of vmselect pods to 2. Thank you for letting me know.

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
alertmanager:
  config:
    inhibit_rules:
    - equal:
      - alertname
      - cluster
      - namespace
      source_matchers:
      - severity="critical"
      target_matchers:
      - severity=~"info|warning"
    - equal:
      - alertname
      - cluster
      - namespace
      source_matchers:
      - severity="warning"
      target_matchers:
      - severity="info"
    - equal:
      - cluster
      - namespace
      source_matchers:
      - alertname="InfoInhibitor"
      target_matchers:
      - severity="info"
    route:
      group_by:
      - alertgroup
      - job
      group_interval: 5m
      group_wait: 30s
      repeat_interval: 12h
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-cluster-issuer-staging
    enabled: true
    hosts:
    - alertmanager.noty.cc
    ingressClassName: cilium
    tls:
    - hosts:
      - alertmanager.noty.cc
      secretName: cloudflare-alertmanager-vmks-victoria-metrics-k8s-stack
  spec:
    configReloaderResources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
    logLevel: WARN
    podDisruptionBudget:
      minAvailable: 1
    replicaCount: 2
    resources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
defaultDashboards:
  dashboards:
    victoriametrics-operator:
      enabled: true
    victoriametrics-vmalert:
      enabled: true
  defaultTimezone: utc
global:
  cluster:
    dnsDomain: cluster.local.
  clusterLabel: default
grafana:
  admin:
    existingSecret: vmks-grafana-user-account
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-cluster-issuer-staging
    enabled: true
    hosts:
    - grafana.noty.cc
    ingressClassName: cilium
    tls:
    - hosts:
      - grafana.noty.cc
      secretName: cloudflare-vmks-grafana
  logLevel: WARN
  podDisruptionBudget:
    minAvailable: 1
  replicas: 1
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
  sidecar:
    resources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
kube-state-metrics:
  podDisruptionBudget:
    minAvailable: 1
  replicas: 1
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
kubeControllerManager:
  endpoints:
  - 192.168.4.2
  - 192.168.4.3
  - 192.168.4.4
  vmScrape:
    spec:
      endpoints:
      - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        port: http-metrics
        scheme: https
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecureSkipVerify: true
          serverName: localhost
kubeEtcd:
  endpoints:
  - 192.168.4.2
  - 192.168.4.3
  - 192.168.4.4
  service:
    port: 2381
    targetPort: 2381
  vmScrape:
    spec:
      endpoints:
      - port: http-metrics
        scheme: http
kubeScheduler:
  endpoints:
  - 192.168.4.2
  - 192.168.4.3
  - 192.168.4.4
  vmScrape:
    spec:
      endpoints:
      - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        port: http-metrics
        scheme: https
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecureSkipVerify: true
          serverName: localhost
prometheus-node-exporter:
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
prometheus-operator-crds:
  enabled: true
victoria-metrics-operator:
  operator:
    admissionWebhooks:
      certManager:
        enabled: true
        issuer:
          group: cert-manager.io
          kind: ClusterIssuer
          name: certmanager-cluster-issuer
    enable_converter_ownership: true
    logLevel: error
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
  replicaCount: 1
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
vmagent:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-cluster-issuer-staging
    enabled: true
    hosts:
    - agent.noty.cc
    ingressClassName: cilium
    tls:
    - hosts:
      - agent.noty.cc
      secretName: cloudflare-vmagent-vmks-victoria-metrics-k8s-stack
  spec:
    configReloaderResources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
    logLevel: WARN
    podDisruptionBudget:
      minAvailable: 1
    replicaCount: 1
    resources:
      limits:
        cpu: null
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 512Mi
vmalert:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-cluster-issuer-staging
    enabled: true
    hosts:
    - alert.noty.cc
    ingressClassName: cilium
    tls:
    - hosts:
      - alert.noty.cc
      secretName: cloudflare-vmalert-vmks-victoria-metrics-k8s-stack
  spec:
    configReloaderResources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
    extraArgs:
      external.url: https://alert.noty.cc
    logLevel: WARN
    podDisruptionBudget:
      minAvailable: 1
    replicaCount: 1
    resources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
vmcluster:
  enabled: true
  ingress:
    insert:
      annotations:
        cert-manager.io/cluster-issuer: cloudflare-cluster-issuer-staging
      enabled: false
      hosts:
      - insert.noty.cc
      ingressClassName: cilium
      tls:
      - hosts:
        - insert.noty.cc
        secretName: cloudflare-vminsert-vmks-victoria-metrics-k8s-stack
    select:
      annotations:
        cert-manager.io/cluster-issuer: cloudflare-cluster-issuer-staging
      enabled: true
      hosts:
      - metrics.noty.cc
      ingressClassName: cilium
      tls:
      - hosts:
        - metrics.noty.cc
        secretName: cloudflare-vmselect-vmks-victoria-metrics-k8s-stack
    storage:
      annotations:
        cert-manager.io/cluster-issuer: cloudflare-cluster-issuer-staging
      enabled: false
      hosts:
      - storage.noty.cc
      ingressClassName: cilium
      tls:
      - hosts:
        - storage.noty.cc
        secretName: cloudflare-vmstorage-vmks-victoria-metrics-k8s-stack
  spec:
    replicationFactor: 2
    retentionPeriod: 72h
    vminsert:
      hpa:
        maxReplicas: 3
        metrics:
        - resource:
            name: memory
            target:
              averageUtilization: 80
              type: Utilization
          type: Resource
        minReplicas: 1
      logLevel: WARN
      podDisruptionBudget:
        minAvailable: 1
      resources:
        limits:
          cpu: null
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 256Mi
    vmselect:
      hpa:
        maxReplicas: 3
        metrics:
        - resource:
            name: memory
            target:
              averageUtilization: 80
              type: Utilization
          type: Resource
        minReplicas: 1
      logLevel: WARN
      podDisruptionBudget:
        minAvailable: 1
      resources:
        limits:
          cpu: null
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 256Mi
      storage:
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: longhorn
    vmstorage:
      logLevel: WARN
      podDisruptionBudget:
        minAvailable: 1
      replicaCount: 1
      resources:
        limits:
          cpu: null
          memory: 2560Mi
        requests:
          cpu: 10m
          memory: 2560Mi
      storage:
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: longhorn
vmsingle:
  enabled: false
```
