### ISSUE TITLE
bug: victoria-metrics-operator logLevel not respected

### ISSUE THREAD

**Issue by fmunteanu** [VictoriaMetrics/helm-charts#1817]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.28.4

**Describe the bug**
For some reason, the `operator.logLevel: error` is not respected, I see `info` log entries:

![image](https://github.com/user-attachments/assets/c27f3dbc-0a25-4231-a1d9-040378801669)

![image](https://github.com/user-attachments/assets/7ad0a0d7-ce67-4321-81f8-1575b6338e8e)

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
victoria-metrics-operator:
  operator:
    admissionWebhooks:
      certManager:
        enabled: true
        issuer:
          group: cert-manager.io
          kind: ClusterIssuer
          name: certmanager-cluster-issuer
    enable_converter_ownership: true
    logLevel: error
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
  replicaCount: 1
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
```

**Comment by AndrewChubatiuk** [comment]
hey @fmunteanu 
both podDisruptionBudged and logLevel are expected under `victoria-metrics-operator` key. See [documentation](https://docs.victoriametrics.com/helm/victoriametrics-operator/index.html)

**Comment by fmunteanu** [comment]
I have them defined, is that what you are referring to?

```
    logLevel: error
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
```
