### ISSUE TITLE
bug: VMAuth TLS value has to be both string and bool

### ISSUE THREAD

**Issue by pokorny-martin** [VictoriaMetrics/helm-charts#1824]
**Chart name and version**
chart: victoria-metrics-cluster
version: 0.14.12

**Describe the bug**
When running vmauth with tls, the chart expect the `tls` value to be type of string [charts/victoria-metrics-common/templates/_pod.tpl#L78](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-common/templates/_pod.tpl#L78) and type of bool [victoria-metrics-common/templates/_service.tpl#L49](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-common/templates/_service.tpl#L49) at the same time

For tls of `"true"` you will receive following error:  
> Helm upgrade failed for release victoria/victoria with chart victoria-metrics-cluster@0.14.12: template: victoria-metrics-cluster/templates/vmauth-deployment.yaml:66:30: executing "victoria-metrics-cluster/templates/vmauth-deployment.yaml" at <include "vm.probe" (dict "app" $app "type" "readiness")>: error calling include: template: victoria-metrics-cluster/charts/victoria-metrics-common/templates/_pod.tpl:50:79: executing "vm.probe" at <include "vm.probe.http.scheme" .>: error calling include: template: victoria-metrics-cluster/charts/victoria-metrics-common/templates/_pod.tpl:78:59: executing "vm.probe.http.scheme" at <false>: wrong type for value; expected bool; got string  

For tis of `true` or `True` you will receive following error:  
> Helm upgrade failed for release victoria/victoria with chart victoria-metrics-cluster@0.14.12: template: victoria-metrics-cluster/templates/NOTES.txt:42:16: executing "victoria-metrics-cluster/templates/NOTES.txt" at <include "vm.url" $ctx>: error calling include: template: victoria-metrics-cluster/charts/victoria-metrics-common/templates/_service.tpl:57:16: executing "vm.url" at <include "vm.host" .>: error calling include: template: victoria-metrics-cluster/charts/victoria-metrics-common/templates/_service.tpl:49:21: executing "vm.host" at <eq ($spec.extraArgs).tls "true">: error calling eq: incompatible types for comparison  

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
vmauth:
  ...
  extraArgs:
    tls: "true" # or true depending on the error you want to get
    tlsKeyFile: /etc/ssl-certificates/tls.key
    tlsCertFile: /etc/ssl-certificates/tls.crt
    httpListenAddr: 0.0.0.0:443
  extraVolumes:
    - name: victoria-tls
      secret:
        secretName: vmauth-ingress-tls
  extraVolumeMounts:
    - mountPath: "/etc/ssl-certificates"
      name: victoria-tls
      readOnly: true
   ...
```
