### ISSUE TITLE
cannot create image without .repository

### ISSUE THREAD

**Issue by tschlaepfer** [VictoriaMetrics/helm-charts#1825]
**Chart name and version**
chart: victoria-metrics-cluster
version: v0.14.12

**Describe the bug**
Deploying the victoria-metrics-cluster chart generates the following error:

execution error at (charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml:47:20): cannot create image without `.repository` 

Providing the repository in the values.yaml file also does not solve the issue. 

**Custom values**
The only special configuration in my chart deployment is that I have the deployment of vmstroage disabled in the values.yaml file:
```
victoria-metrics-cluster:
  vmselect:
    fullnameOverride: vmselect
    image:
      repository: victoriametrics/vmselect
  vmstorage:
    enabled: false
```

Any advice on how to avoid this error?
