### ISSUE TITLE
[VictoriaLogs] bug: when setting resources.requests, the resources.limits is not emptied

### ISSUE THREAD

**Issue by arseny-zinchenko** [VictoriaMetrics/helm-charts#1834]
**Chart name and version**
```
- name: victoria-logs-single
  version: ~0.8.0
  repository: https://victoriametrics.github.io/helm-charts
```

**Describe the bug**

When i set `server.resources.requests` only, i.e. without the `server.resources.limits`, the `limits` is set to the default values - `cpu: 200m`, and `memory:  100Mi`.

This leads to an error:
>  Pod "atlas-victoriametrics-victoria-logs-single-server-0" is invalid: [spec.containers[0].resources.requests: Invalid value: "1": must be less than or equal to cpu limit of 200m, spec.containers[0].resources.requests: Invalid value: "512Mi": must be less than or equal to memory limit of 100Mi]

My `values` used in that case:
```
    resources:
      requests:
        cpu: 1000m
        memory: 512Mi
```

Still, if I add both `requests` AND `limits`, everything is fine:

```
    resources:
      limits:
        cpu: 2000m
        memory: 1024Mi
      requests:
        cpu: 1000m
        memory: 512Mi
```

But I'm expecting that if I'm not setting `limits`, it must be empty, i.e. the STS has no limits for the VMLogs Pod.
