### ISSUE TITLE
bug: spec.clusterIPs[0]: Invalid value: "None"

### ISSUE THREAD

**Issue by fmunteanu** [VictoriaMetrics/helm-charts#1838]
**Chart name and version**
chart: victoria-logs-single
version: v0.8.8

**Describe the bug**
I think there is a template bug, while using `server.service.type: LoadBalancer`. Applied changes:

```
$ diff -Naur a b
--- a	2024-12-02 17:24:45.570867807 -0500
+++ b	2024-12-02 17:27:51.411819748 -0500
@@ -13,7 +13,6 @@
       path:
       - /
       port: http
-    ingressClassName: cilium
     tls:
     - hosts:
       - logs.noty.cc
@@ -32,6 +31,10 @@
     requests:
       cpu: 10m
       memory: 512Mi
+  service:
+    annotations:
+      io.cilium/lb-ipam-ips: 192.168.4.20
+    type: LoadBalancer
   retentionPeriod: 7d
   serviceMonitor:
     enabled: true
```

Error output:

> UPGRADE FAILED: cannot patch "vls-victoria-logs-single-server" with kind Service: Service "vls-victoria-logs-single-server" is invalid: spec.clusterIPs[0]: Invalid value: "None": may not be set to 'None' for LoadBalancer services

Creating a test service works as intended:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    io.cilium/lb-ipam-ips: 192.168.4.20
  name: service-name-test
  namespace: kube-system
spec:
  type: LoadBalancer
```

A basic functional deployment with `type: ClusterIP`, see custom values:

```yaml
dashboards:
  enabled: true
podDisruptionBudget:
  enabled: true
  minAvailable: 1
server:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-cluster-issuer-staging
    enabled: true
    hosts:
    - name: logs.noty.cc
      path:
      - /
      port: http
    ingressClassName: cilium
    tls:
    - hosts:
      - logs.noty.cc
      secretName: cloudflare-vls-victoria-logs-single-server
  persistentVolume:
    accessModes:
    - ReadWriteOnce
    enabled: true
    size: 5Gi
    storageClassName: longhorn
  replicaCount: 1
  resources:
    limits:
      cpu: null
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 512Mi
  retentionPeriod: 7d
  serviceMonitor:
    enabled: true
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
```

Broken deployment:

```yaml
dashboards:
  enabled: true
podDisruptionBudget:
  enabled: true
  minAvailable: 1
server:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-cluster-issuer-staging
    enabled: true
    hosts:
    - name: logs.noty.cc
      path:
      - /
      port: http
    tls:
    - hosts:
      - logs.noty.cc
      secretName: cloudflare-vls-victoria-logs-single-server
  persistentVolume:
    accessModes:
    - ReadWriteOnce
    enabled: true
    size: 5Gi
    storageClassName: longhorn
  replicaCount: 1
  resources:
    limits:
      cpu: null
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 512Mi
  service:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.4.20
    type: LoadBalancer
  retentionPeriod: 7d
  serviceMonitor:
    enabled: true
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
```

**Comment by fmunteanu** [comment]
@AndrewChubatiuk I get the same error message with 0.8.9 release:

```
fatal: [apollo]: FAILED! => changed=false
  attempts: 3
  command: /usr/sbin/helm --version=v0.8.9 upgrade -i --reset-values --wait --timeout 5m0s --create-namespace -f=/tmp/tmp9xb3345j.yml vls 'VictoriaMetrics/victoria-logs-single'
  msg: |-
    Failure when executing Helm command. Exited 1.
    stdout:
    stderr: Error: UPGRADE FAILED: cannot patch "vls-victoria-logs-single-server" with kind Service: Service "vls-victoria-logs-single-server" is invalid: spec.clusterIPs[0]: Invalid value: "None": may not be set to 'None' for LoadBalancer services
  stderr: |-
    Error: UPGRADE FAILED: cannot patch "vls-victoria-logs-single-server" with kind Service: Service "vls-victoria-logs-single-server" is invalid: spec.clusterIPs[0]: Invalid value: "None": may not be set to 'None' for LoadBalancer services
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

**Comment by AndrewChubatiuk** [comment]
not able to reproduce your issue with both helm template rendering and helm install execution with your values, there's no `spec.clusterIP` in rendered manifests

**Comment by fmunteanu** [comment]
Without the highlighted changes mentioned into OP, everything works as intended:

```
changed: [apollo] => changed=true
  attempts: 1
  command: /usr/sbin/helm --version=v0.8.9 upgrade -i --reset-values --wait --timeout 5m0s --create-namespace -f=/tmp/tmps99jrjjy.yml vls 'VictoriaMetrics/victoria-logs-single'
  status:
    app_version: v1.0.0
    chart: victoria-logs-single-0.8.9
    name: vls
    namespace: kube-system
    revision: '7'
    status: deployed
    updated: 2024-12-03 13:40:40.479712046 -0500 EST
    values:
      podDisruptionBudget:
        enabled: true
        maxUnavailable: 1
      server:
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: cloudflare-cluster-issuer-staging
          enabled: true
          hosts:
          - name: logs.noty.cc
            path:
            - /
            port: http
          ingressClassName: cilium
          tls:
          - hosts:
            - logs.noty.cc
            secretName: cloudflare-vls-victoria-logs-single-server
        persistentVolume:
          accessModes:
          - ReadWriteOnce
          enabled: true
          size: 5Gi
          storageClassName: longhorn
        replicaCount: 1
        retentionPeriod: 7d
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      vector:
        enabled: true
        logLevel: warn
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    Release "vls" has been upgraded. Happy Helming!
    NAME: vls
    LAST DEPLOYED: Tue Dec  3 13:40:40 2024
    NAMESPACE: kube-system
    STATUS: deployed
    REVISION: 7
    TEST SUITE: None
    NOTES:
    The VictoriaLogs write api can be accessed via port 9428 on the following DNS name from within your cluster:
        vls-victoria-logs-single-server-0.vls-victoria-logs-single-server.kube-system.svc.cluster.local.

    Logs Ingestion:
      Get the Victoria Logs service URL by running these commands in the same shell:
        export POD_NAME=$(kubectl get pods --namespace kube-system -l "app=server" -o jsonpath="{.items[0].metadata.name}")
        kubectl --namespace kube-system port-forward $POD_NAME 9428

      Write url inside the kubernetes cluster:
        http://vls-victoria-logs-single-server.kube-system.svc.cluster.local.:9428

    Read Data:
      The following url can be used to query data:
        http://vls-victoria-logs-single-server.kube-system.svc.cluster.local.:9428
  stdout_lines: <omitted>
```
