### ISSUE TITLE
bug: vmselect and vminsert pods not created with custom values in victoria-metrics-k8s-stack chart (version 0.30.0)

### ISSUE THREAD

**Issue by Hela98** [VictoriaMetrics/helm-charts#1841]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: 0.30.0

The pods for vmselect and vminsert are not being created when using the custom values provided below. Despite specifying vmselect and vminsert settings in the values.yaml, the pods for these components are not appearing in the Kubernetes cluster after the Helm chart is installed.

**values**
```yaml
vmcluster:
  enabled: true
  spec:
    retentionPeriod: "1y"
    replicationFactor: 2
    vmstorage:
      replicaCount: 5
      storageDataPath: "/vm-data"
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 6Gi
    vmselect:
      replicaCount: 4
      cacheMountPath: "/select-cache"
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 2Gi
    vminsert:
      port: "8480"
      replicaCount: 2
      extraArgs: 
        maxLabelsPerTimeseries: "50"
```
![vms](https://github.com/user-attachments/assets/cbda72e4-8a20-4310-b168-cd5cce7009b1)

**Comment by AndrewChubatiuk** [comment]
please try version 0.30.1. looks like you have both vmsingle and vmcluster enabled, which is not allowed. in 0.30.1 added an error, which will be triggered when both single and cluster are enabled

**Comment by Hela98** [comment]
Hello, I tried using version 0.30.1 of the VictoriaMetrics Helm chart, with the following configuration:

vmsingle is not enabled.
vmcluster is enabled.
However, I am still encountering the same issue.

**Comment by AndrewChubatiuk** [comment]
in a screenshot I see a storage is in a crash loop. please share its logs

**Comment by Hela98** [comment]
Back-off restarting failed container vmstorage in pod vmstorage-victoria-metrics-k8s-stack-0_victoria-stack(64c9417b-fb2e-4b45-9dc6-2f981bc2f41a)
'`2024-12-03T15:34:59.562Z	panic	VictoriaMetrics/lib/mergeset/part_header.go:93	FATAL: cannot parse "/vm-data/indexdb/17E342D0755AEB82/180B41D14B577D98/metadata.json": invalid character '\x00' after top-level value
panic: FATAL: cannot parse "/vm-data/indexdb/17E342D0755AEB82/180B41D14B577D98/metadata.json": invalid character '\x00' after top-level value
goroutine 1 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0x99f12f, 0x5}, {0xc00009d3b0, 0x86}, 0x4)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:315 +0xa74
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0x99f12f, 0x5}, {0x9a992e?, 0xc002d60740?}, {0xc000036c18?, 0xc000036bc8?, 0x473eff?})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:155 +0x1a5
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:147
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:143
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*partHeader).MustReadMetadata(0xc000036d58, {0xc001fffe80, 0x32})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/part_header.go:93 +0x25b
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.mustOpenFilePart({0xc001fffe80, 0x32})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/part.go:72 +0x65
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.mustOpenParts({0xc00002a6c0, 0x21})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:1523 +0x6fc
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.MustOpenTable({0xc00002a6c0?, 0x10?}, 0xa4d990, 0xa4d998, 0xc0001323a8)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:365 +0x54
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.mustOpenIndexDB({0xc00002a6c0, 0x21}, 0xc0001321e0, 0xc0001323a8)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/index_db.go:158 +0x186
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*Storage).mustOpenIndexDBTables(0xc0001321e0, {0xc003300040, 0x10})
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/storage.go:2844 +0x936
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.MustOpenStorage({0x7ffe76309f97?, 0x99edf7?}, 0x7009d32da30000, 0x0, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/storage.go:258 +0xc17
main.main()
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/main.go:104 +0x357`

**Comment by AndrewChubatiuk** [comment]
which version were you using before?

**Comment by Hela98** [comment]
I'm using this to deploy my app on argocd
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-stack-prod-technical
  namespace: argo-cd
spec:
  project: production-technical
  source:
    repoURL: 'git@bitbucket.org:gieps/kubernetes_apps.git'
    path: app/victoria-metrics-stack/overlays/prod-technical
    targetRevision: HEAD

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: victoria-stack
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: victoria-metrics-k8s-stack-victoria-metrics-operator-validation
      namespace: kube-system
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: victoria-metrics-k8s-stack-victoria-metrics-operator-admission
      jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'

 
```
