### ISSUE TITLE
question: vmagent high CPU usage

### ISSUE THREAD

**Issue by fmunteanu** [VictoriaMetrics/helm-charts#1855]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.30.3

**Describe the bug**
I'm trying to understand why `vmagent` is having a constant high CPU usage, on average 2CPU. This happens with both `vmcluster` and `vmsingle`:

![image](https://github.com/user-attachments/assets/78e7e30e-3371-4ba9-8ca4-0b2c4c0cb487)

Are there any settings I missed into helm chart?

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
alertmanager:
  config:
    inhibit_rules:
    - equal:
      - alertname
      - cluster
      - namespace
      source_matchers:
      - severity="critical"
      target_matchers:
      - severity=~"info|warning"
    - equal:
      - alertname
      - cluster
      - namespace
      source_matchers:
      - severity="warning"
      target_matchers:
      - severity="info"
    - equal:
      - cluster
      - namespace
      source_matchers:
      - alertname="InfoInhibitor"
      target_matchers:
      - severity="info"
    route:
      group_by:
      - alertgroup
      - job
      group_interval: 5m
      group_wait: 30s
      repeat_interval: 12h
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-cluster-issuer-staging
    enabled: true
    hosts:
    - alertmanager.noty.cc
    ingressClassName: cilium
    tls:
    - hosts:
      - alertmanager.noty.cc
      secretName: cloudflare-alertmanager-vmks-victoria-metrics-k8s-stack
  spec:
    configReloaderResources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
    emptyDir:
      sizeLimit: 5Gi
    logLevel: WARN
    podDisruptionBudget:
      minAvailable: 1
    replicaCount: 2
    resources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
defaultDashboards:
  dashboards:
    victoriametrics-operator:
      enabled: true
    victoriametrics-vmalert:
      enabled: true
  defaultTimezone: utc
global:
  cluster:
    dnsDomain: cluster.local.
  clusterLabel: default
grafana:
  admin:
    existingSecret: vmks-grafana-credentials
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-cluster-issuer-staging
    enabled: true
    hosts:
    - grafana.noty.cc
    ingressClassName: cilium
    tls:
    - hosts:
      - grafana.noty.cc
      secretName: cloudflare-vmks-grafana
  logLevel: WARN
  podDisruptionBudget:
    minAvailable: 1
  replicas: 1
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
  sidecar:
    resources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
kube-state-metrics:
  podDisruptionBudget:
    minAvailable: 1
  replicas: 1
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
kubeApiServer:
  vmScrape:
    spec:
      endpoints:
      - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        port: https
        scheme: https
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecureSkipVerify: true
          serverName: localhost
kubeControllerManager:
  endpoints:
  - 192.168.4.2
  - 192.168.4.3
  - 192.168.4.4
  vmScrape:
    spec:
      endpoints:
      - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        port: http-metrics
        scheme: https
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecureSkipVerify: true
          serverName: localhost
kubeEtcd:
  endpoints:
  - 192.168.4.2
  - 192.168.4.3
  - 192.168.4.4
  service:
    port: 2381
    targetPort: 2381
  vmScrape:
    spec:
      endpoints:
      - port: http-metrics
        scheme: http
kubeScheduler:
  endpoints:
  - 192.168.4.2
  - 192.168.4.3
  - 192.168.4.4
  vmScrape:
    spec:
      endpoints:
      - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        port: http-metrics
        scheme: https
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecureSkipVerify: true
          serverName: localhost
prometheus-node-exporter:
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
prometheus-operator-crds:
  enabled: true
victoria-metrics-operator:
  logLevel: error
  operator:
    admissionWebhooks:
      certManager:
        enabled: true
        issuer:
          group: cert-manager.io
          kind: ClusterIssuer
          name: cert-manager-cluster-issuer
    enable_converter_ownership: true
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  replicaCount: 1
  resources:
    limits:
      cpu: null
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
vmagent:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-cluster-issuer-staging
    enabled: true
    hosts:
    - agent.noty.cc
    ingressClassName: cilium
    tls:
    - hosts:
      - agent.noty.cc
      secretName: cloudflare-vmagent-vmks-victoria-metrics-k8s-stack
  spec:
    configReloaderResources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
    logLevel: WARN
    podDisruptionBudget:
      minAvailable: 1
    replicaCount: 1
    resources:
      limits:
        cpu: null
        memory: 640Mi
      requests:
        cpu: 10m
        memory: 640Mi
    storage:
      emptyDir:
        sizeLimit: 5Gi
vmalert:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-cluster-issuer-staging
    enabled: true
    hosts:
    - alert.noty.cc
    ingressClassName: cilium
    tls:
    - hosts:
      - alert.noty.cc
      secretName: cloudflare-vmalert-vmks-victoria-metrics-k8s-stack
  spec:
    configReloaderResources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
    extraArgs:
      external.url: https://alert.noty.cc
    logLevel: WARN
    podDisruptionBudget:
      minAvailable: 1
    replicaCount: 1
    resources:
      limits:
        cpu: null
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
vmsingle:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-cluster-issuer-staging
    enabled: true
    hosts:
    - metrics.noty.cc
    ingressClassName: cilium
    tls:
    - hosts:
      - metrics.noty.cc
      secretName: cloudflare-vmsingle-vmks-victoria-metrics-k8s-stack
  spec:
    logLevel: WARN
    replicaCount: 1
    resources:
      limits:
        cpu: null
        memory: 2560Mi
      requests:
        cpu: 10m
        memory: 2560Mi
    retentionPeriod: 72h
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: longhorn
```
