### ISSUE TITLE
Unable to Mount Secret as Volume for VMAgent 

### ISSUE THREAD

**Issue by KG-FX** [VictoriaMetrics/helm-charts#1865]
**Chart Name and Version**
Chart: victoria-metrics-k8s-stack
Version: 0.32.0

**Description of Issue**
I have deployed the Victoria Metrics K8S Stack, with the Operator as a separate deployment, to a Rancher/Longhorn RKE2 cluster using FluxCD. I am trying to mount a TLS certificate, encoded as a secret, for a Prometheus scrape job in my VMAgent deployment. While the secrets, scrape jobs, and environment variables all work as intended, I am unable to mount a secret as a volume in the VMAgent. 

**Configurations**
```
---
apiVersion: v1
kind: Secret
metadata:
  name: vicm-env-secrets
  namespace: vic-metrics
type: Opaque
data:
  #Base64 Encoded
  sso-client-secret: <Omitted>  
  netbox-api-token: <Omitted>
  node-exporter-cert: <Omitted>
  node-exporter-username: <Omitted>
  node-exporter-password: <Omitted>
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: vic-metrics
spec:
  values:
    vmagent:
      envFromSecret: vicm-env-secrets
      spec:    
        volumes:
        - name: victoria-tls
          secret:
            secretName: vicm-env-secrets
            items:
              - key: node-exporter-cert
                path: node-exporter-cert.crt
        volumeMounts:
        - name: victoria-tls
          mountPath: /etc/ssl/certs/
          readOnly: true
        scrapeInterval: 10s
        inlineScrapeConfig: |
          - job_name: http
            scheme: https
            http_sd_configs:
              - url: <Omitted>
                authorization:
                  credentials: $__env{netbox-api-token}
            relabel_configs:
              - source_labels: [__meta_labels_tags]
                regex: .*ansible-managed.*
                action: keep
            tls_config: 
              ca_file: /etc/ssl/certs/node_exporter.crt
              insecure_skip_verify: true
            basic_auth:
              username: $__env{node-exporter-username}
              password: $__env{node-exporter-password}
```
