### ISSUE TITLE
question: vls-vector autoscaling conditions not applied

### ISSUE THREAD

**Issue by fmunteanu** [VictoriaMetrics/helm-charts#1881]
**Chart name and version**
chart: victoria-logs-single
version: v0.8.11

**Describe the bug**

For some reason, the `vector` autoscaling conditions are not applied. I would expect to run a max of 3 pods, especially that I allocated the double of memory needed for a pod to run, `128Mi` should be more than enough:

```
$ kubectl get pods -l=app.kubernetes.io/name=vector -n kube-system
NAME               READY   STATUS    RESTARTS   AGE
vls-vector-2gzl8   1/1     Running   0          2m50s
vls-vector-2hbvq   1/1     Running   0          2m25s
vls-vector-7pxdt   1/1     Running   0          3m34s
vls-vector-h2hq4   1/1     Running   0          2m37s
vls-vector-ptqjc   1/1     Running   0          2m42s
vls-vector-v4p5q   1/1     Running   0          2m45s
vls-vector-wd5gb   1/1     Running   0          3m26s
vls-vector-xtx4g   1/1     Running   0          2m30s
```

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
dashboards:
  enabled: true
podDisruptionBudget:
  enabled: true
  minAvailable: 1
server:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-cluster-issuer-staging
    enabled: true
    hosts:
    - name: logs.noty.cc
      path:
      - /
      port: http
    ingressClassName: cilium
    tls:
    - hosts:
      - logs.noty.cc
      secretName: cloudflare-vls-victoria-logs-single-server
  persistentVolume:
    accessModes:
    - ReadWriteOnce
    enabled: true
    size: 5Gi
    storageClassName: longhorn
  replicaCount: 1
  resources:
    limits:
      cpu: null
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 256Mi
  retentionPeriod: 7d
  serviceMonitor:
    enabled: true
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
vector:
  autoscaling:
    enabled: true
    maxReplicas: 3
    minReplicas: 1
    targetMemoryUtilizationPercentage: 80
  enabled: true
  logLevel: warn
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  podMonitor:
    enabled: true
  resources:
    limits:
      cpu: null
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 256Mi
  serviceMonitor:
    enabled: true
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
```
