### ISSUE TITLE
How to scrape k3s etcd metrics?

### ISSUE THREAD

**Issue by maaft** [VictoriaMetrics/helm-charts#1883]
### Describe the question in detail

I setup k3s etcd metrics scraping with this config (k8s-stack):
```yaml
       kubeEtcd:
          endpoints: # controlplane IPs
          - 10.253.0.101
          - 10.254.0.101
          - 10.255.0.101
          vmScrape:
            spec:
              endpoints:
              - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
                port: http-metrics
                scheme: https
                tlsConfig:
                  caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                  insecureSkipVerify: true
                metricRelabelConfigs:
                - sourceLabels: [ "__name__" ]
                  regex: "(etcd|grpc|rest_client|process|go)_(.+)"
                  action: keep
```

![image](https://github.com/user-attachments/assets/b5e6b71b-d1b2-4b6c-9cc2-1c2d2bcc2996)

But the vmagent cannot scrape these endpoint since some certificate is missing. Not sure if this is k3s related or vm related. But i don't find any ressources that help me.

What certificate is k3s requiring? And how can I supply the correct certificate?

All other k3s metrics are correctly scraped by the way. Only etcd seems to make issues.

Example for a working config for kubeProxy:
```yaml
        kubeProxy:
          endpoints:
          - 10.253.0.101
          - 10.254.0.101
          - 10.255.0.101
          vmScrape:
            spec:
              endpoints:
              - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
                port: http-metrics
                scheme: https
                tlsConfig:
                  caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                  insecureSkipVerify: true
                metricRelabelConfigs:
                - sourceLabels: [ "__name__" ]
                  regex: "(kubeproxy|rest_client|process|go)_(.+)"
                  action: keep
```

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by AndrewChubatiuk** [comment]
transfered issue to helm charts repo, as it's related to configuration not to VictoriaMetrics itself

**Comment by patrickdung** [comment]
Please re-open the issue, please let someone to check or respond before closing it.

**Comment by AndrewChubatiuk** [comment]
The answer was given [here](https://github.com/VictoriaMetrics/helm-charts/issues/1883#issuecomment-2553171699) and there was no reply then

**Comment by maaft** [comment]
Fyi, the previous workaround (overriding vmScrape and changing scheme to "http") breaks when this chart is deployed with argocd > 8.0.0.

Argocd now excludes resources (for good reasons). One of the resources are endpoints.

```
ExcludedResourceWarning
Resource /Endpoints victoria-metrics-vm-kube-proxy is excluded in the settings
16 minutes ago (Tue Jul 01 2025 14:26:12 GMT+0200)
``` 

This leads to the endpoint not being updated and as such the metrics cannot be scraped.

Not sure what the workaround is. I understand that endpoint resources are excluded for good reason, since there exist looots of endpoints in clusters and usually, these are created by k8s and not by users. If argocd would watch all endpoints, this would put considerable pressure on control plane.

Any thoughts @AndrewChubatiuk ?

**Comment by AndrewChubatiuk** [comment]
which argocd version are you using?

**Comment by maaft** [comment]
8.1.2

when i override the relevant config map section of argocd with:

(helm chart values)
```
configs:
          cm:
            timeout.reconciliation: 60s
            resource.exclusions: |
             ....
             # original but leave out Endpoints
```

then endpoints are created and scarping works.
