### ISSUE TITLE
existingClaim does not refer PVC in victoria-metrics-single chart

### ISSUE THREAD

**Issue by challapradyumna** [VictoriaMetrics/helm-charts#189]
existingClaim does not create a PVC but does not refer to the provided value in sts persistentVolumeClaim. 

https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-single/templates/server-statefulset.yaml

**Comment by f41gh7** [comment]
If i understand correctly, it is possible to fix with extraVolumes. Something like:

```yaml
server:
   persistentVolume:
       enabled: false
server:
  extraVolumes:
  - name: server-volume
    persistentVolumeClaim:
      name: exist-claim
```
