### ISSUE TITLE
bug: multiple metrics not scrapeable

### ISSUE THREAD

**Issue by steled** [VictoriaMetrics/helm-charts#1894]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: 0.33.0

**Describe the bug**
I'm not able to scrape:
- kube-controller-manager (connect: connection refused)
- kube-etcd (tls: failed to verify certificate: x509: certificate signed by unknown authority)
- kube-proxy (connect: connection refused)
- kube-scheduler (connect: connection refused)

I checked the bind-address of scheduler and controller and they are set to `127.0.0.1` so they are only listening on them:

```shell
$ netstat -tulpn | grep "10259\|10257"
(No info could be read for "-p": geteuid()=500 but you should be root.)
tcp        0      0 127.0.0.1:10259         0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:10257         0.0.0.0:*               LISTEN      -
```

How can I configure them to use in cluster communication like kube-apiserver scrape?

**Comment by AndrewChubatiuk** [comment]
hey @steled
are you using k3s?

**Comment by steled** [comment]
Hi @AndrewChubatiuk,
no I'm using plain Kubernetes in version `1.31.4` installed via [kubeone](https://github.com/kubermatic/kubeone)

**Comment by AndrewChubatiuk** [comment]
this is a default kubeone configuration issue, related to [this](https://github.com/kubermatic/kubeone/issues/1215). etcd, controller-manager, kube-scheduler have localhost bind-address. I've tried [workaround with metrics-proxy](https://github.com/kubermatic/kubeone/issues/1215#issuecomment-992471229) and it works

**Comment by steled** [comment]
I added the proxy as described [here](https://github.com/kubermatic/kubeone/issues/1215#issuecomment-992471229) and needed to update my `values.yaml` file as seen below:

```yaml
kubeControllerManager:
  service:
    port: 10252
    targetPort: 10252
  # vmScrape:
  #   spec:
  #     endpoints:
  #       - port: http-metrics
  #         scheme: http

kubeProxy:
  enabled: true
  vmScrape:
    spec:
      endpoints:
        - port: http-metrics
          scheme: http

kubeScheduler:
  service:
    port: 10251
    targetPort: 10251
  # vmScrape:
  #   spec:
  #     endpoints:
  #       - port: http-metrics
  #         scheme: http

kubeEtcd:
  service:
    port: 2381
    targetPort: 2381
  vmScrape:
    spec:
      endpoints:
        - port: http-metrics
          scheme: http
```

Unfortunately for `kube-controller-manager` and `kube-scheduler` I get the following error:

```shell
cannot perform request to "https://172.16.4.27:10252/metrics": Get "https://172.16.4.27:10252/metrics": http: server gave HTTP response to HTTPS client
```

When I enable the commented blocks I get the following error:

```shell
unexpected status code returned when scraping "http://172.16.4.27:10252/metrics": 403; expecting 200; response body: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"forbidden: User \\\"system:anonymous\\\" cannot get path \\\"/metrics\\\"\",\"reason\":\"Forbidden\",\"details\":{},\"code\":403}\n"
```

`etcd` and `proxy` are workling now.

I'm missing something?

**Comment by AndrewChubatiuk** [comment]
need to change scheme for controller-manager and scheduler scrapes from https to http

**Comment by steled** [comment]
Also tried that but than I get the following error:

```shell
unexpected status code returned when scraping "http://172.16.4.27:10252/metrics": 403; expecting 200; response body: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"forbidden: User \\\"system:anonymous\\\" cannot get path \\\"/metrics\\\"\",\"reason\":\"Forbidden\",\"details\":{},\"code\":403}\n"
```

**Comment by steled** [comment]
ok, works now... forgot to put in the `bearerTokenFile` to the endpoint...

will put my working `values.yaml` for documentation here:

```yaml
kubeControllerManager:
  service:
    port: 10252
    targetPort: 10252
  vmScrape:
    spec:
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
          scheme: http

kubeEtcd:
  service:
    port: 2381
    targetPort: 2381
  vmScrape:
    spec:
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
          scheme: http

kubeProxy:
  enabled: true
  vmScrape:
    spec:
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
          scheme: http

kubeScheduler:
  service:
    port: 10251
    targetPort: 10251
  vmScrape:
    spec:
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
          scheme: http
```
