### ISSUE TITLE
question: Cannot supply duplicate arguments

### ISSUE THREAD

**Issue by PseudoResonance** [VictoriaMetrics/helm-charts#1904]
**Chart name and version**
chart: victoria-logs-single (Issue is partly in victoria-metrics-common though)
version: v0.8.11

**Describe the bug**
Duplicate `extraArgs` cannot be provided, and argument order is not preserved as `extraArgs` is a dictionary and not a list.

This is acceptable for most cases, however as an example, VictoriaLogs allows configuring multiple syslog ports with different options, such as extraFields. The following arguments are impossible to pass in the current Helm chart.

```
--syslog.listenAddr.udp=:515
--syslog.extraFields.udp=''{"hostname":"switch"}''
--syslog.listenAddr.udp=:514
--syslog.extraFields.udp=''{}''
```

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
server:
  extraArgs:
    syslog.listenAddr.udp: ":515"
    syslog.extraFields.udp: ''{"hostname":"switch"}''
    syslog.listenAddr.udp: ":514"
    syslog.extraFields.udp: "'{}'"
```

**Comment by AndrewChubatiuk** [comment]
hey @PseudoResonance 
to pass same argument multiple times in `extraArgs` map for each key consider using array value
```
server:
  extraArgs:
    syslog.listenAddr.udp: [":515", ":514"]
    syslog.extraFields.udp: ['{"hostname":"switch"}', '{}']
```

**Comment by PseudoResonance** [comment]
Unless I'm misunderstanding, I don't think this is parsed correctly by VictoriaLogs either. Using that sample, I got the following output:

```yaml
- --syslog.extraFields.udp={"hostname":"switch"}
- --syslog.extraFields.udp={}
- --syslog.listenAddr.udp=:515
- --syslog.listenAddr.udp=:514
```

The order of arguments relative to the order of the initial arrays makes sense of course, but the documentation seemed to suggest that they should be in this order:

```yaml
- --syslog.listenAddr.udp=:515
- --syslog.extraFields.udp={"hostname":"switch"}
- --syslog.listenAddr.udp=:514
- --syslog.extraFields.udp={}
```

I assumed that the `listenAddr` is supplied first, then all further arguments are matched with it, until the next `listenAddr` is supplied, but perhaps that was incorrect.

**Comment by AndrewChubatiuk** [comment]
issue is not related to an order. problem is that passed json was not quoted and caused issues
I've updated common dependency and released logs chart 0.8.12, please check it and set values to
```
server:
  extraArgs:
    syslog.listenAddr.udp: [":515", ":514"]
    syslog.extraFields.udp:
     - hostname: switch
     - {}
```
