### ISSUE TITLE
bug: can no longer deploy vmcluster and vmsingle simultaneously

### ISSUE THREAD

**Issue by antoinedeschenes** [VictoriaMetrics/helm-charts#1911]
**Chart name and version**
chart: victoria-metrics-operator
version: v0.33.2

**Describe the bug**
Our current VictoriaMetrics architecture deploys a cluster-local vmalert, vmagent and vmsingle on every K8s clusters we have deployed, while a separate vmcluster receives the aggregated data from all vmagents. 

We find that we are no longer able to deploy vmcluster and vmsingle simultaneously when upgrading from 0.27.4 to 0.33.2. The following error message comes up:
```
Error: Failed to render chart: exit status 1: Error: execution error at (victoria-metrics/charts/vmstack/templates/victoria-metrics-operator/vmsingle/vmsingle.yml:4:6): Only one of .vmsingle.enabled and .vmcluster.enabled can be true
```

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
  vmcluster:
    enabled: true
  vmsingle:
    enabled: true
  vmagent:
    additionalRemoteWrites:
      - url: http://vminsert-vmstack.victoria-metrics.svc.cluster.local:8480/insert/0/prometheus/api/v1/write
```
