### ISSUE TITLE
question: emptyDir definition for vmsingle.spec.storage

### ISSUE THREAD

**Issue by fmunteanu** [VictoriaMetrics/helm-charts#1912]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.33.2

**Describe the bug**
Looking at the [documentation](https://docs.victoriametrics.com/operator/api/index.html#vmsinglespec), it is unclear how `vmsingle.spec.storage.emptyDir` is defined:

https://github.com/VictoriaMetrics/helm-charts/blob/victoria-metrics-k8s-stack-0.33.2/charts/victoria-metrics-k8s-stack/values.yaml#L277

I'm currently using `longhorn` as storage class:

```yaml
    vmsingle:
      spec:
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: longhorn
```

The helm chart does not gives me the ability to define `emptyDir` like:

```yaml
    vmsingle:
      spec:
        storage:
          emptyDir:
            sizeLimit: 50Gi
```

It will automatically force the use of `vmsingle.spec.storage` present into chart. Documentation mentions:

> Storage is the definition of how storage will be used by the VMSingle
> by default it`s empty dir
> this option is ignored if storageDataPath is set

Which to me is confusing. Ideally, `vmsingle.spec.storage` should use the [StorageSpec](https://docs.victoriametrics.com/operator/api/index.html#storagespec) implementation.

**Comment by AndrewChubatiuk** [comment]
at the moment emptyDir is not configurable for vmsingle and vlogs. cc @f41gh7

**Comment by fmunteanu** [comment]
That's what I figured @AndrewChubatiuk. Is this documentation part that was confusing:

> by default it`s empty dir

Are there any plans to implement StorageSpec?

**Comment by f41gh7** [comment]
`storage` field is intended to be used for `PersistentVolumeClaim` configuration.

But there is workaround -  if `storageDataPath` is explicitly defined, operator ignores value of `storage` field. And uses volumes instead.  Currently it's required to use `name: data` for it.

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: sized-emptydir

spec:
  storageDataPath: "/vmdata"
  volumes:
    - name: data
      emptyDir:
        sizeLimit: 5Gi
  volumeMounts:
    - mountPath: /vmdata
      name: data
```
