### ISSUE TITLE
bug: Missing updateStrategy, when podDisruptionBudget.minAvailable set

### ISSUE THREAD

**Issue by fmunteanu** [VictoriaMetrics/helm-charts#1928]
**Chart name and version**
chart: victoria-logs-single
version: v0.8.13

**Describe the bug**
I believe the `updateStrategy` should be defined, for added flexibility. Currently, it is not.

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
podDisruptionBudget:
  enabled: true
  minAvailable: 1
updateStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate
```

Without an `updateStrategy`, pods will never be evicted if `podDisruptionBudget.minAvailable` is set and replicas = 1.

Slack [discussion](https://victoriametrics.slack.com/archives/CGZF1H6L9/p1737091599727769)
