### ISSUE TITLE
vmagent has no permissions to get k8s ingresses objects

### ISSUE THREAD

**Issue by Vladikamira** [VictoriaMetrics/helm-charts#194]
I got message like this:
```
{"ts":"2021-08-23T12:31:31.047Z","level":"error","caller":"VictoriaMetrics/lib/promscrape/discovery/kubernetes/api_watcher.go:433","msg":"unexpected status code for request to \"https://10.31.124.1:443/apis/networking.k8s.io/v1beta1/ingresses\": 403; want 200; response: \"{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"ingresses.networking.k8s.io is forbidden: User \\\\\\\"system:serviceaccount:monitoring:victoria-metrics-agent-regional\\\\\\\" cannot list resource \\\\\\\"ingresses\\\\\\\" in API group \\\\\\\"networking.k8s.io\\\\\\\" at the cluster scope\\\",\\\"reason\\\":\\\"Forbidden\\\",\\\"details\\\":{\\\"group\\\":\\\"networking.k8s.io\\\",\\\"kind\\\":\\\"ingresses\\\"},\\\"code\\\":403}\\n\""}
```
for configuration on k8s Service Discovery
```
    - job_name: blackbox-ingresses-sd
      kubernetes_sd_configs:
      - role: ingress
      metrics_path: /probe
      params:
        module:
        - http_2xx_3xx_4xx
      relabel_configs:
 ....
```
as an result, nothing were discovered
Could we add proper role in the Helm chart? Or there is another way around?
Vmagent chart version: `0.7.14`
