### ISSUE TITLE
[victoria-metrics-single] Affinity is templated twice in deployment if set

### ISSUE THREAD

**Issue by Jeinhaus** [VictoriaMetrics/helm-charts#195]
When using the `victoria-metrics-single` chart with the statefulSet disabled and using any value for the `server.affinity` value, the chart fails to render with this error:
```
Helm upgrade failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:                                                                                        
  line 81: mapping key "affinity" already defined at line 31
```

A minimal `values.yaml` file looks like this:

```yaml
server:
  statefulSet:
    enabled: false
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
```

I think the reason is that the [server-deployment.yaml](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-single/templates/server-deployment.yaml) defines the affinity key twice (in [line 35](https://github.com/VictoriaMetrics/helm-charts/blob/a323349c7d153ce4c7392206710cd1a81e031f51/charts/victoria-metrics-single/templates/server-deployment.yaml#L35) and [line 215](https://github.com/VictoriaMetrics/helm-charts/blob/a323349c7d153ce4c7392206710cd1a81e031f51/charts/victoria-metrics-single/templates/server-deployment.yaml#L215)).

Am I overlooking some configuration or is this a bug in the chart?
