### ISSUE TITLE
bug: GrafanaDashboard metadata.annotations: Too long: must have at most 262144 bytes on dashboards

### ISSUE THREAD

**Issue by dudizimber** [VictoriaMetrics/helm-charts#1951]
**Chart name and version**
chart: victoria-metrics-operator
version: v0.6.0

**Describe the bug**
When deploying the `grafana-operator`, the GrafanaDashboards do not receive the `defaultDashboards.annotation` parameters, so they cannot be applied on the server side. 

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
defaultDashboards:
  enabled: true
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  grafanaOperator:
    enabled: true
```

**Comment by zekker6** [comment]
Reopening until the fix in #1952 will be released.

**Comment by dudizimber** [comment]
@zekker6 when can we expect a release with this fix?

**Comment by AndrewChubatiuk** [comment]
just released 0.35.1

**Comment by zekker6** [comment]
Closing this as it was released in 0.35.1 - https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.35.1

**Comment by burner1024** [comment]
Doesn't seem to work for me.

```yaml
spec:
  destination:
    namespace: vm
    server: "{{ .Values.spec.destination.server }}"
  project: default
  source:
    chart: victoria-metrics-k8s-stack
    helm:
      values: |
        alertmanager:
          enabled: false
        grafana:
          enabled: false
        defaultDashboards:
          enabled: true
          annotations:
            argocd.argoproj.io/sync-options:
              ServerSideApply: true
        vmsingle:
          enabled: false
        vmagent:
          spec:
            remoteWrite:
              - url: https://vmetrics.my.url/api/v1/write
        victoria-metrics-operator:
          admissionWebhooks:
            certManager:
              enabled: true
        vmalert:
          enabled: false
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: 0.36.2
```

```
ConfigMap "vm-victoria-metrics-k8s-stack-node-exporter-full" is invalid: metadata.annotations: Too long: must have at most 262144 bytes -Additional Info: This error usually means that you are trying to add a large resource on client side. Consider using Server-side apply or syncing with replace enabled. Note: Syncing with Replace enabled is potentially destructive as it may cause resource deletion and re-creation.
```
