### ISSUE TITLE
How to configure vmagent remoteWrite relabel configuration?

### ISSUE THREAD

**Issue by cykl** [VictoriaMetrics/helm-charts#196]
Using victoria-metrics-agent chart, I had like to configure `remoteWrite.relabelConfig`. However, chart doesn't seems to support such configuration file as first class citizen. 

My limited knowledge of Helm / K8s drives me toward something like this:

```yaml
extraArgs:
  remoteWrite.relabelConfig: /etc/vmagent/relabel-config.yml

extraVolumeMounts:
  - name: relabel-config
    mountPath: /etc/vmagent/relabel-config.yml

extraVolumes:
  - name: relabel-config
    configMap:
      name: vmagent-relabel-configmap
```

And then manually manage `vmagent-relabel-configmap`.

Is there a better way to do that? If not, wouldn't it make sense to provide a better user experience?
