### ISSUE TITLE
bug: cluster configuration with opentsdbListenAddr

### ISSUE THREAD

**Issue by vivienbcr** [VictoriaMetrics/helm-charts#1961]
**Chart name and version**
chart: victoria-metrics-operator
version: v0.17.3 and master branch

**Describe the bug**

I'm trying to deploy victoria-metrics-cluster with opentsdbL enabled and i'm facing to this error :

````
helm install vmc vm/victoria-metrics-cluster -f values.yaml -n ns
Error: UPGRADE FAILED: template: victoria-metrics-cluster/templates/service.yaml:54:11: executing "victoria-metrics-cluster/templates/service.yaml" at <include $portsTpl $app>: error calling include: template: victoria-metrics-cluster/templates/_helpers.tpl:210:18: executing "vminsert.ports" at <.service.udp>: can't evaluate field service in type string
````

**Custom values**

```yaml
vminsert:
  extraArgs:
    opentsdbListenAddr: :4242
  service:
    type: ClusterIP
    udp: true
```
