### ISSUE TITLE
feature: Allow VMAgent to scrape non-default metrics paths without modifying ClusterRole template

### ISSUE THREAD

**Issue by jorben5** [VictoriaMetrics/helm-charts#1970]
**Chart name and version, where you feel a lack of requested feature**
chart: [victoria-metrics-agent](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-agent)
version: 0.15.6

**Is your feature request related to a problem? Please describe.**
I'm trying to configure VMAgent to scrape custom metrics (Kubernetes Component SLI Metrics) from the Kubernetes API server (https://kubernetes.io/docs/reference/instrumentation/slis/). My scrape job looks like this:
```
- job_name: "sli-job"
  scheme: https
  tls_config:
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  static_configs:
    - targets:
        - "kubernetes.default.svc:443"
      labels:
        job: "mhd-sli-job"
  metrics_path: "/metrics/slis"
```
However, by default, VMAgent lacks the necessary permissions to scrape anything other than /metrics, since the Helm chart does not include an option to extend the ClusterRole permissions.

**Describe the solution you'd like**
Add:
```
nonResourceURLs: ["/metrics", "/metrics/slis"]
```
by default, or provide an option to extend this list through Helm values.

**Additional context**
This change would make it easier to scrape non-default metric paths without requiring manual modifications to the Helm chart. It would also provide more flexibility for users who need to collect custom metrics from API endpoints that are not covered by default permissions.
