### ISSUE TITLE
bug: Kubernetes/View/Pods Grafana Dashboard not showing any data

### ISSUE THREAD

**Issue by Kushagratandon12** [VictoriaMetrics/helm-charts#1979]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.35.7

**Describe the bug**
After upgrading the chart I cannot see the Kubernetes/View/Pods data showing up on Grafana, While other charts are showing data without any issue's 

<img width="767" alt="Image" src="https://github.com/user-attachments/assets/0b3eb148-4dee-41e4-9c30-b340188b6af2" />

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
victoria-metrics-operator:
  admissionWebhooks:
    enabled: false
  enabled: true
  serviceMonitor:
    enabled: false

defaultDashboards:
  dashboards:
    victoriametrics-vmalert:
      enabled: true
    victoriametrics-operator:
      enabled: true
    node-exporter-full:
      enabled: true

defaultRules:
  create: true

vmsingle:
  enabled: true
  nodeSelector:
    node_type: jenkins-master
  resources:
    limits:
      cpu: '1'
      memory: 5Gi
  spec:
    retentionPeriod: '1'
    replicaCount: 1
    storage:
      storageClassName: gp3
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  ingress:
    enabled: true
    hosts:
      - <hidden>

vmagent:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - <hidden>

vmcluster:
  enabled: false

vmalert:
  # -- VMAlert annotations
  annotations: {}
  # -- Create VMAlert CR
  enabled: false

alertmanager:
  enabled: false
  # -- (object) Alertmanager ingress configuration
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - <hidden>

# -- prometheus-node-exporter dependency chart configuration. For possible values check [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml)
prometheus-node-exporter:
  enabled: true

  # all values for prometheus-node-exporter helm chart can be specified here
  service:
    # Add the 'node-exporter' label to be used by serviceMonitor to match standard common usage in rules and grafana dashboards
    #
    labels:
      jobLabel: node-exporter
  extraArgs:
    - '--collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)'
    - '--collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$'
  # -- Node Exporter VM scrape config
  vmScrape:
    # whether we should create a service scrape resource for node-exporter
    enabled: true
    # -- [Scrape configuration](https://docs.victoriametrics.com/operator/api#vmservicescrapespec) for Node Exporter
    spec:
      jobLabel: jobLabel
      selector:
        matchLabels:
          app.kubernetes.io/name: '{{ include "prometheus-node-exporter.name" (index
            .Subcharts "prometheus-node-exporter") }}'
      endpoints:
        - port: metrics
          metricRelabelConfigs:
            - action: drop
              source_labels:
                - mountpoint
              regex: /var/lib/kubelet/pods.+

grafana:
  dashboard:
    overview: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - <hidden>
  vmScrape:
    enabled: false
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Viewer
    auth:
      disable_login_form: false

kubeApiServer:
  enabled: false

kubeControllerManager:
  enabled: false
  vmScrape:
    enabled: false

kubeDns:
  enabled: false

coreDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false
```
