### ISSUE TITLE
bug: The recommended `external.alert.source` for Grafana does not work

### ISSUE THREAD

**Issue by tropnikovvl** [VictoriaMetrics/helm-charts#1994]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: latest

**Describe the bug**
The [documentation](https://docs.victoriametrics.com/vmalert/#link-to-alert-source) recommends adding these flags

```
./bin/vmalert \
    -external.url=http://<grafana-addr> \  # the hostname and port for Grafana 
    -external.alert.source='explore?left={"datasource":"VictoriaMetrics","queries":[{"expr":{{ .Expr|jsonEscape|queryEscape }},"refId":"A"}],"range":{"from":"{{ .ActiveAt.UnixMilli }}","to":"now"}}'
```

When I try to add them to the chart I get an error

> Error: template: victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/vmalert.yaml:17:9: executing "victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/vmalert.yaml" at <include "vm.alert.spec" $ctx>: error calling include: template: victoria-metrics-k8s-stack/templates/_helpers.tpl:131:6: executing "vm.alert.spec" at <tpl (deepCopy (omit $Values.vmalert.spec "notifiers") | mergeOverwrite $vmAlertRemotes | mergeOverwrite $vmAlertTemplates | mergeOverwrite $spec | toYaml) .>: error calling tpl: cannot parse template "configMaps: []\ndatasource:\n  url: http://vmsingle-release-name-victoria-metrics-k8s-stack.default.svc.cluster.local.:8429\nevaluationInterval: 20s\nexternalLabels: {}\nextraArgs:\n  external.alert.source: explore?left={\"datasource\":\"VictoriaMetrics\",\"queries\":[{\"expr\":\"{{.Expr|jsonEscape|queryEscape}}\",\"refId\":\"A\"}],\"range\":{\"from\":\"{{.ActiveAt.UnixMilli}}\",\"to\":\"now\"}}\n  external.url: https://grafana.fofo.ro\n  http.pathPrefix: /\n  remoteWrite.disablePathAppend: \"true\"\nimage:\n  tag: v1.111.0\nlicense: {}\nnotifiers:\n- url: http://vmalertmanager-release-name-victoria-metrics-k8s-stack-0.vmalertmanager-release-name-victoria-metrics-k8s-stack.default.svc.cluster.local.:9093\nport: \"8080\"\nremoteRead:\n  url: http://vmsingle-release-name-victoria-metrics-k8s-stack.default.svc.cluster.local.:8429\nremoteWrite:\n  url: http://vmsingle-release-name-victoria-metrics-k8s-stack.default.svc.cluster.local.:8429/api/v1/write\nselectAllByDefault: true": template: gotpl:7: function "jsonEscape" not defined

**Custom values**

```yaml
external:
  grafana:
    host: grafana.fofo.ro

vmalert:
  enabled: true
  spec:
    extraArgs:
      external.url: https://grafana.fofo.ro
      external.alert.source: 'explore?left={"datasource":"VictoriaMetrics","queries":[{"expr":"{{.Expr|jsonEscape|queryEscape}}","refId":"A"}],"range":{"from":"{{.ActiveAt.UnixMilli}}","to":"now"}}'
```

**Comment by tiny-pangolin** [comment]
I ran into something similar recently with docker compose, does removing the `'` at the beginning and end of the external.alert.source value work for you?

**Comment by tropnikovvl** [comment]
@tiny-pangolin unfortunately no

**Comment by AndrewChubatiuk** [comment]
looks like you need to escape template as first helm renders it and then it's rendered by vmalert

**Comment by tropnikovvl** [comment]
How can I do it?

**Comment by AndrewChubatiuk** [comment]
suppose it should be something like this
```
vmalert:
  spec:
    extraArgs:
      external.alert.source: 'explore?left={"datasource":"VictoriaMetrics","queries":[{"expr":"{{"{{"}}.Expr|jsonEscape|queryEscape{{"}}"}}","refId":"A"}],"range":{"from":"{{"{{"}}.ActiveAt.UnixMilli{{"}}"}}","to":"now"}}'
```
