### ISSUE TITLE
bug: CRDs are not updated when the operator helm chart is updated

### ISSUE THREAD

**Issue by tropnikovvl** [VictoriaMetrics/helm-charts#2001]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: latest

**Describe the bug**
CRDs are not updated when the operator helm chart is updated.
I tested it on a test environment and it doesn't work.

I install an old version of the stack with the operator version 0.52.0

```
helm upgrade -i vm vm/victoria-metrics-k8s-stack --version 0.35.7 -f stack.yaml
```

After that, I update to the latest version where the operator is 0.53.0 and a new field `VLogs` is added to the `targetRefs` in the CRD `VMUser`.

```
helm upgrade -i vm vm/victoria-metrics-k8s-stack --version 0.36.2 -f stack.yaml
```

And I see that these fields in the CRD have not changed, although they should have since they are here.
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-operator/charts/crds/crds/crd.yaml#L31860

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
victoria-metrics-operator:
  enabled: true

defaultDashboards:
  enabled: false

defaultRules:
  create: false

vmsingle:
  enabled: false

vmcluster:
  enabled: false

alertmanager:
  enabled: false

vmalert:
  enabled: false

vmauth:
  enabled: false

vmagent:
  enabled: false

grafana:
  enabled: false

prometheus-node-exporter:
  enabled: false

kube-state-metrics:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false

```
