### ISSUE TITLE
question: how to add "automountServiceAccountToken: false" for vmagent

### ISSUE THREAD

**Issue by hwxy233** [VictoriaMetrics/helm-charts#2006]
**Chart name and version, where you feel a lack of requested feature**
chart: victoria-metrics-k8s-stack
version: v0.36.2

**Is your feature request related to a problem? Please describe.**

Dear team, I use `victoria-metrics-k8s-stack` helm chart to monitor `AKS` cluster. Recently, the azure administrator tells me a `Kubernetes clusters should disable automounting API credentials` problem was found in `vmagent-vmks-victoria-metrics-k8s-stack-xxx` pod.
To fix this, I want to add `automountServiceAccountToken: false` config in `values.yaml` at `vmagent` part, but it does not work.
Then I read this doc  [vmagentspec](https://docs.victoriametrics.com/operator/api#vmagentspec) , I can not find `automountServiceAccountToken` config.
My question is how to add `automountServiceAccountToken: false` for vmagent, thanks.

**Describe the solution you'd like**
I can add "automountServiceAccountToken: false" and projected token voume for vmagent part in `values.yaml` like `victoria-metrics-operator` part:
```yaml
victoria-metrics-operator:
  serviceAccount:
    automountServiceAccountToken: false
  extraVolumes:
    - name: operator
      projected:
        sources:
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
          - configMap:
              name: kube-root-ca.crt
          - serviceAccountToken:
              expirationSeconds: 7200
              path: token
  extraVolumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: operator
```

**Describe alternatives you've considered**
N/A

**Additional context**

The k8s cluster version is `1.27.9`

The `vmagent` part in `values.yaml` is present:
```yaml
vmagent:
  # -- Create VMAgent CR
  enabled: true
  # -- VMAgent annotations
  annotations: { }
  # -- Remote write configuration of VMAgent, allowed parameters defined in a [spec](https://docs.victoriametrics.com/operator/api#vmagentremotewritespec)
  additionalRemoteWrites:
    - url: https://my-single-vm-node-ouside-aks/victoria-write/

  # -- (object) Full spec for VMAgent CRD.
  #  Allowed values described [here](https://docs.victoriametrics.com/operator/api#vmagentspec)
  automountServiceAccountToken: false # this is not working
  spec:
    # automountServiceAccountToken: false # I try to add it there, but it is also not working
    port: "8429"
    # bugfix: non root
    securityContext:
      fsGroup: 65534
      runAsGroup: 65534
      runAsNonRoot: true
      runAsUser: 65534
    containers:
      - name: config-reloader
        image: myacr/prometheus-operator/prometheus-config-reloader:v0.68.0
    initContainers:
      - name: config-init
        image: myacr/prometheus-operator/prometheus-config-reloader:v0.68.0
    image:
      repository: myacr/victoriametrics/vmagent
      tag: v1.102.1
      pullPolicy: IfNotPresent
    selectAllByDefault: true
    scrapeInterval: 20s
    externalLabels:
      # For multi-cluster setups it is useful to use "cluster" label to identify the metrics source.
      # For example:
      cluster: my-aks-cluster
    extraArgs:
      promscrape.streamParse: "true"
      # Do not store original labels in vmagent's memory by default. This reduces the amount of memory used by vmagent
      # but makes vmagent debugging UI less informative. See: https://docs.victoriametrics.com/vmagent/#relabel-debug
      promscrape.dropOriginalLabels: "true"
  # -- (object) VMAgent ingress configuration
  ingress:
    enabled: false
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    # ingressClassName: nginx
    # Values can be templated
    annotations:
      { }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    labels: { }
    path: ""
    pathType: Prefix

    hosts:
      - vmagent.domain.com
    extraPaths: [ ]
```

**Comment by AndrewChubatiuk** [comment]
hey @hwxy233 
unfortunately this is not supported by operator at the moment

**Comment by hwxy233** [comment]
hi @AndrewChubatiuk ,thanks for answer, I find [https://docs.victoriametrics.com/helm/victoriametrics-agent/](https://docs.victoriametrics.com/helm/victoriametrics-agent/) single vmagent can set `serviceAccount.automountToken`, I will try vmagent helm chart.

**Comment by zekker6** [comment]
Hi @hwxy233 @tiny-pangolin 

>  believe we ran into this problem with a different user recently was the solution to create the service account separately and specify there service account when configuring the CRD? 

Yes, it is possible to use `serviceAccountName` as a part of [VMAgent spec](https://docs.victoriametrics.com/operator/api/index.html#vmagentspec) to point it to a manually created service amount with automatic mount being disabled.

> lso since this has occurred multiple times should we have a blog post or docs that describes how to use the k8s stack in AKS?

We do have somewhat similar [blog post](https://victoriametrics.com/blog/monitoring-azure-aks-azure-linux-with-victoriametrics/), but it does not cover using enhanced security config for AKS itself. It would be great to either extend/update this blog post or to convert it into a guide as a part of our [docs](https://docs.victoriametrics.com/guides/).

**Comment by hwxy233** [comment]
Hi @tiny-pangolin @zekker6 

Thanks you for the suggestion. The custom service account approach worked for me on my local test k8s cluster.
But on AKS, the problem is still being scanned.

I read some docs([Azure BlockAutomountToken Policy](https://github.com/Azure/azure-policy/blob/a8512e1f5feab86d1a8a73a64676612ae88cb6a7/built-in-policies/policyDefinitions/Kubernetes/BlockAutomountToken.json#L156) and [template.yaml](https://store.policy.core.windows.net/kubernetes/block-automount-token/v2/template.yaml)) and find AKS policy does not check `automountServiceAccountToken` in `serviceAccount`.
So even if I set `automountServiceAccountToken: false` and use a manual mount token, it will still be scanned
incorrectly.

I will ask my Azure administrator if he can communicate with Azure. For now, I will try to use `vmagent` helm chart to replace the `vmagent` in `vmks` helm chart.
If `vmagent` in `vmks` can set `automountServiceAccountToken` in the future, I will make an update.

Anyway, I will write the steps how to use custom serviceAccount there, if Azure can fix their policy issue or someone
can use a fixed policy.

Below is a streamlined guide:

## 1. Create a Custom Service Account

### 1.1 Service Account Configuration

Key configuration: `automountServiceAccountToken: false`

```yaml
# sa.yaml
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: vmagent-service-account
  namespace: <YOUR_VMKS_NAMESPACE>
```

Apply with:

```bash
kubectl apply -f sa.yaml -n <YOUR_VMKS_NAMESPACE>
```

### 1.2  Configure RBAC Rules

The` vmagent` will request the `Kubernetes API`, `ClusterRole` & `ClusterRoleBinding` are required for authorisation.

### ClusterRole:

Remove unnecessary permissions from ClusterRole based on your monitoring needs.

```yaml
# cr.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmagent-monitoring-role
rules:
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs: [ "get", "list", "watch" ]
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/metrics
      - nodes/proxy
      - services
      - endpoints
      - pods
      - configmaps
      - namespaces
      - secrets
    verbs: [ "get", "list", "watch" ]
  - apiGroups:
      - networking.k8s.io
      - extensions
    resources:
      - ingresses
    verbs: [ "get", "list", "watch" ]
  - nonResourceURLs:
      - /metrics
      - /metrics/resources
    verbs: [ "get", "list", "watch" ]
```

### ClusterRoleBinding

```yaml
# crb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vmagent-monitoring-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmagent-monitoring-role
subjects:
  - kind: ServiceAccount
    name: vmagent-service-account
    namespace: <YOUR_VMKS_NAMESPACE>

```

Apply with:

```bash
kubectl apply -f cr.yaml
kubectl apply -f crb.yaml
```

Verify binding:

```yaml
kubectl describe clusterrolebinding vmagent-monitoring-role-binding
```

## 2. Configure Helm Values

### 2.1 Basic VMAgent Configuration

Key configuration: `serviceAccountName: vmagent-service-account`

```yaml
# values.yaml
vmagent:
  enabled: true
  spec:
    serviceAccountName: vmagent-service-account
    port: "8429"
    securityContext:
      fsGroup: 65534
      runAsGroup: 65534
      runAsNonRoot: true
      runAsUser: 65534
    scrapeInterval: 20s
    extraArgs:
      promscrape.streamParse: "true"
      promscrape.dropOriginalLabels: "true"

```

### 2.2 Manual Token Mounting

To request the `Kubernetes API` for authentication, a `projected volume` is mounted on the `config-reloader` container,
the `config-init` container and `vmagent` itself.

The full `vmagent` part is like:

```yaml
# values.yaml
vmagent:
  enabled: true
  annotations: { }
  additionalRemoteWrites:
    - url: https://<YOUR_VM_SERVER_WRITE_API>/

  spec:
    serviceAccountName: vmagent-service-account
    port: "8429"
    securityContext:
      fsGroup: 65534
      runAsGroup: 65534
      runAsNonRoot: true
      runAsUser: 65534
    containers:
      - name: config-reloader
        image: <YOUR_ACR>/prometheus-operator/prometheus-config-reloader:<YOUR_TAG>
        volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: kube-api-access-vmagent
            readOnly: true
    initContainers:
      - name: config-init
        image: <YOUR_ACR>/prometheus-operator/prometheus-config-reloader:<YOUR_TAG>
        volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: kube-api-access-vmagent
            readOnly: true
    image:
      repository: <YOUR_ACR>/victoriametrics/vmagent
      tag: <YOUR_TAG>
      pullPolicy: IfNotPresent
    selectAllByDefault: true
    scrapeInterval: 20s
    externalLabels:
      cluster: <YOUR_CLUSTER>
    extraArgs:
      promscrape.streamParse: "true"
      promscrape.dropOriginalLabels: "true"

    volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-vmagent
        readOnly: true
    volumes:
      - name: kube-api-access-vmagent
        projected:
          defaultMode: 420
          sources:
            - serviceAccountToken:
                expirationSeconds: 3607
                path: token
            - configMap:
                name: kube-root-ca.crt
            - downwardAPI:
                items:
                  - fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
                    path: namespace
```

Then use `helm upgrade` command to update and use `kubectl logs` to check `operator` log and `vmagent` log.
