### ISSUE TITLE
bug: vmagent helm chart ingress.enabled: true does not imply service.enabled true and does not fail

### ISSUE THREAD

**Issue by fayak** [VictoriaMetrics/helm-charts#2007]
**Chart name and version**
chart: victoria-metrics-operator
version: v0.15.8

**Describe the bug**
I enabled the ingress but not explicitly the service, and it did not create the service nonetheless, making the ingress not working.
I reckon enabling the ingress should automatically enable the service, or at least prevent the template from rendering ?

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
ingress:
    enabled: true

remoteWrite:
    - url: dummy
```
