### ISSUE TITLE
Chart victoria-metrics-operator resource VMServiceScrape.Endpoint does not support proxyUrl field

### ISSUE THREAD

**Issue by morooshka** [VictoriaMetrics/helm-charts#2029]
Chart victoria-metrics-operator, resource VMServiceScrape does not support resource field [Endpoint.proxyUrl](https://docs.victoriametrics.com/operator/api/#endpoint): [HERE](https://github.com/VictoriaMetrics/helm-charts/blob/6cce611ada2c4f85661365e2308e78e9e49a0531/charts/victoria-metrics-operator/templates/service_scrape.yaml#L22)
As a result an error on chart update:

~~~
[....]$ helm upgrade --cleanup-on-fail \
    victoria vm/victoria-metrics-k8s-stack \
    --namespace victoria-metrics \
    --version=0.35.1 \
    --values ./charts/victoria-metrics/values.yaml
W0302 21:53:38.471299   96352 warnings.go:70] unknown field "spec.endpoints[0].proxyUrl"
Error: UPGRADE FAILED: cannot patch "victoria-victoria-metrics-k8s-stack-kube-proxy" with kind Service: Service "victoria-victoria-metrics-k8s-stack-kube-proxy" is invalid: [spec.ipFamilyPolicy: Invalid value: "RequireDualStack": this cluster is not configured for dual-stack services, spec.ipFamilies[1]: Invalid value: "IPv6": not configured on this cluster]
~~~

**Comment by morooshka** [comment]
@AndrewChubatiuk Hello! Thank you for looking into it. Can you please help me to understand - is that only about chart to add or the problem is bigger and `VMServiceScrape` does not support it? I would like to make a patch and contribute but I do not understand how big the problem is

**Comment by AndrewChubatiuk** [comment]
I've added support for proxyURL in a latest chart release, but your issue is related to `ipFamilyPolicy: RequireDualStack` value. Error reports, that you k8s cluster has no dual stack configured

**Comment by morooshka** [comment]
@AndrewChubatiuk I thought it was some strange bug, because I've removed `proxyURL` from the values and the problem were still there. I've deleted the service manually and rerun the chart update - and the problem gone. So I came to conclusion that `proxyURL` does not require `RequireDualStack` naturally, especially taking into consideration I am already using it via additional scrape configs Secret:
~~~
    - job_name: "kube-proxy"
      proxy_url: "http://pushprox-kube-proxy-proxy.kube-system.svc:8080"
      static_configs:
      - targets: 
        - "http://XXX:10249"
        - "http://XXX:10249"
        - "http://XXX:10249"
~~~

**Comment by morooshka** [comment]
@AndrewChubatiuk I have applied it and the chart is updated without errors and accept the `proxyURL` param. However the resource `VMServiceScrape` still does not have that item. Does it meant it is not supported there? Can you please help me how to check it?

**Comment by AndrewChubatiuk** [comment]
latest chart version with
```
serviceMonitor:
  enabled: true
  proxyURL: test-value
```
generates 
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: release-name-victoria-metrics-operator
  namespace: default
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-operator
    app.kubernetes.io/version: v0.53.0
    helm.sh/chart: victoria-metrics-operator-0.42.4
spec:
  selector:
    matchLabels: 
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: victoria-metrics-operator
  endpoints:
    - port: http
      proxyURL: test-value
  namespaceSelector:
    matchNames:
      - default
```

so there's proxyURL there
