### ISSUE TITLE
bug: vmcluster doesn't place image tag in correct place (0.38.2)

### ISSUE THREAD

**Issue by idogada-akamai** [VictoriaMetrics/helm-charts#2034]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.38.2

**Describe the bug**
When enabling vmcluster. The tags for vminsert and vmstorage and placed directly under `vminsert/vmstorage`.

Behavior:
```yaml
spec: 
  license: {}
  replicationFactor: 2
  retentionPeriod: "1"
  vminsert:
    extraArgs: {}
    port: "8480"
    replicaCount: 2
    resources: {}
    tag: v1.112.0-cluster
  vmstorage:
    replicaCount: 2
    resources: {}
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi
    storageDataPath: /vm-data
    tag: v1.112.0-cluster
```
Expected:
```yaml
spec: 
  license: {}
  replicationFactor: 2
  retentionPeriod: "1"
  vminsert:
    extraArgs: {}
    image:
      tag: v1.112.0-cluster
    port: "8480"
    replicaCount: 2
    resources: {}
  vmstorage:
    image:
      tag: v1.112.0-cluster
    replicaCount: 2
    resources: {}
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi
    storageDataPath: /vm-data
```

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
vmcluster:
  enabled: true
vmsingle:
  enabled: false
```
