### ISSUE TITLE
bug: Problem with installing `victoria-metrics-k8s-stack` with templated CRD

### ISSUE THREAD

**Issue by tropnikovvl** [VictoriaMetrics/helm-charts#2041]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: latest

**Describe the bug**
When I try to install a chart with the following parameters (I want the CRD to be updated automatically along with the chart) I get an error

```bash
helm upgrade -i vm vm/victoria-metrics-k8s-stack -n default -f stack.yaml
```

> Error: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "vm-victoria-metrics-k8s-stack-cadvisor" namespace: "default" from "": no matches for kind "VMNodeScrape" in version "operator.victoriametrics.com/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "vm-victoria-metrics-k8s-stack-kubelet" namespace: "default" from "": no matches for kind "VMNodeScrape" in version "operator.victoriametrics.com/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "vm-victoria-metrics-k8s-stack-probes" namespace: "default" from "": no matches for kind "VMNodeScrape" in version "operator.victoriametrics.com/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "vm-victoria-metrics-k8s-stack-resources" namespace: "default" from "": no matches for kind "VMNodeScrape" in version "operator.victoriametrics.com/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "vm-victoria-metrics-operator" namespace: "default" from "": no matches for kind "VMServiceScrape" in version "operator.victoriametrics.com/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "vm-victoria-metrics-k8s-stack-core-dns" namespace: "default" from "": no matches for kind "VMServiceScrape" in version "operator.victoriametrics.com/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "vm-victoria-metrics-k8s-stack-kube-api-server" namespace: "default" from "": no matches for kind "VMServiceScrape" in version "operator.victoriametrics.com/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "vm-victoria-metrics-k8s-stack-kube-controller-manager" namespace: "default" from "": no matches for kind "VMServiceScrape" in version "operator.victoriametrics.com/v1beta1"
ensure CRDs are installed first]

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
victoria-metrics-operator:
  crds:
    plain: false

defaultDashboards:
  enabled: false

defaultRules:
  create: false

vmsingle:
  enabled: false

vmcluster:
  enabled: false

alertmanager:
  enabled: false

vmalert:
  enabled: false

vmauth:
  enabled: false

vmagent:
  enabled: false

grafana:
  enabled: false

prometheus-node-exporter:
  enabled: false

kube-state-metrics:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false
```

**Comment by AndrewChubatiuk** [comment]
I would recommend to install operator separately. helm has defined order in which it creates resources, but with CRDs as templates there's no guarantee that they are applied before CRs that depend on it

**Comment by tropnikovvl** [comment]
Have you thought about some kind of approach like this?

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: install-dependency
  annotations:
    "helm.sh/hook": pre-install
spec:
  template:
    spec:
      containers:
        - name: helm-install
          image: alpine/helm:latest
          command:
            - "sh"
            - "-c"
            - "helm upgrade --install dependency-chart ./charts/dependency-chart --namespace my-namespace"
      restartPolicy: Never
```
