### ISSUE TITLE
bug: Error creating Helm release

### ISSUE THREAD

**Issue by tropnikovvl** [VictoriaMetrics/helm-charts#2042]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: latest

**Describe the bug**
When trying to create a Helm release that will simultaneously have a CRD for the Prometheus operator and the Victoria operator, I get an error

> Error: create: failed to create: Secret "sh.helm.release.v1.vmo.v1" is invalid: data: Too long: may not be more than 1048576 bytes

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
victoria-metrics-operator:
  crds:
    plain: false

defaultDashboards:
  enabled: false

defaultRules:
  create: false

vmsingle:
  enabled: false

vmcluster:
  enabled: false

alertmanager:
  enabled: false

vmalert:
  enabled: false

vmauth:
  enabled: false

vmagent:
  enabled: false

grafana:
  enabled: false

prometheus-node-exporter:
  enabled: false

kube-state-metrics:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false

prometheus-operator-crds:
  enabled: true
```
