### ISSUE TITLE
bug: `api_version` Error When Using HTTP Sink type in victorialogs-single-server Helm Chart

### ISSUE THREAD

**Issue by Angel0r** [VictoriaMetrics/helm-charts#2043]
**Chart name and version**
chart: victoria-logs-single
version: v0.8.11

**Describe the bug**
Vector works fine with `sink.vlogs.type:elasticsearch`, however when I change the configuration to use `type: http` I get the following error:
`ERROR vector::cli: Configuration error. error=unknown field api_version`

**Custom values**
My configuration:
```yaml
        sinks:
          vlogs:
            inputs:
              - parser
            type: http
            uri: http://victorialogs-victoria-logs-single-server.vlogs.svc.cluster.local:9428/insert/jsonline
            compression: gzip
            encoding:
              codec: json
            framing:
              method: newline_delimited
            healthcheck:
              enabled: false
```
