### ISSUE TITLE
bug: victoria-metrics-agent AWS configuration issues

### ISSUE THREAD

**Issue by ctrlsam** [VictoriaMetrics/helm-charts#2047]
**Chart name and version**  
chart: victoria-metrics-agent  
version: 0.16.2

**Describe the bug**  
When configuring AWS remoteWrite using the official helm chart, the generated deployment includes an invalid flag. Instead of splitting the AWS configuration into separate flags (e.g. `--remoteWrite.aws.useSigv4` and `--remoteWrite.aws.region=ap-southeast-2`), the chart renders:  
```
--remoteWrite.aws=/config/rw/0-aws.yaml
```  
which causes vmagent v1.112.0 to error with:  
```
flag provided but not defined: -remoteWrite.aws
```  
This indicates that the chart is using an outdated file-based approach to configure AWS SigV4 options that the current vmagent binary no longer supports.

**Custom values**  
Below is an example values.yaml that reproduces the issue:

```yaml
fullnameOverride: vmagent
mode: deployment
replicaCount: 1

serviceAccount:
  create: true
  name: vmagent
  annotations:
    eks.amazonaws.com/role-arn: "<module.vmagent_irsa.iam_role_arn>"

remoteWrite:
  - url: "https://aps-workspaces.ap-southeast-2.amazonaws.com/workspaces/<redacted>/api/v1/remote_write"
    aws:
      useSigv4: true
      region: ap-southeast-2
```

**Additional context**  
- **Expected behavior:** The chart should render separate AWS flags (e.g. `--remoteWrite.aws.useSigv4` and `--remoteWrite.aws.region=ap-southeast-2`) so that vmagent v1.112.0 starts without error.  
- **Actual behavior:** The generated deployment passes a composite flag (`--remoteWrite.aws=/config/rw/0-aws.yaml`), resulting in the error:  
  ```
  flag provided but not defined: -remoteWrite.aws
  ```  
- **Generated deployment snippet:**  
  ```
  Args:
    --envflag.enable
    --envflag.prefix=VM_
    --httpListenAddr=:8429
    --loggerFormat=json
    --promscrape.config=/config/scrape/scrape.yml
    --remoteWrite.aws=/config/rw/0-aws.yaml
    --remoteWrite.tmpDataPath=/tmpData
    --remoteWrite.url=https://aps-workspaces.ap-southeast-2.amazonaws.com/workspaces/<redacted>/api/v1/remote_write
  ```  

**Steps to reproduce:**  
1. Deploy the chart with the above custom values.  
2. Observe that vmagent starts with the invalid AWS configuration flag.  
3. Check the logs to see the error:  
   ```
   flag provided but not defined: -remoteWrite.aws
   ```

**Comment by ctrlsam** [comment]
It works when the aws configuration is flattened, e.g.

```
remoteWrite:
  - url: "https://aps-workspaces.ap-southeast-2.amazonaws.com/workspaces/<redacted>/api/v1/remote_write"
    aws.region: ap-southeast-2
    aws.useSigv4: true
```
