### ISSUE TITLE
Restrict user on namespace using vmauth

### ISSUE THREAD

**Issue by Angel0r** [VictoriaMetrics/helm-charts#2050]
Hello,

I am using VictoriaLogs with Grafana and I want specific users to see the logs from only specific namespaces. This means that users can log in to the Grafana instance, and the victorialogs datasource will use basic authentication from the tenant, who will be restricted to a specific namespace.
Can this be done?

I am trying to configure this with vmauth, but I couldn't find a way. 
One of my tries was to use url_map and set `src_path` to a user which includes the query path.
```
    config:
      users:
        - username: "test"
          password: "test"
          url_map:
            - src_paths:
               - /select/logsql/query"?query=namespace:"test""
              url_prefix: "http://victorialogs-victoria-logs-single-server.vmauth-grafana-test.svc.cluster.local:9428"
```
 However, it seems like Grafana couldn't accept the src_path.

I also tried with Headers and X-Query-Filter but this didn't work as well.
```
          headers:
            - "X-Scope-OrgID: it"
            - "X-Query-Filter: {namespace='test'}"
```

/Angelos

**Comment by AndrewChubatiuk** [comment]
I'm not sure it's possible. You need to push data from this specific namespace to a separate tenant

**Comment by Angel0r** [comment]
Hey @AndrewChubatiuk,
Sorry for the late reply and thank you for the answer.
I tried to push the logs and filter them via Vector agent to a separate tenant as you said and it seems to work.
My Vector:
```
        data_dir: /vector-data-dir
        api:
          enabled: false
          address: 0.0.0.0:8686
          playground: true
        sources:
          k8s:
            type: kubernetes_logs
        transforms:
          parser:
            type: remap
            inputs: [k8s]
            source: |
              .log = parse_json(.message) ?? .message
              del(.message)
              .namespace = .kubernetes.pod_namespace
          filter_test1_namespace:
            type: filter
            inputs: [parser]
            condition: '.namespace == "test1" || .namespace == "test2"'
          filter_test2_namespace:
            type: filter
            inputs: [parser]
            condition: '.namespace == "test2"'
        sinks:
          vlogs_test1:
            type: elasticsearch
            inputs: [filter_test1_namespace]
            endpoints: << include "vlogs.es.urls" . >>
            mode: bulk
            api_version: v8
            compression: gzip
            healthcheck:
              enabled: false
            request:
              headers:
                VL-Time-Field: timestamp
                VL-Stream-Fields: stream,kubernetes.pod_name,kubernetes.container_name,kubernetes.pod_namespace
                VL-Msg-Field: message,msg,_msg,log.msg,log.message,log
                AccountID: "1"
                ProjectID: "0"
          vlogs_test2:
            type: elasticsearch
            inputs: [filter_test2_namespace]
            endpoints: << include "vlogs.es.urls" . >>
            mode: bulk
            api_version: v8
            compression: gzip
            healthcheck:
              enabled: false
            request:
              headers:
                VL-Time-Field: timestamp
                VL-Stream-Fields: stream,kubernetes.pod_name,kubernetes.container_name,kubernetes.pod_namespace
                VL-Msg-Field: message,msg,_msg,log.msg,log.message,log
                AccountID: "2"
                ProjectID: "0"
```
and vmauth:

```
    config:
      users:
        - username: "test1"
          password: "test1"
          url_map:
            - src_paths: ["/select/.*"]
              url_prefix: "http://victorialogs-victoria-logs-single-server.vmauth-grafana-test.svc.cluster.local:9428"
              headers:
                - "AccountID: 1"
                - "ProjectID: 0"
                # - "X-Scope-OrgID: it"
        - username: "test2"
          password: "test2"
          url_map:
            - src_paths: ["/select/.*"]
              url_prefix: "http://victorialogs-victoria-logs-single-server.vmauth-grafana-test.svc.cluster.local:9428"
              headers:
                - "AccountID: 2"
                - "ProjectID: 0"
```

Do you know if will get duplicate logs in VictoriaLogs since we send logs to different accounts?

Thank you!

/Angelos
