### ISSUE TITLE
bug: upgrading to `victoria-logs-single-0.9.3` causes `missing _msg field`

### ISSUE THREAD

**Issue by dhess** [VictoriaMetrics/helm-charts#2060]
**Chart name and version**
chart: victoria-logs-single
version: 0.9.3

**Describe the bug**
Since upgrading to `victoria-logs-single-0.9.3` from `0.9.2`, having made no other changes or updating any other components in our cluster, all logs are now of the form:

```
2025-03-14 20:14:44.000 missing _msg field; see https://docs.victoriametrics.com/victorialogs/keyconcepts/#message-field
```

Upon downgrading to `0.9.2`, and having made no other changes, normal operations are restored.

**Custom values**
```yaml
server:
  persistentVolume:
    enabled: true
    storageClassName: mayastor-pool-0-repl-2
    size: 500Gi
  serviceMonitor:
    enabled: true
    interval: 30s
  retentionDiskSpaceUsage: 500GiB

dashboards:
  enabled: true
  grafanaOperator:
    enabled: true
```
