### ISSUE TITLE
bug: urlRelabelConfig order

### ISSUE THREAD

**Issue by nevlkv** [VictoriaMetrics/helm-charts#2065]
**Chart name and version**
chart: victoria-metrics-agent
version: v0.16.2

**Describe the bug**

urlRelabelConfig defined in section 

```
remoteWrite:
  - url: http://<fqdn1>/insert/0/prometheus
  - url: http://<fqdn2>/insert/0/prometheus
  - url: http://<fqdn3>/insert/0/prometheus
  - url: http://vmsingle.io-vm.svc:8428/api/v1/write
    urlRelabelConfig:
      - source_labels: [__name__]
        regex: "(^world_.*_count$|kubelet_pod_ephemeral_storage_used_bytes|kubelet_pod_volumes_used_bytes|jvm_memory_bytes_used|^http_requests.*_total$)"
        action: keep

```

Applyed for first url

For define for 4th i'm need to set in sts 
```
77c77
<         - --remoteWrite.urlRelabelConfig=,,,/config/rw/3-urlRelabelConfig.yaml
---
>         - --remoteWrite.urlRelabelConfig=/config/rw/3-urlRelabelConfig.yaml
166c166
```
