### ISSUE TITLE
question: missing CPU/Mem metrics with k3s

### ISSUE THREAD

**Issue by lewandowskim1988** [VictoriaMetrics/helm-charts#2071]
## Configuration
In my home lab I deployed single node `k3s` cluster with following command
```
curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server" sh -s - --disable traefik
```

To be able to see CPU/Memory usage I installed `victoria-metrics-k8s-stack` with following `values.yaml` file
```
nameOverride: "vm"
fullnameOverride: "vm"
argocdReleaseOverride: "victoriametrics"
vmsingle:
  enabled: true
  spec:
    retentionPeriod: "60d"
    storage:
      accessModes:
        - ReadWriteOnce
      storageClassName: "openebs-lvmpv"
      resources:
        requests:
          storage: 20Gi
    resources:
      limits:
        cpu: 150m
        memory: 400Mi
      requests:
        cpu: 100m
        memory: 300Mi
alertmanager:
  enabled: false
vmalert:
  enabled: false
vmagent:
  spec:
    resources:
      limits:
        cpu: 50m
        memory: 150Mi
      requests:
        cpu: 40m
        memory: 120Mi
    scrapeInterval: 10s
    externalLabels:
      cluster: skynet
    inlineScrapeConfig: |
      - job_name: 'gpu'
        metrics_path: '/metrics'
        scheme: http
        static_configs:
          - targets: ['gpu-operator-metrics-exporter.gpu-operator.svc.cluster.local:5000']
grafana:
  enabled: true
  resources:
    requests:
      cpu: 200m
      memory: 250Mi
    limits:
      cpu: 250m
      memory: 300Mi
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    pathType: Prefix
    hosts:
      - monitoring.lewandowskim.com
    tls:
    - hosts:
      - monitoring.lewandowskim.com
      secretName: tls-wildcard-lewandowskim-com
  defaultDashboardsTimezone: cet
```
## Problem
When I go to `grafana` I am able to see metrics related to `vm-stack` and `node` but when I am checking pods all CPU/Mem graphs are blank with `No data` info

![Image](https://github.com/user-attachments/assets/00b36a3b-0b96-40e2-a554-eba8ae310bfb)

I check what is missing and it looks like there is no `container_*` related metrics like `container_cpu_usage_seconds_total` or `container_memory_working_set_bytes`

![Image](https://github.com/user-attachments/assets/aec95e54-5ed4-4068-80a3-f738b26deb65) 

Could you help me with resolving this issue?
