### ISSUE TITLE
bug: volume secretName reference for additional-notifier does not match the Secret's name

### ISSUE THREAD

**Issue by bincyber** [VictoriaMetrics/helm-charts#2075]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: 0.38.3

**Describe the bug**

When using `vmagent.additionalNotifierConfigs` to configure additional notifiers, the Secret name is created as `vmalert-monitoring-victoriametrics-vmks-additional-notifier`, but a different name is used when it's mounted as a volume:
```
  volumes:
    - name: vmalert-notifier-config
      secret:
        defaultMode: 420
        secretName: monitoring-victoriametrics-vmks-additional-notifier
```

`vm.managed.fullname` is used in [notifiers.yaml](https://github.com/VictoriaMetrics/helm-charts/blob/e3c4fc41d6b1fb7603c512b39ab25e99cd5ab3f0/charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/notifiers.yaml#L9), but in [_helpers.tpl](https://github.com/VictoriaMetrics/helm-charts/blob/e3c4fc41d6b1fb7603c512b39ab25e99cd5ab3f0/charts/victoria-metrics-k8s-stack/templates/_helpers.tpl#L60) `vm.fullname` is used

**Custom values**
```yaml
nameOverride: "vmks"
fullnameOverride: ""

vmalert:
  additionalNotifierConfigs:
    dns_sd_configs:
      - names:
          - alertmanager-operated.monitoring.svc.cluster.local
        type: 'A'
        port: 9093
```
