### ISSUE TITLE
bug: vmagent deployment broken because of empty remotewrite url

### ISSUE THREAD

**Issue by abaars** [VictoriaMetrics/helm-charts#2083]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: 0.39.1

**Describe the bug**
When updating the victoria-metrics-k8s-stack helm chart from 0.39.0 to 0.39.1 (or 0.39.2), the vmagent deployment fails with the message "_VMAgent.operator.victoriametrics.com "vm" is invalid: spec.remoteWrite[3].url: Required value (retried 5 times)._". 

When looking at the github version comparison between 0.39.0 and 0.39.1, we found one entry saying "_Add empty values to list args for remoteWrite. See [this issue](https://github.com/VictoriaMetrics/helm-charts/issues/2065)._" (from https://github.com/VictoriaMetrics/helm-charts/compare/victoria-metrics-k8s-stack-0.39.0...victoria-metrics-k8s-stack-0.39.1).

**Custom values**
Please provide only custom values (excluding default ones):
The spec in version 0.39.0:
```yaml
remoteWrite:
	- tlsConfig:
		insecureSkipVerify: true
	  url: https://some-remote-write/api/v1/write
	- tlsConfig:
		insecureSkipVerify: true
	  url: https://some-remote-write/api/v1/write
	- tlsConfig:
		insecureSkipVerify: true
	  url: https://some-remote-write/api/v1/write
```

The spec from 0.39.1:
```yaml
remoteWrite:
	- tlsConfig:
		insecureSkipVerify: true
	  url: https://some-remote-write/api/v1/write
	- tlsConfig:
		insecureSkipVerify: true
	  url: https://some-remote-write/api/v1/write
	- tlsConfig:
		insecureSkipVerify: true
	  url: https://some-remote-write/api/v1/write
	- {}
```

**Comment by AndrewChubatiuk** [comment]
hey @abaars 
could you please share your custom values, that you're using for k8s-stack chart?

**Comment by abaars** [comment]
Hi Andrew, sure. These are the custom values we use for vmagent in the victoria-metrics-k8s-stack helm chart:
```yaml
vmagent:
  additionalRemoteWrites:
      - url: https://some-remote-write/api/v1/write
        tlsConfig:
          insecureSkipVerify: true
      - url: https://some-remote-write/api/v1/write
        tlsConfig:
          insecureSkipVerify: true
      - url: https://some-remote-write/api/v1/write
        tlsConfig:
          insecureSkipVerify: true
  spec:
    additionalScrapeConfigs:
      name: additional-scrape-configs
      key: additional-metrics.yaml
    remoteWriteSettings:
      queues: 8
      showURL: true
    shardCount: 1
    replicaCount: 1
    selectAllByDefault: true
    extraArgs:
      promscrape.maxScrapeSize: "256MiB"
      promscrape.suppressDuplicateScrapeTargetErrors: "true"
      promscrape.suppressScrapeErrors: "true"
    volumes:
      - name: etcd-certs
        secret:
          secretName: etcd-certificates
    volumeMounts:
      - name: etcd-certs
        readOnly: true
        mountPath: "/etcd-certs"
    resources:
      limits:
        memory: 3Gi
      requests:
        memory: 128Mi
        cpu: "0.1"
    inlineRelabelConfig:
      - source_labels: [cluster]
        target_label: exported_cluster
      - target_label: cluster
        replacement: clustername
      - target_label: dc_name
        replacement: dc_name
    serviceScrapeRelabelTemplate:
      - source_labels: [__meta_kubernetes_pod_annotation_tenant_id]
        target_label: __tenant_id__
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node_name
    podScrapeRelabelTemplate:
      - source_labels: [__meta_kubernetes_pod_annotation_tenant_id]
        target_label: __tenant_id__
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node_name
    nodeScrapeRelabelTemplate:
      - source_labels: [__meta_kubernetes_pod_annotation_tenant_id]
        target_label: __tenant_id__
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node_name
    probeScrapeRelabelTemplate:
      - source_labels: [__meta_kubernetes_pod_annotation_tenant_id]
        target_label: __tenant_id__
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node_name
    staticScrapeRelabelTemplate:
      - source_labels: [__meta_kubernetes_pod_annotation_tenant_id]
        target_label: __tenant_id__
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node_name
```
