### ISSUE TITLE
question: add the ability to change serviceSpec (not only ingress) in k8s-stack

### ISSUE THREAD

**Issue by yuvalavidor** [VictoriaMetrics/helm-charts#2091]
**Chart name and version, where you feel a lack of requested feature**
chart: victoria-metrics-k8s-stack
version: v0.39.4

**Is your feature request related to a problem? Please describe.**
I wouldnt say its a problem, but I want to be able to add/change annotations for the services the VMcluster CRD is creating, specifically vminsert so i can create a NLB using a loadBalancer service and the AWS controller

**Describe the solution you'd like**
I would like to see something like:
```
vmcluster:
    vminsert:
       serviceSpec:
          type:
          extraAnnotations
```

**Comment by AndrewChubatiuk** [comment]
as it's mentioned in docs for [chart's vmcluster.spec param](https://docs.victoriametrics.com/helm/victoriametrics-k8s-stack/) you can get a list of all available for `vmcluster.spec` params [here](https://docs.victoriametrics.com/operator/api/index.html#vmclusterspec). annotations for vminsert can be added using this config
```
vmcluster:
  spec:
    vminsert:
      serviceSpec:
        metadata:
          annotations:
            some-key: some-value
```
