### ISSUE TITLE
feature: Possibility to set datasource for `external.alert.source`

### ISSUE THREAD

**Issue by tropnikovvl** [VictoriaMetrics/helm-charts#2092]
**Chart name and version, where you feel a lack of requested feature**
chart: victoria-metrics-k8s-stack
version: latest

**Is your feature request related to a problem? Please describe.**
It would be great to be able to give a different name to the datasource that is in the external grafana. At the moment it is hardcoded.
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/templates/_helpers.tpl#L146

**Describe the solution you'd like**
It would be logical to add the datasource name here

```yaml
external:
  grafana:
    host: ""
    datasource: my-custom-datasource-name
```
