### ISSUE TITLE
bug: k8s-stack - dashboard: `k8s_views_nodes` expression error

### ISSUE THREAD

**Issue by aorith** [VictoriaMetrics/helm-charts#2100]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: `v0.41.0`

**Describe the bug**
The grafana dashboard `uid: k8s_views_nodes` contains a variable "`instance`" with the following query:

```
label_values(node_uname_info{nodename=~"(?i:($node)(\.[a-z0-9.]+)?)"}, instance)
```

That query breaks with this error:

```
ERROR: 422, error when executing query="label_values(node_uname_info{nodename=~\"(?i:($node)(\\.[a-z0-9.]+)?)\"}, instance)" for (time=1743665954084, step=1800000): cannot expand WITH expressions: cannot parse string literal "\"(?i:($node)(\\.[a-z0-9.]+)?)\"": invalid syntax
```

**Custom values**
```yaml
    grafana:
      enabled: false
      forceDeployDatasource: false

    defaultDashboards:
      grafanaOperator:
        enabled: true
```
