### ISSUE TITLE
question: field templates already set in type config.plain

### ISSUE THREAD

**Issue by patsevanton** [VictoriaMetrics/helm-charts#2101]
**Chart name and version**
chart: `victoria-metrics-k8s-stack`
version: v0.30.3

**Describe the bug**
After update to `0.41.0` version i have error:
```
/etc/alertmanager/config/alertmanager.yaml","err":"yaml: unmarshal errors:\n  line 65: field templates already set in type config.plain
```

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: victoria-metrics
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.30.3
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: victoria-metrics
  values:
    alertmanager:
      enabled: true
      monzoTemplate:
        enabled: false
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - alertmanager.k8s.dev.corp
        annotations:
          cert-manager.io/cluster-issuer: "cluster-issuer"
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
        tls:
          - hosts:
              - alertmanager.k8s.dev.corp
            secretName: alertmanager-tls
      spec:
        image:
          repository: harbor.corp/dockerhub/prom/alertmanager
        logFormat: json
        logLevel: debug
        # [xxxx-1739] Add webhooks to Grafana Oncall
        secrets:
          - grafana-oncall-webhook
        # Add message templates as ConfigMap
        configMaps:
          - alertmanager-templates
      config:
        global:
          resolve_timeout: 5m
        time_intervals:
          - name: business-hours
            time_intervals:
              - location: Europe/Moscow
                times:
                  - start_time: "08:00"
                    end_time: "23:00"
        receivers:
          - name: "null"
          - name: prometheus-mattermost-infra-critical
            slack_configs:
              - send_resolved: true
                api_url: "https://mattermost.dev.platform.md.corp.xx/hooks/xxxx"
                channel: "#alerts-core-infra-critical"
                icon_url: https://avatars3.githubusercontent.com/u/3380462
                color: '{{ template "mm.color" . }}'
                title: '{{ template "mm.title" . }}'
                text: '{{ template "mm.text" . }}'
                username: "alertmanager"
          # Grafana Oncall Receivers
          - name: grafana-oncall
            webhook_configs:
              - url_file: "/etc/vm/secrets/grafana-oncall-webhook/oncall-webhook"
                send_resolved: true
          - name: grafana-oncall-heartbeat
            webhook_configs:
              - url_file: "/etc/vm/secrets/grafana-oncall-webhook/oncall-heartbeat"
          - name: element-infra-critical
            webhook_configs:
              - url: "https://webhook-gateway.dev.platform.md.corp.xx/v1/webhook/alertmanager/send?webhookID=xxxx"
                send_resolved: true
        route:
          group_by: ["job"]
          group_interval: 5m
          group_wait: 30s
          receiver: "null"
          repeat_interval: 12h
          routes:
            # Mattermost integration
            - receiver: prometheus-mattermost-infra-critical
              matchers:
                - severity="infra-critical"
              group_wait: 10s
              continue: true
            # Element integration
            - receiver: element-infra-critical
              matchers:
                - severity="infra-critical"
              group_wait: 10s
              continue: true
            # Grafana Oncall integration
            - receiver: grafana-oncall
              matchers:
                - severity=~"critical|infra-critical"
                - teams="core-devops"
              group_wait: 10s
              continue: true
            - receiver: grafana-oncall-heartbeat
              matchers:
                - alertname="heartbeat"
              group_wait: 0s
              group_interval: 1m
              repeat_interval: 50s
        templates:
          - "/etc/vm/configs/**/*.tmpl"
```

and ConfigMap alertmanager-templates
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
  namespace: victoria-metrics
data:
  telegram_message.tmpl: |-
    {{ define "telegram.custom.message" }}
    {{ if gt (len .Alerts.Firing) 0 }}
    🚨*Alerts Firing*🔥:
    {{ range .Alerts.Firing }}
    *{{ .Labels.alertname }}*
    *Severity:* {{ .Labels.severity }}
    *Site:* {{ .Labels.site }}

    *Annotations:*
    {{ range .Annotations.SortedPairs -}}
    • *{{ .Name }}:* `{{ .Value }}`
    {{ end }}
    {{ end }}
    {{ end }}
    {{ if gt (len .Alerts.Resolved) 0 }}
    ✅*Alerts Resolved*✅:
    {{ range .Alerts.Resolved }}
    *{{ .Annotations.description }} resolved*
    *Severity:* {{ .Labels.severity }}
    *Site:* {{ .Labels.site }}

    *Annotations:*{{ range .Annotations.SortedPairs }}{{if ne .Name "description"}}• *{{ .Name }}:* `{{ .Value }}`{{ end }}
    {{ end }}
    {{ end }}
    {{ end }}
    {{ end }}
  mattermost.tmpl: |-
    {{ define "__alert_silence_link" -}}
        {{ .ExternalURL }}/#/silences/new?filter=%7B
        {{- range .CommonLabels.SortedPairs -}}
            {{- if ne .Name "alertname" -}}
                {{- .Name }}%3D"{{- .Value -}}"%2C%20
            {{- end -}}
        {{- end -}}
        alertname%3D"{{- .CommonLabels.alertname -}}"%7D
    {{- end }}

    {{/* Severity of the alert */}}
    {{ define "__alert_severity" -}}
        {{- if eq .CommonLabels.severity "critical" -}}
        *Severity:* `Critical`
        {{- else if eq .CommonLabels.severity "warning" -}}
        *Severity:* `Warning`
        {{- else if eq .CommonLabels.severity "info" -}}
        *Severity:* `Info`
        {{- else -}}
        *Severity:* :question: {{ .CommonLabels.severity }}
        {{- end }}
    {{- end }}

    {{/* Title of the MM alert */}}
    {{ define "mm.title" -}}
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
    {{- end }}

    {{/* Color of mm attachment (appears as line next to alert )*/}}
    {{ define "mm.color" -}}
        {{ if eq .Status "firing" -}}
            {{ if eq .CommonLabels.severity "warning" -}}
                warning
            {{- else if eq .CommonLabels.severity "critical" -}}
                danger
            {{- else -}}
                #439FE0
            {{- end -}}
        {{ else -}}
        good
        {{- end }}
    {{- end }}

    {{/* The text to display in the alert */}}
    {{ define "mm.text" -}}
        {{ range .Alerts -}}
        *Alert:* {{ .Labels.alertname }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
        *Labels:*
          {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
        *Annotations:*
          {{ range .Annotations.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
        {{- end }}
    {{- end }}
```

how fixed ?

**Comment by AndrewChubatiuk** [comment]
templates should be set using .[Values.alertmanager.spec.templates](https://docs.victoriametrics.com/operator/api/#vmalertmanagerspec-templates)

**Comment by AndrewChubatiuk** [comment]
it's not related to k8s-stack or operator upgrade, looks like changes in alertmanager configuration validation. `Values.alertmanager.spec.templates` property support was added long time ago and we never recommended using .Values.alertmanager.config.templates

**Comment by patsevanton** [comment]
I found the version when the error appears: from version `victoria-metrics-k8s-stack` 0.38.3 to version `victoria-metrics-k8s-stack` 0.39.0

**Comment by patsevanton** [comment]
I change value and upgrade HelmRelease :
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: victoria-metrics
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.39.0
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: victoria-metrics
  values:
    alertmanager:
      spec:
        secrets:
          - grafana-oncall-webhook
        configMaps:
          - alertmanager-templates
      config:
#        templates:
#          - "/etc/vm/configs/**/*.tmpl"
        templates:
          - name: alertmanager-templates
            key: telegram_message.tmpl
          - name: alertmanager-templates
            key: mattermost.tmpl
```

and get error:
```
vmalertmanager-victoria-metrics-k8s-stack-0 alertmanager {"caller":"coordinator.go:118","component":"configuration","err":"yaml: unmarshal errors:\n  line 57: cannot unmarshal !!map into string\n  line 59: cannot unmarshal !!map into string\n  line 68: field templates already set in type config.plain","file":"/etc/alertmanager/config/alertmanager.yaml","level":"error","msg":"Loading configuration file failed","ts":"2025-04-04T06:23:13.116Z"}
```

**Comment by AndrewChubatiuk** [comment]
operator never relied on .Value.alertmanager.config.templates. Old alertmanager version could tolerate invalid yaml, that has two `templates` sections (default one is injected by operator). The only valid option to set templates is `Value.alertmanager.spec.templates`

**Comment by patsevanton** [comment]
I tested in different version victoria-metrics-k8s-stack
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: victoria-metrics
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.36.2
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: victoria-metrics
  values:
    alertmanager:
      enabled: true
      monzoTemplate:
        enabled: false
      spec:
        image:
          repository: harbor.corp/dockerhub/prom/alertmanager
        secrets:
          - grafana-oncall-webhook
        configMaps:
          - alertmanager-templates
        templates:
          - name: alertmanager-templates
            key: telegram_message.tmpl
          - name: alertmanager-templates
            key: mattermost.tmpl
```

but secret old:
```
kubectl get secrets -n victoria-metrics vmalertmanager-victoria-metrics-k8s-stack-config -o jsonpath='{.data.alertmanager\.yaml}' | base64 --decode | grep templates -A 3
templates:
  - "/etc/vm/configs/**/*.tmpl"
```

**Comment by f41gh7** [comment]
> How check/valid HelmRelease ? may be change version ?

 Looks like helm chart overwrite `spec.templates` value with generated content:
https://github.com/VictoriaMetrics/helm-charts/blob/ea19b7724edda9a7688ad5f8bcf50e5b9a4a7327/charts/victoria-metrics-k8s-stack/templates/_helpers.tpl#L252
```
{{- $templates := default list -}}
  {{- if $Values.alertmanager.monzoTemplate.enabled -}}
    {{- $configMap := printf "%s-monzo-tpl" $fullname -}}
    {{- $templates = append $templates (dict "name" $configMap "key" "monzo.tmpl") -}}
  {{- end -}}
  {{- $configMap := printf "%s-extra-tpl" $fullname -}}
  {{- range $key, $value := $Values.alertmanager.templateFiles | default dict -}}
    {{- $templates = append $templates (dict "name" $configMap "key" $key) -}}
  {{- end -}}
  {{- if and ($app.useManagedConfig) (not (hasKey $spec "disableNamespaceMatcher")) }}
    {{- $_ := set $spec "disableNamespaceMatcher" true }}
  {{- end }}
  {{- $_ := set $spec "templates" $templates -}}
  {{- toYaml $spec -}}
```

 Looks like bug to me @AndrewChubatiuk

**Comment by f41gh7** [comment]
@patsevanton  I think, you can just remove from your original helmFile given line:

```
        templates:
          - "/etc/vm/configs/**/*.tmpl"
 ```

 It's already unconditionally added by helm chart to the configuration:
https://github.com/VictoriaMetrics/helm-charts/blob/ea19b7724edda9a7688ad5f8bcf50e5b9a4a7327/charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/vmalertmanager.yaml#L30

**Comment by AndrewChubatiuk** [comment]
> Looks like bug to me
Right, released chart 0.41.3, where monzo and extra templates are appended to ones defined in `.Values.alertmanager.spec.templates`

**Comment by patsevanton** [comment]
Work! Thanks!
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: victoria-metrics
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.41.3
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: victoria-metrics
  values:
    alertmanager:
      enabled: true
      spec:
        image:
          repository: harbor.corp/dockerhub/prom/alertmanager
        logFormat: json
        logLevel: debug
        secrets:
          - grafana-oncall-webhook
        configMaps:
          - alertmanager-templates
        templates:
          - name: alertmanager-templates
            key: telegram_message.tmpl
          - name: alertmanager-templates
            key: mattermost.tmpl
```
