### ISSUE TITLE
feature: ability to add extra ports to victoria-logs-single service

### ISSUE THREAD

**Issue by cathelijne** [VictoriaMetrics/helm-charts#2111]
**Chart name and version, where you feel a lack of requested feature**
chart: victoria-logs-single
version: v0.9.3

**Is your feature request related to a problem? Please describe.**
Victoria Logs allows me to run as a remote syslog server by adding ports 514 for TCP and UDP respectively to the server args, as described [here](https://docs.victoriametrics.com/victorialogs/data-ingestion/syslog/).

In the values.yaml for the helm chart, I can add extraArgs for the server, i.e.

```
          extraArgs:
            envflag.enable: true
            envflag.prefix: VM_
            httpListenAddr: :9428
            loggerFormat: json
            syslog.listenAddr.tcp: :514
            syslog.listenAddr.udp: :514
```
and add the capabilities to the pod:
```
          securityContext:
            capabilities:
              add:
                - CAP_NET_BIND_SERVICE
              drop:
                - ALL
            enabled: true
            readOnlyRootFilesystem: true
```
But what I _can't_ do is add the syslog ports to the service. The [values](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-logs-single/values.yaml) (currently starting at line 268) file gives me these options:
```
  service:
    # -- Service annotations
    annotations: {}
    # -- Service labels
    labels: {}
    # -- Service ClusterIP
    clusterIP: None
    # -- Service external IPs. Details are [here]( https://kubernetes.io/docs/user-guide/services/#external-ips)
    externalIPs: []
    # -- Service load balancer IP
    loadBalancerIP: ""
    # -- Load balancer source range
    loadBalancerSourceRanges: []
    # -- Target port
    targetPort: http
    # -- Service port
    servicePort: 9428
    # -- Node port
    # nodePort: 30000
    # -- Service type
    type: ClusterIP
    # -- Service external traffic policy. Check [here](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip) for details
    externalTrafficPolicy: ""
    # -- Health check node port for a service. Check [here](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip) for details
    healthCheckNodePort: ""
    # -- Service IP family policy. Check [here](https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services) for details.
    ipFamilyPolicy: ""
    # -- List of service IP families. Check [here](https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services) for details.
    ipFamilies: []
```
and checking the [template file for the service](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-logs-single/templates/server-service.yaml) indeed shows that there's a service with just this single port.

**Describe the solution you'd like**
Given that I can describe a service with multiple ports in a manifest like this:
```
apiVersion: v1
kind: Service
metadata:
  name: victoria-logs-single
spec:
  ports:
  - name: http
    port: 9428
    targetPort: 9428
  - name: syslog-tcp
    port: 514
    targetPort: 514    
  - name: syslog-udp
    port: 514
    targetPort: 514
    protocol: UDP
  selector:
    app: victoria-logs-single
  type: LoadBalancer
```
it would be nice if the chart would let me set up a service with multiple ports for this otherwise supported configuration. Helm templating supports looping over a range.

**Describe alternatives you've considered**
For now I'll deploy an extra service alongside the main application. It's not hard to do, but I'll miss the possibility to use templated fields for my service.

**Comment by AndrewChubatiuk** [comment]
hey @cathelijne
added .Values.service.extraPorts to release 0.9.4

**Comment by cathelijne** [comment]
Wow. That was fast. Thank you!

**Comment by cathelijne** [comment]
Just one more comment for future visitors coming here via a search engine to confirm that this works beautifully. 
I just came home and renovate had already picked up the new version. Removed my manually applied service, edited the values like so:
```
            service:
              annotations:
                metallb.universe.tf/loadBalancerIPs: 192.168.2.222
                metallb.universe.tf/allow-shared-ip: monitoring
              targetPort: http
              servicePort: 9428
              type: LoadBalancer
              clusterIP: ""
              extraPorts:
                - name: syslog
                  port: 514
                  protocol: TCP
                  targetPort: syslog
                - name: syslog-udp
                  port: 514
                  protocol: UDP
                  targetPort: syslog-udp
```
_(for those of you copying/pasting, mind the indentation, my values are included in argocd apps and quite a few spaces to the right from normal values files)_
Applied and boom! Worked first try.
