### ISSUE TITLE
bug: vminsert_streamagg_config_last_reload_successful == 0

### ISSUE THREAD

**Issue by ndevenish** [VictoriaMetrics/helm-charts#2119]
**Chart name and version**
chart: victoria-metrics-single
version: 0.17.0

**Describe the bug**
My VM instance has a time series called `vminsert_streamagg_config_last_reload_successful` which is set to zero. This shows up on a generic "*_last_reload_successful" catching reload alert.

I'd like to know if this is something I've done wrong in my configuration or a way to resolve it, or if I have to craft the rules around specifically excluding this value?

**Custom values**
Please provide only custom values (excluding default ones):
```yamlvictoria-metrics-single:
  rbac:
    create: false

  serviceAccount:
    create: false

  server:
    retentionPeriod: 2y
    ingress:
      enabled: true
      hosts:
        - name: "mx-analysis-prometheus.diamond.ac.uk"
          path: "/"
    resources:
      requests:
        cpu: 1000m
      limits:
        cpu: 4000m

    scrape:
      enabled: true
      configMap: mxa-prometheus-targets

    extraArgs:
      promscrape.configCheckInterval: 60s
      selfScrapeInterval: 60s
      vmalert.proxyURL: http://mxa-victoria-metrics-alert-server.mx-analysis.svc.cluster.local:8880/vmalert

```
