### ISSUE TITLE
bug: vmcluster version label does not match clusterVersion

### ISSUE THREAD

**Issue by dctrwatson** [VictoriaMetrics/helm-charts#2120]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.42.0

**Describe the bug**
The `app.kubernetes.io/version` label on the VMCluster CR does not match the `clusterVersion` of the CR.

VMAgent, VMAlert, etc CRs have standardized `spec.image.tag` so they work as expected.

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
vmcluster:
  spec:
    clusterVersion: v1.114.0
```
