### ISSUE TITLE
bug: Set wildcard for vminsert.ingress.hosts.name

### ISSUE THREAD

**Issue by Kislaci90** [VictoriaMetrics/helm-charts#2134]
**Chart name and version**
chart: victoria-metrics-cluster
version: v0.19.4

**Describe the bug**
I can not leave it empty or set a wildcard for the vminsert ingress hosts.name. 
If it's empty, I get this error:
 template: victoria-metrics-cluster/templates/ingress.yaml:28:24: executing "victoria-metrics-cluster/templates/ingress.yaml" at <$host.name>: wrong type for value; expected string; got interface {}
If I set "*", I get this error:
Error: YAML parse error on victoria-metrics-cluster/templates/ingress.yaml: error converting YAML to JSON: yaml: line 22: did not find expected alphabetic or numeric character

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
vminsert:
  ingress:
    hosts:
      - name: "*"
        path:
          - "/remote_write(/|$)(.*)"
        port: http
```

```yaml
vminsert:
  ingress:
    hosts:
      - path:
          - "/remote_write(/|$)(.*)"
        port: http
```
