### ISSUE TITLE
bug: missing cadvisor metrics in VMsingle although scraped by VMagent

### ISSUE THREAD

**Issue by muhlba91** [VictoriaMetrics/helm-charts#2155]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.44.0
kubernetes: 1.32.3 (Talos, single-node)

**Describe the bug**
Although VMagent scrapes the cadvisor endpoint correctly, I don't have metrics related to cadvisor in VMsingle.

For example, `container_cpu_usage_seconds_total` which is a cadvisor metric is not found in VMsingle.

The endpoint and auth token used by VMagent is correct. If I use the same data to query the endpoint, I receive those metrics without problems.

I can see in VMagent that the target is healthy and I can find the VMScrapeConfig which has the correct endpoint and path to the service account token.

It also looks like VMagent scrapes correctly as the sample size is shown as 23790.

One example metric is `container_cpu_usage_seconds_total{container="worker",cpu="total",id="/kubepods/besteffort/pod16a9385f-72dd-480d-a839-87b8c6ec8943/f2fa9a0c4fb984bffeac50bdfd0f3083cf723c668cc3ebaae9fe501dfdcd75a3",image="registry.k8s.io/nfd/node-feature-discovery:v0.15.3",name="f2fa9a0c4fb984bffeac50bdfd0f3083cf723c668cc3ebaae9fe501dfdcd75a3",namespace="nvidia-device-plugin",pod="nvidia-device-plugin-node-feature-discovery-worker-w9tmv"} 2259.971068 1745756770975`

The job configuration is:
```
- job_name: nodeScrape/victoria-metrics/victoria-metrics-cadvisor/0
  scrape_interval: 1m0s
  scrape_timeout: 5s
  metrics_path: /metrics/cadvisor
  honor_labels: true
  scheme: https
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_node_name]
    target_label: node
  - target_label: job
    replacement: victoria-metrics/victoria-metrics-cadvisor
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - source_labels: [__metrics_path__]
    target_label: metrics_path
  - target_label: job
    replacement: kubelet
  metric_relabel_configs:
  - action: labeldrop
    regex: (uid)
  - action: labeldrop
    regex: (id|name)
  - action: drop
    source_labels: [__name__]
    regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
  kubernetes_sd_configs:
  - role: node
```

**Custom values**
Default regarding `kubelet`.

**Comment by zekker6** [comment]
> What are the implications of increasing the maxLabelsPerTimeseries option, or is the recommendation to drop labels instead?

It is recommended to drop all labels which are not actually used when querying the data in order to reduce resource footprint. `maxLabelsPerTimeseries` default limit is 50 labels which usually suits most use-cases where all the labels are actually in use.
Having more labels in metrics will mean that more data is stored in database index. If these labels are static (both label names and values) it should not be a problem, otherwise it will lead to having [high churn rate](https://docs.victoriametrics.com/victoriametrics/faq/#what-is-high-churn-rate) and thus degraded performance over time.

In this specific case it looks like kubernetes node feature labels are hitting the limit, so if those labels are not used it is better to drop those with [relabeling](https://docs.victoriametrics.com/victoriametrics/relabeling/#how-to-remove-labels-from-scraped-metrics).

**Comment by P-n-I** [comment]
For the hassled and rushed among us:
```
kubelet:
  vmScrape:
    spec:
      metricRelabelConfigs:
        - action: labeldrop
          regex: (uid)
        - action: labeldrop
          regex: (id|name)
        - action: drop
          source_labels: [__name__]
          regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
        # Kubevirt adds a lot of labels to the nodes
        - action: labeldrop
          regex: (.*kubevirt.*)
```
because kubevirt adds a lot of labels to nodes.
