### ISSUE TITLE
How set priorityClassName for deploy,sts for victoria-metrics

### ISSUE THREAD

**Issue by patsevanton** [VictoriaMetrics/helm-charts#2157]
Hello! How set priorityClassName for deploy,sts for victoria-metrics ? 

version:
```
helm list -n  victoria-metrics
NAME                      	NAMESPACE       	REVISION	UPDATED                                	STATUS  	CHART                            APP VERSION
victoria-metrics-k8s-stack	victoria-metrics	102     	2025-04-16 12:57:30.843154534 +0000 UTC	deployed	victoria-metrics-k8s-stack-0.41.3v1.114.0   
```

get priorityClassName for deploy,sts,ds:
```
kubectl get deploy,sts,ds -n victoria-metrics -o custom-columns="NAME:.metadata.name,TYPE:.kind,PRIORITY_CLASS:.spec.template.spec.priorityClassName"
NAME                                                   TYPE          PRIORITY_CLASS
victoria-metrics-k8s-stack-kube-state-metrics          Deployment    <none>
victoria-metrics-k8s-stack-victoria-metrics-operator   Deployment    <none>
vmagent-victoria-metrics-k8s-stack                     Deployment    <none>
vmalert-victoria-metrics-k8s-stack                     Deployment    <none>
vminsert-victoria-metrics-k8s-stack                    Deployment    <none>
vmalertmanager-victoria-metrics-k8s-stack              StatefulSet   <none>
vmselect-victoria-metrics-k8s-stack                    StatefulSet   <none>
vmstorage-victoria-metrics-k8s-stack                   StatefulSet   <none>
victoria-metrics-k8s-stack-prometheus-node-exporter    DaemonSet     <none>

```

**Comment by AndrewChubatiuk** [comment]
there's no option to set it globally for all chart resources, you need to set it per CR: `vmcluster.spec.vminsert.priorityClassName`, `vmcluster.spec.vmselect.priorityClassName`, `vmagent.spec.priorityClassName`, `vmalert.spec.priorityClassName`, `alertmanager.spec.priorityClassName`, `vmauth.spec.priorityClassName`, etc. Parameters for all managed by vm operator CRs are available [here](https://docs.victoriametrics.com/operator/api). for kube-state-metrics, node-exporter, grafana, etc please check respective subchart docs.

**Comment by patsevanton** [comment]
Thank you. I'll test it.

**Comment by patsevanton** [comment]
Thanks!
```
victoria-metrics-operator:
  priorityClassName: high
vmcluster:
  spec:
    vmstorage:
      priorityClassName: high
    vmselect:
      priorityClassName: high
    vminsert:
      priorityClassName: high
alertmanager:
  spec:
    priorityClassName: high
vmalert:
  spec:
    priorityClassName: high
vmagent:
  spec:
    priorityClassName: high
prometheus-node-exporter:
  priorityClassName: high
kube-state-metrics:
  priorityClassName: high
```
