### ISSUE TITLE
bug: distributed, name is vmagent-zone-1a but nodeSelector is vmagent-zone-1b

### ISSUE THREAD

**Issue by east4ming** [VictoriaMetrics/helm-charts#2158]
**Chart name and version**
chart: victoria-metrics-distributedr
version: v0.13.2

**Describe the bug**
Use argocd to deploy helm chart. It was found that one of the deploy configurations of vmagent was abnormal, specifically manifested as: name is vmagent-zone-1a but nodeSelector is vmagent-zone-1b

**Custom values**
Please provide only custom values (excluding default ones):

The first time, my configuration is as follows, resulting in this issue

```yaml
zoneTpl:
  common:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
availabilityZones:
  - name: ap-southeast-1a
  - name: ap-southeast-1b
```

The second time, after adjusting my configuration as follows, the issue was not resolved

```yaml
zoneTpl:
  common:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
  vmagent:
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: "{{ (.zone).name }}"
availabilityZones:
  - name: ap-southeast-1a
  - name: ap-southeast-1b
```

My Deployment  vm-xxx-1a final yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vmagent-ap-southeast-1a
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: vmagent-ap-southeast-1a
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vmagent
    app.kubernetes.io/version: v1.115.0
    argocd.argoproj.io/instance: vm
    helm.sh/chart: victoria-metrics-distributed-0.13.2
    managed-by: vm-operator
  name: vmagent-vmagent-ap-southeast-1a
  namespace: vm
spec:
  ...
  template:
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: ap-southeast-1b
```
