### ISSUE TITLE
bug: Overriding vmauth unauthorizedUserAccessSpec options is not working

### ISSUE THREAD

**Issue by neethu-p** [VictoriaMetrics/helm-charts#2167]
**Chart name and version**
chart: victoria-metrics-distributed
version: v0.14.0

**Describe the bug**
## Bug Report

We are trying to override the `unauthorizedUserAccessSpec` for global VMAuth read and write.

Even though we specify a custom `url_map` block like below in the Helm `values.yaml`, The deployed configuration still reflects the default path values (/api/v1/write, /prometheus/api/v1/write, etc.) — not our override.

**Custom values**
vmauth-global-write
```yaml
write:
  global:
    vmauth:
     spec:
      unauthorizedUserAccessSpec:
        url_map:
          - src_paths:
              - /insert/.+/prometheus
            url_prefix:
              - http://vmagent-vmagent-eu-north-1a.victoria-metrics.svc.cluster.local.:8429
              - http://vmagent-vmagent-eu-north-1b.victoria-metrics.svc.cluster.local.:8429
```
