### ISSUE TITLE
bug: Grafana built-in core data sources are excluded from extra data sources

### ISSUE THREAD

**Issue by dctrwatson** [VictoriaMetrics/helm-charts#2185]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.47.1

**Describe the bug**
Of the list of [built-in core data sources](https://grafana.com/docs/grafana/latest/datasources/#built-in-core-data-sources) only `prometheus` and `alertmanager` will be included from `defaultDatasources.extra`.

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
defaultDatasources:
  extra:
    - name: loki
      access: proxy
      editable: false
      isDefault: false
      type: loki
      url: https://loki-distributed-query-frontend.loki.svc.cluster.local.:3100

    - name: cloudwatch
      access: proxy
      editable: false
      isDefault: false
      type: cloudwatch
```
