### ISSUE TITLE
feature: vmauth support user password from secret

### ISSUE THREAD

**Issue by YuryHrytsuk** [VictoriaMetrics/helm-charts#2213]
**Chart name and version, where you feel a lack of requested feature**
chart: victoria-metrics-auth
version: 0.15.0

**Is your feature request related to a problem? Please describe.**
I am configuring vmauth in front of victoria logs single cluster. I want to configure user password value from secret

**Describe the solution you'd like**
```yaml
config:
  users:
    - username: my-user
      password:
        secretKeyRef:
          name: victoria-logs-user-password
          key: password
      url_prefix: http://victoria-logs-victoria-logs-single-server.{{ .Release.Namespace }}.svc.cluster.local:9428/

extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: victoria-logs-user-password
      namespace: {{ .Release.Namespace }}
    type: Opaque
    data:
      password: {{ requiredEnv "SERVICES_PASSWORD" | b64enc }}
```

**Describe alternatives you've considered**
Working alternative is to use password directly, i.e.

```yaml
config:
  users:
    - username: my-user
      password: {{ requiredEnv "SERVICES_PASSWORD" }}
      url_prefix: http://victoria-logs-victoria-logs-single-server.{{ .Release.Namespace }}.svc.cluster.local:9428/
```

**Additional context**
Currently I get the following error

```json
{"ts":"2025-06-02T12:54:02.239Z","level":"fatal","caller":"VictoriaMetrics/app/vmauth/auth_config.go:601","msg":"cannot load auth config: failed to pars -auth.config=\"/config/auth.yml\": failed to parse auth config: cannot unmarshal AuthConfig data: yaml: unmarshal errors:\n  line 3: cannot unmarshal !!map into string"}
```

**Comment by AndrewChubatiuk** [comment]
vmauth doesn't work with k8s api, there are two possible options:
- use operator, VMUser resource has [passwordRef](https://docs.victoriametrics.com/operator/api/#vmuserspec-passwordref), which allows to extract password from secrets
- use env variable placeholder in configuration
```
config:
  users:
    - username: my-user
      password: %{SERVICES_PASSWORD}
env:
  - name: SERVICES_PASSWORD
    valueFrom:
        secretKeyRef:
            name: victoria-logs-user-password
            key: password
```
