### ISSUE TITLE
bug: `victoria logs single` sink endpoints's configuration is broken

### ISSUE THREAD

**Issue by YuryHrytsuk** [VictoriaMetrics/helm-charts#2214]
**Chart name and version**
chart: victoria-logs-single
version: v0.11.1

**Describe the bug**
I am implementing HA pattern with 2 separate VL-single stacks and VM-auth in front. I disable vector in standby VL-single stack and add 2nd sink to the vector of the main VL-single stack.

![Image](https://github.com/user-attachments/assets/3370c984-1112-4359-b3b5-e72ebda6dc5a)
Original source: https://github.com/VictoriaMetrics/VictoriaLogs/issues/72

Now, if I configure `.Values.vector.customConfig.sinks.vlogs.endpoints` as below,
yaml
```
endpoints: 
  - "http://victoria-logs-main-single-server.{{ .Release.Namespace }}.svc.cluster.local:9428/insert/elasticsearch"
```
`helmfile-diff` fails with 
```
Error: Failed to render chart: exit status 1: Error: template: victoria-logs-single/templates/vector.yaml:10:82: executing "victoria-logs-single/templates/vector.yaml" at <$sinkConfig.endpoints>: wrong type for value; expected string; got []interface {}
```

When I try to avoid the error by using
```
endpoints: "[http://victoria-logs-standby-single-server.{{ .Release.Namespace }}.svc.cluster.local:9428/insert/elasticsearch]"
```
helmfile diff works, but vector pod then errors
```
2025-06-02T14:36:18.178746Z ERROR vector::cli: Configuration error. error=invalid type: string "[http://victoria-logs-standby-single-server.victoria-logs.svc.cluster.local:9428/insert/elasticsearch]", expected a sequence
```

**Custom values**
excerpt from helmfile.yaml
```yaml
  - name: victoria-logs-main-server
    namespace: &victoria-logs-namespace victoria-logs
    chart: victoria-metrics/victoria-logs-single
    version: &victoria-logs-single-version 0.11.1 # app version v1.23.0
    createNamespace: true
    values:
      - ./victoria-logs/values.main-server.yaml.gotmpl

  - name: victoria-logs-standby-server
    namespace: *victoria-logs-namespace
    chart: victoria-metrics/victoria-logs-single
    version: *victoria-logs-single-version
    createNamespace: true
    values:
      - ./victoria-logs/values.standby-server.yaml.gotmpl

  - name: victoria-metrics-auth
    namespace: *victoria-logs-namespace
    chart: victoria-metrics/victoria-metrics-auth
    version: 0.15.0 # app version v1.118.0
    createNamespace: true
    values:
      - ./victoria-metrics-auth/values.yaml.gotmpl
    needs:
      - victoria-logs-main-server
      - victoria-logs-standby-server
```
./victoria-logs/values.main-server.yaml.gotmpl
```yaml
# https://github.com/VictoriaMetrics/helm-charts/blob/victoria-logs-single-0.11.1/charts/victoria-logs-single/values.yaml

vector:
  enabled: true
  customConfig:
    sinks:
      vlogs: # vlogs-main-server (cannot rename created by default sink)
        endpoints: ["http://victoria-logs-main-single-server.{{ .Release.Namespace }}.svc.cluster.local:9428/insert/elasticsearch"]
      vlogs-standby-server: 
        endpoints: "[http://victoria-logs-standby-single-server.{{ .Release.Namespace }}.svc.cluster.local:9428/insert/elasticsearch]"
        # duplicated from chart's values for default sink
        type: elasticsearch
        inputs: [parser]
        mode: bulk
        api_version: v8
        compression: gzip
        healthcheck:
          enabled: false
        request:
          headers:
            VL-Time-Field: timestamp
            VL-Stream-Fields: stream,kubernetes.pod_name,kubernetes.container_name,kubernetes.pod_namespace
            VL-Msg-Field: message,msg,_msg,log.msg,log.message,log
            AccountID: "0"
            ProjectID: "0"

server:
  fullnameOverride: "victoria-logs-main-single-server"

  ingress:
    # we use victoria metrics auth to expose, load balance and authenticate access
    # https://github.com/VictoriaMetrics/VictoriaLogs/issues/72
```

./victoria-logs/values.standby-server.yaml.gotmpl
```yaml
# https://github.com/VictoriaMetrics/helm-charts/blob/victoria-logs-single-0.11.1/charts/victoria-logs-single/values.yaml

vector: # configured in main server to send logs to standby server
  enabled: false
  # helm chart still creates the configmap, so we need to use a different name
  # to avoid conflicts with configmap from main server where vector is enabled

server:
  fullnameOverride: "victoria-logs-standby-single-server"

  ingress:
    # we use victoria metrics auth to expose, load balance and authenticate access
    # https://github.com/VictoriaMetrics/VictoriaLogs/issues/72
    enabled: false
```

./victoria-metrics-auth/values.yaml.gotmpl
```yaml
# https://github.com/VictoriaMetrics/helm-charts/blob/victoria-metrics-auth-0.15.0/charts/victoria-metrics-auth/values.yaml

replicaCount: 1

ingress:
  enabled: true
  annotations:
    namespace: "{{ .Release.Namespace }}"
    cert-manager.io/cluster-issuer: "cert-issuer"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-logs-strip-prefix@kubernetescrd
  tls:
    - hosts:
        - {{ requiredEnv "DOMAIN" }}
      secretName: my-tls
  hosts:
    - name: {{ requiredEnv "DOMAIN" }}
      path:
        - /logs
      pathType: Prefix

config:
  users:
    - username: {{ requiredEnv "USER" }}
      password: {{ requiredEnv "PASSWORD" }}
      # https://docs.victoriametrics.com/victoriametrics/vmauth/#high-availability
      url_prefix:
      - http://victoria-logs-main-single-server.{{ .Release.Namespace }}.svc.cluster.local:9428/
      - http://victoria-logs-standby-single-server.{{ .Release.Namespace }}.svc.cluster.local:9428/
```
