### ISSUE TITLE
feature: [victoria-logs-single] `topologySpreadConstraints` provide default labelSelector if not defined

### ISSUE THREAD

**Issue by YuryHrytsuk** [VictoriaMetrics/helm-charts#2219]
**Chart name and version, where you feel a lack of requested feature**
chart: victoria-logs-single
version: v0.11.2

**Is your feature request related to a problem? Please describe.**
I want to [distribute victor-logs-single pods across nodes](https://stackoverflow.com/questions/39092090/how-can-i-distribute-a-deployment-across-nodes) for HA purposes. That's why I define `topologySpreadConstraints` that needs `labelSelector.matchLabels` which is defined deep inside templates of victoria-logs-single chart (https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-common/templates/_helpers.tpl#L196)

**Describe the solution you'd like**
I want chart to automatically populate `server.topologySpreadConstraints.[].labelSelector.matchLabels` if not specified explicitly (like in https://github.com/VictoriaMetrics/helm-charts/pull/583)

**Describe alternatives you've considered**
Right now I am hardcoding label selectors (copied from deployed statefulset)
```yaml
server:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app: server
          app.kubernetes.io/instance: victoria-logs
          app.kubernetes.io/name: victoria-logs-single
```

**Additional context**
A good example how it is done in `vmagent` https://github.com/VictoriaMetrics/helm-charts/pull/583
