### ISSUE TITLE
Why enabling `admissionWebhooks` in a cluster with Istio service mesh causes health check failure ?

### ISSUE THREAD

**Issue by crewri** [VictoriaMetrics/helm-charts#2220]
I am seeing failure in cluster installation when enabling `admissionWebhooks`.

```
victoria-metrics-operator:
  enabled: true
  serviceMonitor:
    enabled: true
  admissionWebhooks:
    enabled: true
```

**Error**

"https://victoria-metrics-victoria-metrics-operator.infra.svc:9443/validate-operator-victoriametrics-com-v1beta1-vmalertmanagerconfig?timeout=10s":
             tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match
             victoria-metrics-victoria-metrics-operator.infra.svc

They work only if I make

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: allow-mixed-traffic-victoria-metrics
  namespace: infra
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: victoria-metrics
  mtls:
    mode: PERMISSIVE
```

Is this required to have `Permissive` for validatingwebhook to work ?

**Comment by AndrewChubatiuk** [comment]
interesting case, by default helm chart generates self signed certs for webhook, which seems to be a problem for istio, need to check which solution can work for this case

**Comment by makasim** [comment]
If you can use `PERMISSIVE` mode for `VictoriaMetrics` services (including the operator), I recommend doing so. Enforcing mTLS for operator-to-Kubernetes API server communication offers limited value, as this traffic already goes over a secure channel.

While running VictoriaMetrics in STRICT mode is possible, it often introduces unnecessary complexity and edge cases.

There is a doc on how to run VictoriaMetrics  and Istio https://docs.victoriametrics.com/operator/integrations/istio/

**Comment by crewri** [comment]
@AndrewChubatiuk  @makasim 

keeping permissive only for operator. rather than for all components of victoria metric also works.

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: allow-mixed-traffic-victoria-metrics
  namespace: infra
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: victoria-metrics-operator
  mtls:
    mode: PERMISSIVE
```

Thanks.
