### ISSUE TITLE
feature: add ability to specify multiple downsampling filters in Distributed chart

### ISSUE THREAD

**Issue by tiny-pangolin** [VictoriaMetrics/helm-charts#2221]
**Chart name and version, where you feel a lack of requested feature**
chart: victoria-metrics-cluster
version: v0.16.0

**Is your feature request related to a problem? Please describe.**
users are unable to specify multiple instances of a command line argument in the distributed helm chart making it tricky to define complex downsampling polices.

**Describe the solution you'd like**
I would like if the extra args field in the distributed chart could have the same command line argument defined multiple times

**Describe alternatives you've considered**
using a complex single instance of the downsampling argument but this would challenging to maintain over time.

**Additional context**
N/A

**Comment by AndrewChubatiuk** [comment]
looks like this is an operator issue, since it expects map[string]string in ExtraArgs, which means that downsampling filters can be only passed as comma-separated value:
```
zontTpl:
  vmcluster:
    spec:
      vmstorage:
        extraArgs:
          downsampling.period: '{vm_account_id="12"}:1h:1m,{vm_account_id="42"}:2h:2m'
```
there's nothing could be done in charts
