### ISSUE TITLE
bug: Operator ignores `spec.image.registry` field from CRDs (VMSingle, etc.)

### ISSUE THREAD

**Issue by NeOncsgo1** [VictoriaMetrics/helm-charts#2226]
Chart:
victoria-metrics/victoria-metrics-k8s-stack
Chart version 0.50.1

What happened?

When deploying components like VMSingle using a private registry, the Helm chart correctly generates the Custom Resource with a spec.image.registry field.

However, the victoria-metrics-operator seems to completely ignore this registry field when it reconciles the CR and creates the underlying Deployment or StatefulSet.

The resulting Pod spec uses an image path constructed only from repository and tag. This forces Kubernetes to pull from the default registry (e.g., Docker Hub) instead of the specified private registry, leading to ImagePullBackOff errors.

What you expected to happen?

The victoria-metrics-operator should honor the spec.image.registry field from the CR. It should combine registry, repository, and tag to form the full, correct image path (<registry>/<repository>:<tag>) for the pods it manages.
How to reproduce it:

Use the victoria-metrics-k8s-stack:0.50.1 chart.
Configure values.yaml to use a private registry for a component, for example vmsingle:
YAML
```

vmsingle:
  enabled: true
  spec:
    image:
      registry: "0000000000000.dkr.ecr.eu-central-1.amazonaws.com"
      repository: "victoriametrics/victoria-metrics"
      tag: "v1.116.0"
```
Deploy the chart
In my ArgoCD i see this diff

![Image](https://github.com/user-attachments/assets/bf1b9c8f-61e3-452f-9dad-326e747c7a59)
And crd VMsingle in status out of sycn
Bug 2: Helm Templating Fails with nil map Error

Attempting to use the documented global.image.registry setting to specify a private registry for all components immediately fails the template rendering process. For the first component processed (e.g., vmsingle), it triggers the following error:

Error: template: ... executing "vm.internal.image" at <set $image "registry" ...>: error calling set: assignment to entry in nil map

How to reproduce it:

Use the victoria-metrics-k8s-stack:0.50.1 chart.

Configure values.yaml to use a private registry in global, for example global:
```
global:
  image:
    registry: "0000000000000.dkr.ecr.eu-central-1.amazonaws.com"
```

helm template .

Helm version: v3.17.2
Kubernetes version: 1.30

**Comment by f41gh7** [comment]
As far as I see, operator doesn't provide an option to change `registry` per resource https://docs.victoriametrics.com/operator/api/#image.  cc @AndrewChubatiuk 

 For me, it doesn't make much sense. If you already have define `repository`, just add a value of registry into it: ` repository: "0000000000000.dkr.ecr.eu-central-1.amazonaws.com/victoriametrics/victoria-metrics"`

 But, operator supports global registry option, for all resources:

```
# values.yaml
victoria-metrics-operator:
  enabled: true
  env:
  - name: VM_CONTAINERREGISTRY
    value: 0000000000000.dkr.ecr.eu-central-1.amazonaws.com
```
