### ISSUE TITLE
bug: victoria-metrics-k8s-stack ignores vmauth.spec.image.repository field

### ISSUE THREAD

**Issue by marselsultanov** [VictoriaMetrics/helm-charts#2236]
```
vmauth:
  spec:
    image:
      repository: localrepo/remote-quay-docker/victoriametrics/vmauth
```
in https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml#L746

creates CRD without repository:
```
Spec:
  Image:
    Tag:  v1.118.0
```
