### ISSUE TITLE
[victoria-metrics-k8s-stac] `labelmap` doesn't working in `inlineRelabelConfig`

### ISSUE THREAD

**Issue by kolserdav** [VictoriaMetrics/helm-charts#2237]
Hi everyone! I'm just getting started with k8s including VictoriaMetrics. 

**I'm trying to collect basic metrics from pods that are tagged with a specific label and add some labels from the pod for easy filtering of metrics.**

I have two issues with `inlineRelabelConfig`:
1. How can I collect metrics from `nodeScrape` only for pods with a certain label?
2. How can I add labels to the collected metrics so that I can filter by them?

I currently have this `values.yaml`
_issues are noted in the comments_
```yaml
vmsingle:
  enabled: true
  replicaCount: 2
  retentionPeriod: "30d"
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: "standard"
  service:
    type: ClusterIP

vmagent:
  enabled: true
  replicaCount: 2
  scrapeInterval: "60s"
  podScrapeInterval: "30s"
  spec:
    selectAllByDefault: false
    nodeScrapeSelector: {} 
    
    podScrapeSelector: null
    podScrapeNamespaceSelector: null
    serviceScrapeSelector: null
    serviceScrapeNamespaceSelector: null
    probeSelector: null
    probeNamespaceSelector: null
    nodeScrapeNamespaceSelector: null
    staticScrapeSelector: null
    staticScrapeNamespaceSelector: null
    inlineRelabelConfig:
      # It doesn't work
      - sourceLabels: [__meta_kubernetes_endpoints_label_monitoring]
        action: keep
        regex: "enabled"
      # It doesn't work
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(project_id|service_id)
      # It works!
      - action: keep 
        sourceLabels: [__name__]
        regex: "(container_cpu_usage_seconds_total|container_memory_usage_bytes|process_memory_limit_bytes|container_network_receive_bytes_total|container_network_transmit_bytes_total|container_fs_reads_bytes_total|container_fs_writes_bytes_total|kube_pod_status_ready|kube_pod_container_status_restarts_total)"

defaultScrapeConfigs:
  enabled: false

alertmanager:
  enabled: false  
vmcluster:
  enabled: false
vmalert:
  enabled: false
vmbackup:
  enabled: false
vmauth:
  enabled: false
vminsert:
  enabled: false
vmselect:
  enabled: false
vmstorage:
  enabled: false

prometheus-node-exporter: 
  enabled: false
grafana:
  enabled: false
kube-state-metrics:
  enabled: false
```

Most likely I'm doing something wrong. But I've tried a lot of approaches in the last few days and this solution is the closest to the target, but it still doesn't work properly.

**Comment by f41gh7** [comment]
@kolserdav  relabeling configuration has a different scopes of labels.  `__metadata` prefixed labels are only accessible during service discovery level relabeling ( which could be configured `VMServicescrape` or other `*Scrape` objects).

 `inlineRelabelConfig` relabel config applies a global configuration before forward time series to the remote writes, at this point all label names which started with `__`  are removed from scope.

 Related doc https://docs.victoriametrics.com/victoriametrics/relabeling/#relabeling-stages


 You have the could apply relabeling for  `__meta` labels globally with the following settings:

```
# https://docs.victoriametrics.com/operator/api/#vmagentspec-servicescraperelabeltemplate
vmagent:
  spec:
   serviceScrapeRelabelTemplate:
      - sourceLabels: [__meta_kubernetes_pod_label_monitoring]
        action: keep
        regex: "enabled"
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(project_id|service_id)
   podScrapeRelabelTemplate:
      - sourceLabels: [__meta_kubernetes_pod_label_monitoring]
        action: keep
        regex: "enabled"
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(project_id|service_id)
```

 Also, operator will receive global relabeling rules at one of the next releases. Related issue: https://github.com/VictoriaMetrics/operator/issues/1179

**Comment by kolserdav** [comment]
Thanks for the support!
The problem was that `vmagent` does not have access to the pod labels at the time of scraping with `VMNodeScrape`.

I used this approach to solve this issue: https://forum.gitlab.com/t/solved-kubernetes-executor-runner-job-metrics-scrape-pod-labels-annotations-with-prometheus/114763

The basic metrics are collected with `VMNodeScrape`. And the annotations (for some reason it didn't work with labels) are collected with `kube-state-metrics`. And then a request is made using `join` like that:
```bash
#! /usr/bin/bash

END=$(date +%s)
START=$((END - 60))
NAMESPACE="pods-namespace"
SERVICE_ID="pods-target-annotation-value"

curl "http://10.106.56.227:8429/api/v1/query" \
  -G \
  --data-urlencode "query=
    (
      container_cpu_usage_seconds_total{namespace=\"${NAMESPACE}\"} or
      container_memory_usage_bytes{namespace=\"${NAMESPACE}\"} or
      container_network_receive_bytes_total{namespace=\"${NAMESPACE}\"} or
      container_network_transmit_bytes_total{namespace=\"${NAMESPACE}\"} or
      container_fs_reads_bytes_total{namespace=\"${NAMESPACE}\"} or
      container_fs_writes_bytes_total{namespace=\"${NAMESPACE}\"}
    )
    and on(pod)
    (
      kube_pod_annotations{
        exported_namespace=\"${NAMESPACE}\",
        annotation_victoriametrics_com_service_id=\"${SERVICE_ID}\"
      } > 0
    )
  " \
  --data-urlencode "start=${START}" \
  --data-urlencode "end=${END}"
```
The final configuration turned out to be like this:
```yaml
vmagent:
  enabled: true
  scrapeInterval: "60s"
  podScrapeInterval: "60s"
  spec:
    selectAllByDefault: false
    nodeScrapeSelector: {}
    nodeScrapeNamespaceSelector: null
    podScrapeSelector: {}
    podScrapeNamespaceSelector: null
    serviceScrapeSelector: null
    serviceScrapeNamespaceSelector: null
    probeSelector: null
    probeNamespaceSelector: null
    staticScrapeSelector: null
    staticScrapeNamespaceSelector: null
    inlineRelabelConfig:
      - action: keep 
        sourceLabels: [__name__]
        regex: "(kube_pod_annotations|container_cpu_usage_seconds_total|container_memory_usage_bytes|process_memory_limit_bytes|container_network_receive_bytes_total|container_network_transmit_bytes_total|container_fs_reads_bytes_total|container_fs_writes_bytes_total|kube_pod_status_ready|kube_pod_container_status_restarts_total)"

kube-state-metrics:
  enabled: true
  metricAnnotationsAllowList:
    - pods=[*]
  collectors:
    - pods
  podLabels:
    app.kubernetes.io/instance: vm-stack
    app.kubernetes.io/name: kube-state-metrics
  extraArgs:
    - --metric-allowlist=kube_pod_annotations
  vmScrape:
    enabled: true
    kind: VMPodScrape
    spec:
      podMetricsEndpoints:
        - port: http
          path: /metrics
          scheme: http
          interval: 30s
          metricRelabelConfigs:
          - source_labels: [__name__]
            regex: "kube_pod_annotations"
            action: keep
          - source_labels: [exported_pod]
            target_label: pod
            action: replace
      selector:
        matchLabels:
          app.kubernetes.io/instance: vm-stack
          app.kubernetes.io/name: kube-state-metrics
      namespaceSelector: {}
```
