### ISSUE TITLE
question: victoria-metrics-k8s-stack Need help with metrics

### ISSUE THREAD

**Issue by NeOncsgo1** [VictoriaMetrics/helm-charts#2242]
Hi, I need help with metrics, I have the following values.yaml:

```
fullnameOverride: victoriametrics-bigdata
defaultRules:
  create: true
victoria-metrics-operator:
  enabled: true
  env:
  - name: VM_CONTAINERREGISTRY
    value: 617329703819.dkr.ecr.eu-central-1.amazonaws.com
  crds:
    plain: false
    cleanup:
      enabled: false
    enabled: true
  operator:
    disable_prometheus_converter: false
  securityContext:
    seccompProfile:
      type: "RuntimeDefault"
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
  admissionWebhooks:
    enabled: false
  watchNamespaces:
    - bigdata
  tolerations:
  - effect: NoSchedule
    key: bigdata
  image:
    registry: "617329703819.dkr.ecr.eu-central-1.amazonaws.com"
    repository: "victoriametrics/operator"
    tag: "v0.59.1"


vmsingle:
  enabled: true
  annotations:
    OCG: ITD-BIGDATA
  imagePullSecrets:
    - name: ecr-secret
  spec:
    image:
      repository: "victoriametrics/victoria-metrics"
      tag: "v1.116.0"
    imagePullSecrets:
    - name: ecr-secret
    port: "8429"
    # -- Data retention period. Possible units character: h(ours), d(ays), w(eeks), y(ears), if no unit character specified - month. The minimum retention period is 24h. See these [docs](https://docs.victoriametrics.com/single-server-victoriametrics/#retention)
    retentionPeriod: "7d"
    replicaCount: 1
    tolerations:
    - effect: NoSchedule
      key: bigdata
    storage:
      accessModes:
        - ReadWriteMany
      storageClassName: efs-bigdata-tensor-server
      volumeName: pv-efs-kube-vm-stack
      resources:
        requests:
          storage: 20Gi
    securityContext:
      seccompProfile:
        type: "RuntimeDefault"
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
        - ALL
 
alertmanager:
  enabled: false
vmalert:
  enabled: true
  spec:
    image:
      repository: "victoriametrics/vmalert"
      tag: "v1.116.0"
    configReloaderImageTag: jimmidyson/configmap-reload:v0.8.0
    serviceAccountName: vmagent-bigdata-custom-sa
    imagePullSecrets:
    - name: ecr-secret
    tolerations:
    - effect: NoSchedule
      key: bigdata
    extraArgs:
      notifier.blackhole: "true"
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
      seccompProfile:
        type: "RuntimeDefault"
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
        - ALL
vmagent:
  enabled: true
  spec:
    image:
      repository: "victoriametrics/vmagent"
      tag: "v1.116.0"
    configReloaderImageTag: prometheus-operator/prometheus-config-reloader:v0.70.0
    imagePullSecrets:
    - name: ecr-secret
    tolerations:
    - effect: NoSchedule
      key: bigdata
    serviceAccountName: vmagent-bigdata-custom-sa
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
      seccompProfile:
        type: "RuntimeDefault"
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
        - ALL

kube-state-metrics:
  enabled: true
  image:
    registry: 617329703819.dkr.ecr.eu-central-1.amazonaws.com
    repository: kube-state-metrics/kube-state-metrics
    tag: "v2.15.0"
  extraArgs:
    - --namespaces=bigdata
  tolerations:
  - effect: NoSchedule
    key: bigdata

kubelet:
  enabled: true
  vmScrapes:
    # -- Enable scraping /metrics/cadvisor from kubelet's service
    cadvisor:
      enabled: true
      spec:
        path: /metrics/cadvisor
    # -- Enable scraping /metrics/probes from kubelet's service
    probes:
      enabled: true
      spec:
        path: /metrics/probes
    # -- Enabled scraping /metrics/resource from kubelet's service
    resources:
      enabled: true
      spec:
        path: /metrics/resource
    kubelet:
      spec: {}
  # -- Spec for VMNodeScrape CRD is [here](https://docs.victoriametrics.com/operator/api.html#vmnodescrapespec)
  vmScrape:
    kind: VMNodeScrape
    spec:
      scheme: "https"
      honorLabels: true
      interval: "30s"
      scrapeTimeout: "5s"
      tlsConfig:
        insecureSkipVerify: true
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabelConfigs:
        - source_labels: [__meta_kubernetes_node_name]
          action: drop
          regex: fargate-.+
        - source_labels: [__meta_kubernetes_node_label_karpenter_sh_nodepool]
          action: keep
          regex: "bigdata"
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - sourceLabels: [__metrics_path__]
          targetLabel: metrics_path
        - targetLabel: job
          replacement: kubelet
      metricRelabelConfigs:
        - source_labels: [namespace]
          action: keep
          regex: "bigdata"
      honorTimestamps: false

kubeControllerManager:
  enabled: false
kubeDns:
  enabled: false
coreDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false
extraObjects:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-efs-kube-vm-stack
      namespace: bigdata
    spec:
      capacity:
        storage: 40Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      storageClassName: efs-bigdata-tensor-server
      csi:
        driver: efs.csi.aws.com
        volumeHandle: fs-0575661a90d64a61d::fsap-07ca291ccb5da0550

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: vmagent-kubelet-scraper
    rules:
    - apiGroups: [""]
      resources:
      - services
      - endpoints
      - pods
      - namespaces
      - nodes
      - nodes/metrics
      - nodes/proxy
      - nodes/stats
      - nodes/log
      verbs: ["get", "list", "watch"]
    - nonResourceURLs: ["/metrics", "/metrics/cadvisor", "/metrics/probes", "/metrics/resource"]
      verbs: ["get"]

  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: vmagent-bigdata-custom-sa
      namespace: bigdata

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: vmagent-kubelet-scraper-binding
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: vmagent-kubelet-scraper
    subjects:
    - kind: ServiceAccount
      name: vmagent-bigdata-custom-sa
      namespace: bigdata

```

In VMAgent I can see all my monitoring targets, but not all metrics are being collected from them.

![Image](https://github.com/user-attachments/assets/d3efb6f8-b386-4614-91b2-857c1bf0e956)
For example, data from the container_network_receive_bytes_total metric is missing.
![Image](https://github.com/user-attachments/assets/916b46db-9243-4b31-834f-4380326a52a3)

When I go into the VMAgent pod and make a direct query, the metrics are there
![Image](https://github.com/user-attachments/assets/c568d4b5-bb74-49ff-8993-275333cdb2d4)

Please help me understand why this is happening—maybe I missed a configuration or set something up incorrectly.

There is also a problem with VMRules—for example, the metric node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m is missing, even though the container_cpu_usage_seconds_total metric is present, and all rules are enabled and created.

But first, please help me understand the issue above—why are not all metrics reaching VMSingle?

**Comment by NeOncsgo1** [comment]
If you need additional data, I can provide it

**Comment by AndrewChubatiuk** [comment]
are there're any errors/warnings in vmagent/vmsingle logs?

**Comment by NeOncsgo1** [comment]
no, nothing

**Comment by NeOncsgo1** [comment]
If I run ServiceMonitor and PrometheusOperator in parallel (with kubelet monitoring), then VM picks up the ServiceMonitor, creates a corresponding ServiceScrape from it, and all metrics are displayed—everything also shows up correctly in Grafana and VM
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app: prometheus-operator-kubelet
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: prometheus-operator
    app.kubernetes.io/version: 72.7.0
    argocd.argoproj.io/instance: prometheus-stack
    chart: kube-prometheus-stack-72.7.0
    heritage: Helm
    release: prometheus-stack
  name: prometheus-stack-prometheu-kubelet
  namespace: bigdata
spec:
  attach_metadata:
    node: false
  endpoints:
    - attach_metadata: {}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      honorTimestamps: true
      metricRelabelConfigs:
        - action: drop
          regex: >-
            (csi_operations|storage_operation_duration)_seconds_bucket;(0.25|2.5|15|25|120|600)(\.0)?
          sourceLabels:
            - __name__
            - le
      port: https-metrics
      relabelConfigs:
        - action: replace
          sourceLabels:
            - __metrics_path__
          targetLabel: metrics_path
      scheme: https
      tlsConfig:
        ca: {}
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        cert: {}
        insecureSkipVerify: true
    - attach_metadata: {}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      honorTimestamps: true
      interval: 10s
      metricRelabelConfigs:
        - action: drop
          regex: >-
            container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)
          sourceLabels:
            - __name__
        - action: drop
          regex: >-
            container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)
          sourceLabels:
            - __name__
        - action: drop
          regex: container_memory_(mapped_file|swap)
          sourceLabels:
            - __name__
        - action: drop
          regex: container_(file_descriptors|tasks_state|threads_max)
          sourceLabels:
            - __name__
        - action: drop
          regex: container_memory_failures_total;hierarchy
          sourceLabels:
            - __name__
            - scope
        - action: drop
          regex: container_network_.*;(cali|cilium|cni|lxc|nodelocaldns|tunl).*
          sourceLabels:
            - __name__
            - interface
        - action: drop
          regex: container_spec.*
          sourceLabels:
            - __name__
        - action: drop
          regex: .+;
          sourceLabels:
            - id
            - pod
        - action: keep
          regex: bigdata
          sourceLabels:
            - namespace
      path: /metrics/cadvisor
      port: https-metrics
      relabelConfigs:
        - action: replace
          sourceLabels:
            - __metrics_path__
          targetLabel: metrics_path
      scheme: https
      tlsConfig:
        ca: {}
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        cert: {}
        insecureSkipVerify: true
    - attach_metadata: {}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      honorTimestamps: true
      path: /metrics/probes
      port: https-metrics
      relabelConfigs:
        - action: replace
          sourceLabels:
            - __metrics_path__
          targetLabel: metrics_path
      scheme: https
      tlsConfig:
        ca: {}
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        cert: {}
        insecureSkipVerify: true
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
      k8s-app: kubelet
```
