### ISSUE TITLE
Multitenancy Headers passed for VictoriaLogs not clear why it isn't working

### ISSUE THREAD

**Issue by maheshevizio** [VictoriaMetrics/helm-charts#2257]
I have a VictoriaLogs Cluster setup and able to send the logs with the OTLPHTTP exporter with headers being digits Ex:  account_id=7 and project_id=9...

It doesn't work when I add any alphabet or special character, Does it support only digits?

   ```
                otlphttp/vlogs:
            # This URL will be updated dynamically depending on the environment mapped to Loki
            endpoint: "http://[vlc-victoria-logs-cluster-vlinsert.victoria-logs.svc.cluster.local]:9481/insert/opentelemetry"
            headers:
              AccountID: "32327-sdsd"
              ProjectID: "rererr0-5454-4f4f-8f8f-8f8f8f8f8f8f"
```
