### ISSUE TITLE
feature: Allow VMAgent (which creates from victoria-metrics-operator) to scrape non-default metrics paths

### ISSUE THREAD

**Issue by jorben5** [VictoriaMetrics/helm-charts#2260]
**Chart name and version, where you feel a lack of requested feature**
chart: victoria-metrics-operator
version: v0.46.4

**Is your feature request related to a problem? Please describe.**
My VMAgent was created by Victoria-metrics-operator. I'm trying to configure VMAgent to scrape custom metrics (Kubernetes Component SLI Metrics) from the Kubernetes API server (https://kubernetes.io/docs/reference/instrumentation/slis/). My scrape job looks like this:

```
- job_name: "sli-job"
  scheme: https
  tls_config:
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  static_configs:
    - targets:
        - "kubernetes.default.svc:443"
      labels:
        job: "mhd-sli-job"
  metrics_path: "/metrics/slis"
```

However, by default, the VMAgent does not have permission to scrape this endpoint.
The ClusterRole created by the operator (e.g., monitoring:vmagent-cluster-access-<vmAgentName>) only allows access to /metrics and /metrics/resources.
There is currently no option in the Helm chart or CRD to extend these permissions.

Describe the solution you'd like
Please add /metrics/slis to the autogenerated ClusterRole for VMAgent (e.g., monitoring:vmagent-cluster-access-\<vmAgentName\>).
Alternatively, allow customizing the generated ClusterRole permissions via the CRD or Helm values.

Describe alternatives you've considered
Using a custom ServiceAccount and managing RBAC manually — works but defeats the purpose of automation via CRDs.
