### ISSUE TITLE
vmalert: Required value: port name or number is required.

### ISSUE THREAD

**Issue by pollynesterovich** [VictoriaMetrics/helm-charts#228]
I get the following error when I try to upgrade the vmalert:
Error: UPGRADE FAILED: cannot patch "vmalert-victoria-metrics-alert-server" with kind Ingress: Ingress.extensions "vmalert-victoria-metrics-alert-server" is invalid: spec.rules[0].http.paths[0].backend: Required value: port name or number is required.

part values:
```
service:
    servicePort: 8880
    type: ClusterIP
  
  ingress:
    enabled: true
    hosts:
      - name: hostname
        path: /
        port: http
    tls:
      - secretName: secret
        hosts:
          - hostname
```
How to create an ingress for a vmalert?
