### ISSUE TITLE
[victoria-metrics-k8s-stack] bug: victoriametrics dashboards dont apply the multicluster setting

### ISSUE THREAD

**Issue by bmack94** [VictoriaMetrics/helm-charts#2281]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.55.0

**Describe the bug**
All kubernetes clusters respect the setting but the victoriametrics dashboards dont:
```
grafana:
  sidecar:
    dashboards:
      searchNamespace: ALL
      multicluster: true
```
The value is looked up but will never applied. Example can be found here:
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/files/dashboards/generated/victoriametrics-vmalert.yaml#L3
