### ISSUE TITLE
Alert is shown even no restart happened for vm-agent

### ISSUE THREAD

**Issue by eugenegoncharuk** [VictoriaMetrics/helm-charts#252]
I have a default rules setup for my cluster.
This rule always sending me alerts TooManyRestarts with the definition below

``` 
  - name: vm-health
    rules:
    - alert: TooManyRestarts
      annotations:
        description: Job {{`{{`}} $labels.job {{`}}`}} has restarted more than twice in the last 15 minutes. It might be crashlooping.
        summary: '{{`{{`}} $labels.job {{`}}`}} too many restarts (instance {{`{{`}} $labels.instance {{`}}`}})'
      expr: changes(process_start_time_seconds{job=~"victoriametrics|vmagent|vmalert"}[15m]) > 2
      labels:
        severity: critical
{{- if .Values.defaultRules.additionalRuleLabels }}
{{ toYaml .Values.defaultRules.additionalRuleLabels | indent 8 }}
{{- end }}
```

If I check my "vm-agent" pods they haven't been restarted any time.
Maybe it's worth to rewrite the rule for a different metric?
