### ISSUE TITLE
ClusterIssuer support for victoria-metrics-operator/certmanager.yaml

### ISSUE THREAD

**Issue by aspekt112** [VictoriaMetrics/helm-charts#260]
Hello! Can you add support `ClusterIssuer` at `helm-charts/charts/victoria-metrics-operator/templates/certmanager.yaml`? For now i forced to create `Issuer` object at VicrotiaMetrics Operator namespace or use self-signed certificate.
Also `admissionWebhooks.certManager.issuerName` has to be a map like below, not a string.
```
    issuerName:
      name: "issuer-name"
```

**Comment by f41gh7** [comment]
Yes, simple change to map must solve it. Latest release 0.5.1 must support it

```yaml
admissionWebhooks:
 enabled: true
 certManager:
   # -- Enables cert creation and injection by cert-manager.
   enabled: true
    # --If needed, provide own issuerName. Operator will create self-signed if empty.
    issuer:
       name: ca-issuer
       kind: ClusterIssuer
       # kind Issuer
       group: cert-manager.io
```
