### ISSUE TITLE
Add content files used remoteWrite.urlRelabelConfig in chart

### ISSUE THREAD

**Issue by nevlkv** [VictoriaMetrics/helm-charts#263]
If defined array  remoteWrite.urlRelabelConfig you need creates and mount files with rules  before deploy chart

Is it availible  create custom configmaps with content from values?

**Comment by nevlkv** [comment]
[maybe the order will not matter](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/467) ?
```
remote_wtite_relabelConfig:  /dir/default_name
remote_write:
 - url: some_url1
   [relabelConfig: /dir/file_name1]
 - url: some_url2
 - url: some_url3
   [relabelConfig: /dir/file_name3] 
 
```
