### ISSUE TITLE
[victoria-metrics-k8s-stack]  please add ability to use external victoria metrics cluster

### ISSUE THREAD

**Issue by cristicalin** [VictoriaMetrics/helm-charts#265]
I would like to use an external VM cluster in which to publish metrics with `victoria-metrics-k8s-stack` by disabling the grafana, alertmanager and vmsingle or vmcluster objects but keep just the vmagent and vmalert agents to publish to a remote VM cluster.

I see that the [VMAgent CRD](https://github.com/VictoriaMetrics/operator/blob/master/docs/quick-start.MD#vmagent) and [VMAlert CRD](https://github.com/VictoriaMetrics/operator/blob/master/docs/quick-start.MD#vmalert) already have the capability to target a remote VM cluster but these are not supported by the `victoria-metrics-k8s-stack` chart.

**Comment by k1rk** [comment]
hi @cristicalin. to write to external VM cluster you can just specify remote write in spec of vmagent
example:
`values.yaml`
```
vmagent:
  spec:
    remoteWrite:
      - url: "https://insert.vmcluster.domain.com/insert/0/prometheus/api/v1/write"
```
