### ISSUE TITLE
Not able to convert prometheus-operator objects

### ISSUE THREAD

**Issue by samba1112** [VictoriaMetrics/helm-charts#294]
I have tried installing prometheus-k8s-stack and then installing vm-stack,
For replacing prometheus with victoria metrics completely but with prometheus crds
I am not able to do it 
And in values file of artifacthub of vm operator & vm stack its given different boolean values to convert prometheus objects by default.

Attaching screenshots of values of vm operator and vm stack 

SS of vm operator
![Screenshot from 2022-03-16 17-26-13](https://user-images.githubusercontent.com/76871147/158585135-910057ed-88c3-491e-ac9a-dc5620a62a5b.png)
SS of vmstack
![Screenshot from 2022-03-16 17-26-46](https://user-images.githubusercontent.com/76871147/158585185-53d2e7ef-afe9-42e7-8e9a-557fc4be1aae.png)

**Comment by Haleygo** [comment]
@samba1112 Hello!
>For replacing prometheus with victoria metrics completely but with prometheus crds
I am not able to do it

Is this still not working? Can you try the latest version?

>And in values file of artifacthub of vm operator & vm stack its given different boolean values to convert prometheus objects by default.

Yeah, in operator, we disable it by default. But with stack, we use it by default.

**Comment by fenio** [comment]
I think I've got question closely related to that topic and I don't want to start another bugreport just for it.
I started from scratch with victoria-metrics-k8s-stack so I don't really need to convert prometheus based stuff to VM.

However now I'm trying to install other stuff on my cluster. Some of the components come with their own let's call it Prometheus targeted stuff. Like for example there are predefined Prometheus rules that can be used with cloudnative-pg.

It's simple file with bunch of alerts definitions:

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: postgres-v1-alerts
  namespace: database
spec:
  groups:
    - name: cnp-default.rules
      rules:
        - alert: LongRunningTransaction
          annotations:
            description: Pod {{ $labels.pod }} is taking more than 5 minutes (300 seconds) for a query.
            summary: A query is taking longer than 5 minutes.
          expr: |-
            cnpg_backends_max_tx_duration_seconds > 300
          for: 1m
          labels:
            severity: warning
```

Obviously if I try to deploy that file on my cluster it will fail as I'm using VM instead of Prometheus stack.
I couldn't find any information how to deal with such situations. What's the best way to convert such upstream rules to be compatible with VM stack?
