### ISSUE TITLE
k8s-stack: vmsingle expose influx port?

### ISSUE THREAD

**Issue by alaricljs** [VictoriaMetrics/helm-charts#295]
Is there a built-in way to expose the influx port with the k8s-stack chart?  I have gotten vmsingle listening inside the container, but haven't found anything in the chart to make that an endpoint or service in k8s.  What would be the best way to achieve this?

Thanks

**Comment by Haleygo** [comment]
@alaricljs Hello!
You can add [serviceSpec](https://docs.victoriametrics.com/operator/api.html?highlight=serviceSpec#vmagentspec) using your influx port under vmagent.Spec, operator will create an additional service then.

**Comment by AndrewChubatiuk** [comment]
hey @alaricljs. Given below config will create deployment with service that listens on port 8086 both tcp and udp traffic for influx
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: example-vmsingle
spec:
  retentionPeriod: "1"
  insertPorts:
    influxPort: "8086"
```
