### ISSUE TITLE
how to specifiy "-promscrape.cluster.memberNum" in vmagent helm chart when multiple replicas are configured

### ISSUE THREAD

**Issue by venkatbvc** [VictoriaMetrics/helm-charts#298]
In VmAgent chart:

- statefulset is enabled
- replicaCount is set to 2
- under extra args promscrape.cluster.membersCount is set to 2
how do we give promscrape.cluster.memberNum argument to the vmagent?

Currently k8s doesn't support providing statefulset ordinal index to the pod. A wrapper script needs to be added before starting vmagent. This will not work if distroless images are used. 

Will it be better to take hostname and get the ordinal number in k8s environments?

**Comment by Haleygo** [comment]
Hello!
Maybe you can use vmagent cr in victoria-metrics-k8s-stack, operator will help build this parameter.

**Comment by AndrewChubatiuk** [comment]
VictoriaMetrics already [supports](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2359) extraction of `-promscrape.cluster.memberNum` from pod name for statefulsets and it's already implemented in victoria-metrics-agent helm chart with 
```
statefulset:
  enabled: true
  clusterMode: true
```

**Comment by djryanj** [comment]
@AndrewChubatiuk that functionality is in the `victoria-metrics-agent` helm chart but a similar functionality does not exist in `victoria-metrics-k8s-chart`. You can build it yourself like this:

```yaml
vmagent:
  enabled: true
  spec:
    statefulMode: true # needed so that we can set up a cluster properly
    extraArgs:
      promscrape.streamParse: "true"
      promscrape.dropOriginalLabels: "true"
      promscrape.cluster.membersCount: "2"
      promscrape.cluster.replicationFactor: "2"
      envflag.enable: "true"
    extraEnvs:
      - name: promscrape_cluster_memberNum
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
    replicaCount: 2
```

But feature-parity here would be great given the likelihood of wanting a proper cluster of agents for HA even with a relatively small number of scrape targets.
