### ISSUE TITLE
victoria-metrics-alert chart -  How to configure recording rule through victoria-metrics-alert chart ?

### ISSUE THREAD

**Issue by sreejith-vk** [VictoriaMetrics/helm-charts#305]
How to configure recording rule through victoria-metrics-alert chart ?

Can we only configure alerts through the chart?
There is only alerts mentioned here : https://github.com/VictoriaMetrics/helm-charts/blob/28867177d708e254fd0342521cb949d603344b70/charts/victoria-metrics-alert/values.yaml#L201 

```
  # vmalert alert rules configuration configuration:
  # use existing configmap if specified
  # otherwise .config values will be used
  configMap: ""
  config:
    alerts:
      groups: []

```
