### ISSUE TITLE
How to configure alertmanager service from victoria-metrics-k8s-stack as NodePort

### ISSUE THREAD

**Issue by enp** [VictoriaMetrics/helm-charts#314]
Can't find any way to configure alertmanager service from victoria-metrics-k8s-stack as NodePort

Found serviceSpec in https://docs.victoriametrics.com/operator/api.html#vmalertmanagerspec and https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/vmalertmanager.yaml#L29 but can't understand what ```include "victoria-metrics-k8s-stack.``` means and how to set spec from values.yaml

Or maybe more simple solution exists?

**Comment by enp** [comment]
Temporary fixed local file ```templates/victoria-metrics-operator/alertmanager/vmalertmanager.yaml``` in chart like so:

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
...
spec:
{{ include "victoria-metrics-k8s-stack.alertmanagerSpec" . | indent 2}}
  serviceSpec:
    spec:
      type: NodePort
{{- end }}
```

So I see updated resource in ```helm upgrade ... --dry-run --debug```, but no effect in ```kubectl describe svc vmalertmanager-vm-stack-victoria-metrics-k8s-stack -n monitoring``` - type is still ```ClusterIP```. Bug in operator or I'm using it in wrong way?
