### ISSUE TITLE
Alertmanager configuration default values are not overritten [victoria-metrics-k8s-stack]

### ISSUE THREAD

**Issue by PawlikMateusz** [VictoriaMetrics/helm-charts#317]
Hi, when I am adding a new alertmanager configuration, alertmanager secret that holds alertmanager.yaml file is getting merged with some default values. Example below:
Alert manager section in values.yaml file:
```
alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    receivers:
      - name: "teams_infra_alerts_channel"
        webhook_configs:
          - url: "http://alertmanager-msteams:2000/infra_alerts_channel"
            send_resolved: true
    route:
      receiver: "teams_infra_alerts_channel"
      group_by: ["job", "alertname"]
      group_wait: 1m
      group_interval: 5m
      repeat_interval: 6h
```
When I am doing helm upgrade i got this output (content of vmalertmanager-vm-victoria-metrics-k8s-stack-config)
```
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
      slack_api_url: http://slack:30500/
    receivers:
    - name: teams_infra_alerts_channel
      webhook_configs:
      - send_resolved: true
        url: http://alertmanager-msteams:2000/infra_alerts_channel
    route:
      group_by:
      - job
      - alertname
      group_interval: 5m
      group_wait: 1m
      receiver: teams_infra_alerts_channel
      repeat_interval: 6h
      routes:
      - group_by:
        - code_owner_channel
        - alertgroup
        - job
        matchers:
        - code_owner_channel!=""
        - severity=~"info|warning|critical"
        receiver: slack-code-owners
      - continue: true
        matchers:
        - severity=~"info|warning|critical"
        receiver: slack-monitoring
    templates:
    - /etc/vm/configs/**/*.tmpl
```
Is there a way to get rid of default values and apply only my configuration?

**Comment by Shm013** [comment]
This is because of template renders secret like this and there is not diff when values update.

```
# Source: victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/vmalertmanager.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: victoria-metrics-k8s-stack-alertmanager
    app.kubernetes.io/instance: victoria-metrics-k8s-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: 1.87.1
    helm.sh/chart: victoria-metrics-k8s-stack-0.14.8
    name: victoria-metrics-k8s-stack-alertmanager
    namespace: victoriametrics
```

If you need fastfix you can delete alertnamager with applying chart with value `alertmanager.enabled: false` and install again, this will update secret.

**Comment by f41gh7** [comment]
Hello, I think it's an old issue. New versions of operator must perform period resync (60sec by default). It must solve any issues with config update.

**Comment by Haleygo** [comment]
@Shm013 I'm so sorry for the long silence, I wasn't able to reproduce it before and forget to ask here(

>This is because of template renders secret like this and there is not diff when values update.

Do you use `helm template charts/victoria-metrics-k8s-stack` directly to get [this result](https://github.com/VictoriaMetrics/helm-charts/issues/317#issuecomment-1503373143)?
It should contain the whole resource including `alertmanager.yaml` data, thus changes can be detected by `helm upgrade`.
```
➜  ~ helm template vm -n default charts/victoria-metrics-k8s-stack

---
# Source: victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/vmalertmanager.yaml
apiVersion: v1
kind: Secret
metadata:
  name: vm-victoria-metrics-k8s-stack-alertmanager
  namespace: default
  labels:
    app.kubernetes.io/component: victoria-metrics-k8s-stack-alertmanager
    helm.sh/chart: victoria-metrics-k8s-stack-0.18.8
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/instance: vm
    app.kubernetes.io/version: "v1.95.1"
    app.kubernetes.io/managed-by: Helm
stringData:
  alertmanager.yaml: "global:\n  resolve_timeout: 5m\n  slack_api_url: http://slack:30500/\ninhibit_rules:\n- equal:\n  - cluster\n  - namespace\n  - alertname\n  source_matchers:\n  - severity=critical\n  target_matchers:\n  - severity=~\"warning|info\"\n- equal:\n  - cluster\n  - namespace\n  - alertname\n  source_matchers:\n  - severity=warning\n  target_matchers:\n  - severity=info\n- equal:\n  - cluster\n  - namespace\n  source_matchers:\n  - alertname=InfoInhibitor\n  target_matchers:\n  - severity=info\nroute:\n  group_by:\n  - alertgroup\n  - job\n  group_interval: 5m\n  group_wait: 30s\n  receiver: slack-monitoring\n  repeat_interval: 12h\n  routes:\n  - group_by:\n    - code_owner_channel\n    - alertgroup\n    - job\n    matchers:\n    - code_owner_channel!=\"\"\n    - severity=~\"info|warning|critical\"\n    receiver: slack-code-owners\n  - continue: true\n    matchers:\n    - severity=~\"info|warning|critical\"\n    receiver: slack-monitoring\ntemplates:\n- /etc/vm/configs/**/*.tmpl"
```

According to my test, any field change under [alertmanager.config](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml#L353) will be updated to the secret resource.
My test steps:
1. helm install latest victoria-metrics-k8s-stack with default values;
2. change or delete some fields under [alertmanager.config](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml#L353);
3. run `helm upgrade` with updated value file and check secret `vm-victoria-metrics-k8s-stack-alertmanager` data.
