### ISSUE TITLE
Can't use one port for TCP/UDP with LoadBalancer service type (OpenTSDB input)

### ISSUE THREAD

**Issue by ipeacocks** [VictoriaMetrics/helm-charts#319]
I use Helm for installation of clustered VM version and OpenTSDB input. That's why in `values.yaml` I am using `opentsdbListenAddr` option:
```
...
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json
    opentsdbListenAddr: ":4242"
...
```
And service `type: LoadBalancer`
As results it produces such resulted yaml:
```
---
# Source: victoria-metrics-cluster/templates/vminsert-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vminsert
    app.kubernetes.io/name: victoria-metrics-cluster
    app.kubernetes.io/instance: release-name
    helm.sh/chart: victoria-metrics-cluster-0.9.23
    app.kubernetes.io/managed-by: Helm
  name: release-name-victoria-metrics-cluster-vminsert
  namespace: default
spec:
  ports:
    - name: http
      port: 8480
      protocol: TCP
      targetPort: http
    - name: opentsdb-udp
      protocol: UDP
      port: 4242
      targetPort: opentsdb-udp
    - name: opentsdb-tcp
      protocol: TCP
      port: 4242
      targetPort: opentsdb-tcp

  selector:
    app: vminsert
    app.kubernetes.io/name: victoria-metrics-cluster
    app.kubernetes.io/instance: release-name
  type: "LoadBalancer"
```
So `opentsdbListenAddr` gotta open two OpenTSDB ports TCP and UDP (can OpenTSDB even work on UDP?). As a result of such description K8s opens only one UDP port:
```
NAME                                                  TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                         AGE
victoria-metrics-victoria-metrics-cluster-vminsert    LoadBalancer   10.11.82.14     10.15.12.10   8480:31219/TCP,4242:31862/UDP   42h
```
Of course it's possible to use also
```
  extraArgs:
...
    opentsdbListenAddr: ":4242"
    opentsdbHTTPListenAddr: ":4243"
```
But according to this https://github.com/VictoriaMetrics/VictoriaMetrics/issues/266#issuecomment-566759632  it's not needed now and that's produce error:
```
Error: UPGRADE FAILED: cannot patch "victoria-metrics-victoria-metrics-cluster-vminsert" with kind Service: Service "victoria-metrics-victoria-metrics-cluster-vminsert" is invalid: spec.ports: Invalid value: []core.ServicePort{core.ServicePort{Name:"http", Protocol:"TCP", AppProtocol:(*string)(nil), Port:8480, TargetPort:intstr.IntOrString{Type:1, IntVal:0, StrVal:"http"}, NodePort:32421}, core.ServicePort{Name:"opentsdb-udp", Protocol:"UDP", AppProtocol:(*string)(nil), Port:4242, TargetPort:intstr.IntOrString{Type:1, IntVal:0, StrVal:"opentsdb-udp"}, NodePort:0}}: may not contain more than 1 protocol when type is 'LoadBalancer'
```
Probably this section needs to be removed in Helm:
```
{{- if .Values.vminsert.extraArgs.opentsdbListenAddr }}
    - name: opentsdb-udp
      protocol: UDP
      port: {{ include "split-host-port" .Values.vminsert.extraArgs.opentsdbListenAddr }}
      targetPort: opentsdb-udp
{{- end }}
```
