### ISSUE TITLE
[k8s-stack] Default grafana dashboard "Kubernetes / Compute Resources / Pod" not working

### ISSUE THREAD

**Issue by nikmel2803** [VictoriaMetrics/helm-charts#320]
I ran into a problem that the "Kubernetes / Compute Resources / Pod" dashboard does not display RAM consumption:

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/32655339/165971941-663eccdd-4a56-49b3-b6d6-9ed1d2382870.png">

During the research, I found that the metric does not have an `image` label, which is the request:

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/32655339/165972130-f4ed549b-225c-4a86-8040-1ea537e57a0c.png">

I also found the following config in values ([link](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml#L712)): 

```yaml
    metricRelabelConfigs:
      - action: labeldrop
        regex: (uid)
      - action: labeldrop
        regex: (id|name|image)
      - action: drop
        source_labels: [__name__]
        regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
```

It can be seen that the label `image` is removed, which is why the dashboard does not work.

If you change this config to the following, then everything works:

```yaml
        metricRelabelConfigs:
          - action: labeldrop
            regex: (uid)
          - action: labeldrop
            regex: (id|name)
          - action: drop
            source_labels: [ __name__ ]
            regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
```

Graph displayed:

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/32655339/165972906-c1dadb40-b785-4034-83b6-9191198cce82.png">

Does this mean the default values need to be changed to fix this issue
