### ISSUE TITLE
Stack VMAgent resources settings not in values

### ISSUE THREAD

**Issue by morphalus** [VictoriaMetrics/helm-charts#328]
Hi,

I wanted to raise the values of resource requests and limit for the vmagent in stack mode. I did not find how to do this so I fell on [this issue](https://github.com/VictoriaMetrics/helm-charts/issues/130#issuecomment-829957305) which explains we have to add `resources` under ` spec` as shown in `values.yaml` but I don't see anything about it, neither in the [agent template](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmagent.yaml).

Is this a missing piece or did I misunderstand something?

**Comment by Haleygo** [comment]
As far as I know, it can be configured under vmagent.Spec
https://github.com/VictoriaMetrics/helm-charts/blob/659a1d6d4eb35f5dbdd8c539c376cdbcbc60b1c9/charts/victoria-metrics-k8s-stack/values.yaml#L106-L112
Like
```
# -- Configures vmsingle params
vmsingle:
  annotations: {}
  enabled: true
  # spec for VMSingle crd
  # https://docs.victoriametrics.com/operator/api.html#vmsinglespec
  spec:
    resources:
      limits:
        cpu:
        mem:
```

**Comment by ansromanov** [comment]
@Haleygo Thank you, this works for me.

```
vmagent:
  spec:
    resources:
      limits: {}
      requests: {}
```
