### ISSUE TITLE
Label for statefulset  more than 63 characters

### ISSUE THREAD

**Issue by artemsre** [VictoriaMetrics/helm-charts#34]
When helm release name longer than 17 chars the error happens: 

`create Pod victoriametrics-gcp-stg-victoria-metrics-cluster-vmstorage-0 in StatefulSet victoriametrics-gcp-stg-victoria-metrics-cluster-vmstorage failed error: Pod "victoriametrics-gcp-stg-victoria-metrics-cluster-vmstorage-0" is invalid: metadata.labels: Invalid value: "victoriametrics-gcp-stg-victoria-metrics-cluster-vmstorage-5dcccc548": must be no more than 63 characters`

I am not sure is it ok.  

For me is not a problem to use short name.

**Comment by tenmozes** [comment]
thanks will fix that

**Comment by kazukousen** [comment]
I had that happens too.

I changed releaseName to be shorter.
it seems to be working so far.

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: monitoring
spec:
  helmVersion: v3
  releaseName: vm
  targetNamespace: monitoring
  chart:
    repository: https://victoriametrics.github.io/helm-charts/
    name: victoria-metrics-cluster
    version: 0.5.9
    appVersion: 1.36.2
```
