### ISSUE TITLE
victoria-metrics-k8s-stack Helm chart creates duplicate vmservicescrape for grafana and node-exporter owned by subcharts

### ISSUE THREAD

**Issue by brokenjacobs** [VictoriaMetrics/helm-charts#352]
"owned by dependent chart:"
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  annotations:
    meta.helm.sh/release-name: vm-stack
    meta.helm.sh/release-namespace: vm-system
  creationTimestamp: "2022-07-27T16:19:55Z"
  generation: 1
  labels:
    app: prometheus-node-exporter
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-node-exporter-3.3.1
    helm.toolkit.fluxcd.io/name: vm-stack
    helm.toolkit.fluxcd.io/namespace: flux-system
    heritage: Helm
    jobLabel: node-exporter
    release: vm-stack
  name: vm-stack-prometheus-node-exporter
```
Owned by main chart:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  annotations:
    meta.helm.sh/release-name: vm-stack
    meta.helm.sh/release-namespace: vm-system
  creationTimestamp: "2022-07-27T16:18:23Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: vm-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: 1.79.0
    helm.sh/chart: victoria-metrics-k8s-stack-0.10.2
    helm.toolkit.fluxcd.io/name: vm-stack
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: vm-stack-victoria-metrics-k8s-stack-node-exporter
```

It does this for both the grafana and node-exporter vmservicescrape's. I don't know why... but it leads to duplicate metrics in the VM because the job labels are different.
