### ISSUE TITLE
vmalert can't use vmagent as a proxy relay for multiple remote_writes

### ISSUE THREAD

**Issue by brokenjacobs** [VictoriaMetrics/helm-charts#358]
As documented here:
https://docs.victoriametrics.com/vmalert.html#multiple-remote-writes

I want to use vmagent to proxy my vmalert remote_write to multiple destinations. But the helm chart doesn't allow overriding the remote_write destination for vmalert:
https://github.com/VictoriaMetrics/helm-charts/blob/b130be84e99ac1584289dfc3ee9eeb59b154a94a/charts/victoria-metrics-k8s-stack/templates/_helpers.tpl#L113
https://github.com/VictoriaMetrics/helm-charts/blob/b130be84e99ac1584289dfc3ee9eeb59b154a94a/charts/victoria-metrics-k8s-stack/templates/_helpers.tpl#L151

I would suggest a setting for vmalert like:
```.Values.vmalert.useAgentForRemoteWrite (bool)```

and then:
```
{{/*
  for VMAlert remote
*/}}
{{- define "victoria-metrics-k8s-stack.vmInsertEndpoint" -}}
{{- if ..Values.vmalert.useAgentForRemoteWrite -}}
... put the vmagent address in ...
{{- else if .Values.vmsingle.enabled -}}
{{ include "victoria-metrics-k8s-stack.vmSingleInsertEndpoint" . }}
{{- else if .Values.vmcluster.enabled -}}
{{ include "victoria-metrics-k8s-stack.vmClusterInsertEndpoint" . }}
{{- end }}
{{- end }}
{{- end }}
```

**Comment by k1rk** [comment]
@brokenjacobs hi
as of now you can override remotewrite url for VMAlert through spec
```
vmalert:
  spec:
    remoteWrite:
      url: <vm-agent-service-url>
```

we will also add flag to enable this in chart

**Comment by brokenjacobs** [comment]
This doesn't appear to be what the changes do, it looks like you can add .Values.vmagent.additionalRemoteWrites to the helm spec but not override the single remotewrite (which means I would have to enable deduplication in my vmsingle instance).
https://github.com/VictoriaMetrics/helm-charts/blob/3934ec8139cacc8f1e565a1e97ce756a0b854755/charts/victoria-metrics-k8s-stack/templates/_helpers.tpl#L166

I just tested the proposed change above and it does not work in the latest victoria-metrics-k8s-stack chart.

**Comment by brokenjacobs** [comment]
```yaml
    vmalert:
      spec:
      # Send metrics to vmalert as a proxy to remote_write to gcp
      remoteWrite:
        url: http://vmagent-vm-stack-victoria-metrics-k8s-stack.vm-system.svc:8429
```

Logs still show vmalert connecting to vmsingle endpoint. victoria-metrics-k8s-stack chart version 0.12.1

**Comment by brokenjacobs** [comment]
I THINK this will work though:
```yaml
    vmalert:
      spec:
      # Send metrics to vmalert as a proxy to remote_write to gcp
      extraArgs:
        remotewrite.url: http://vmagent-vm-stack-victoria-metrics-k8s-stack.vm-system.svc:8429
```
