### ISSUE TITLE
[Question][vmagent] How do I add more scrape scrape_configs?

### ISSUE THREAD

**Issue by yelinaung** [VictoriaMetrics/helm-charts#364]
Hello, 

Thanks for creating the VictoriaMetrics and the Helm Chart.

### Context
I installed all the components with [VM kubernetes monitoring stack](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack).
```bash
NAME      NAMESPACE       REVISION   UPDATED                                 STATUS     CHART                                   APP VERSION
dev-vm    monitoring      3          2022-08-24 12:10:32.597133858 +0800 +08 deployed   victoria-metrics-k8s-stack-0.11.1       1.80.0
```

I've separated the `values.yaml` into main_components and others. This is my main_components values
https://gist.github.com/yelinaung/d10dfdce774cb641d5d70bf68aca791a

Now, I have setup Istio in my cluster to collect other metrics about my applications.
Istio comes with its [own Prometheus ](https://istio.io/latest/docs/ops/best-practices/observability/#using-prometheus-for-production-scale-monitoring)so I am trying to scrape Istio's Promethues with vmagent.

I am having a difficult time trying to figure how can I add more scrape config to the `vmagent`. 

I saw that the scrape config to the container
```yaml
  vmagent:
    Container ID:  containerd://bd6237a16a1980996b916a2dc95ad6c9feaf79962cfa457ac39a519ea0899147
    Image:         victoriametrics/vmagent:v1.80.0
    Image ID:      docker.io/victoriametrics/vmagent@sha256:34b159b8bb8ea0794348d555ea747fea779f8f75e7fa4230eb2dccc0c3711534
    Port:          8429/TCP
    Host Port:     0/TCP
    Args:
      -httpListenAddr=:8429
      -promscrape.config=/etc/vmagent/config_out/vmagent.env.yaml
```
But I am not sure how I can sideload my own config. e.g
```yaml
- job_name: 'istio-prometheus'
  honor_labels: true
  metrics_path: '/federate'
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names: ['istio-system']
  metric_relabel_configs:
  - source_labels: [__name__]
    regex: 'workload:(.*)'
    target_label: __name__
    action: replace
  params:
    'match[]':
    - '{__name__=~"workload:(.*)"}'
    - '{__name__=~"pilot(.*)"}'
```

I've gone through the documentation and saw that there is [a way to load multiple](https://docs.victoriametrics.com/vmagent.html#loading-scrape-configs-from-multiple-files) scrape configs but not sure how I can do that with Helm.

Thanks!

**Comment by nvtkaszpir** [comment]
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-agent/values.yaml#L557

**Comment by yelinaung** [comment]
@nvtkaszpir Thanks for the reply!

In my case, I installed the `vmagent` as part of the [Helm Chart For Victoria Metrics kubernetes monitoring stack](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack) and I cannot find similar config for `extraScrapeConfigs`.

Maybe I should disable the `vmagent` from that Helm chart and install the `vmagent` with the values you posted above.

**Comment by nvtkaszpir** [comment]
you can try to set vmagent.spec.inlineScrapeConfig as a yaml section or use vmagent.spec.additionalScrapeConfigs to point to a externally created secret with additional scrape config.

https://docs.victoriametrics.com/operator/additional-scrape.html for more details

https://docs.victoriametrics.com/operator/api.html#vmagentspec for specification of the CRD

**Comment by yelinaung** [comment]
I've tried the examples from the links you've sent above but had a hard time making it up and running.

What I end up doing is setting up another `vm-agent` with the standalone vm-agent helm chart and scrape the custom config with `extraScrapeConfigs`. That seems to be working fine for me.

Thanks for the help and please feel free to close the issue!

**Comment by air3ijai** [comment]
This is how we can use a copy/paste from Prometheus config
```yaml
vmagent:
  # https://docs.victoriametrics.com/operator/api.html#vmagentspec
  spec:
    inlineScrapeConfig: |
      - job_name: kubernetes-pods
        honor_labels: true
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - action: keep
          regex: true
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_scrape
        - action: drop
          regex: true
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow
        - action: replace
          regex: (https?)
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_scheme
          target_label: __scheme__
        - action: replace
          regex: (.+)
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_path
          target_label: __metrics_path__
        - action: replace
          regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
          replacement: '[$2]:$1'
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_port
          - __meta_kubernetes_pod_ip
          target_label: __address__
        - action: replace
          regex: (\d+);((([0-9]+?)(\.|$)){4})
          replacement: $2:$1
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_port
          - __meta_kubernetes_pod_ip
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
          replacement: __param_$1
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: pod
        - action: drop
          regex: Pending|Succeeded|Failed|Completed
          source_labels:
          - __meta_kubernetes_pod_phase
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: node
```
