### ISSUE TITLE
[victoria-metrics-k8s-stack] kube-state-metrics won't scraped if $ARGOCD_APP_NAME is used

### ISSUE THREAD

**Issue by h5vx** [VictoriaMetrics/helm-charts#367]
1. I deploy the stack with ArgoCD, so, according to [values.yaml](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml)...
   
    ```yaml
    # -- For correct working need set value 'argocdReleaseOverride=$ARGOCD_APP_NAME'
    argocdReleaseOverride: ""
    ```
     ... I have set `argocdReleaseOverride: "$ARGOCD_APP_NAME"` in values

1. Variable substition is working with labels, but in vmagent's config it is placed **literally**:

    ```yaml
    - job_name: serviceScrape/victoria-metrics/vm-victoria-metrics-k8s-stack-kube-state-metrics/0
      honor_labels: true
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
        regex: $ARGOCD_APP_NAME
        action: keep
    ```

1. So, kube-state-metrics isn't shown up in scrape targets. After "manual variable substitution" it works fine:`argocdReleaseOverride: "victoria-metrics"`

I still doesn't sure if that is a bug or I misunderstood something
