### ISSUE TITLE
Unable to update resources for vmstorage on a deployed victoria-metrics-k8s-stack

### ISSUE THREAD

**Issue by ahsang** [VictoriaMetrics/helm-charts#372]
Hi 
I am using fluxcd to deploy this helmchart
The problem is if i update vmstorage resources (memory or cpu) on an existing deployment, it fails to update the pods
Here is my chart definition:
```
chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: vm-stack
        namespace: flux-system
  values:
    defaultRules:
      create: false
    vmsingle:
      enabled: false
    vmcluster:
      enabled: true
      spec:
        vminsert:
          extraArgs:
            maxLabelsPerTimeseries: "80"
        vmstorage:
          storageDataPath: "/vm-data"
          storage:
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 100Gi
          resources:
            limits:
              cpu: "1"
              memory: 2600Mi
        vmselect:
          resources:
            limits:
              cpu: "2"
              memory: "2000Mi"
```
While inspecting the cluster if i navigate to the vmcluster crd here is the output of the vm-operator

```
{"level":"error","ts":1662416798.0692394,"msg":"Reconciler error","controller":"vmcluster","controllerGroup":"operator.victoriametrics.com","controllerKind":" │
│ VMCluster","vMCluster":{"name":"victoria-metrics-vm","namespace":"monitoring"},"namespace":"monitoring","name":"victoria-metrics-vm","reconcileID":"b718cee4-f │
│ f6e-4d4e-9a6a-c87dd95f9d3b","error":"failed create or update vmcluster: cannot perform update on sts: vmstorage-victoria-metrics-vm, err: StatefulSet.apps \"v │
│ mstorage-victoria-metrics-vm\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy' and 'mi │
│ nReadySeconds' are forbidden","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller │
│ -runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/ │
│ controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
```
