### ISSUE TITLE
Ingress to VM Single server is not working

### ISSUE THREAD

**Issue by hrbapna** [VictoriaMetrics/helm-charts#375]
I am using  [victoria-metrics-k8s-stack](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack) and configuring ingress to divert requests at /vicm to the VM's main page. Unable to reach to VMSingle using http://localhost/vicm
In the same setup, I also have prometheus running (for some comparison purpose). The same ingress manifest works on it. http://localhost/prometheus works. Can someone provide me pointers on what am I doing wrong?
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/component: victoria-metrics-k8s-stack-vmsingle
    app.kubernetes.io/instance: victoriametrics
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: 1.81.1
    argocd.argoproj.io/instance: victoriametrics
    helm.sh/chart: victoria-metrics-k8s-stack-0.12.1
  name: vmsingle-vm
  namespace: monitoring
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: vmsingle-vm
                port:
                  number: 8429
            path: /vicm
            pathType: Prefix
```

The below config works.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: prometheus-prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/version: 34.0.0
    argocd.argoproj.io/instance: prometheus
    chart: kube-prometheus-stack-34.0.0
    heritage: Helm
    release: prometheus
  name: prometheus-prometheus
  namespace: monitoring
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: prometheus-prometheus
                port:
                  number: 9090
            path: /prometheus
            pathType: ImplementationSpecific
```
