### ISSUE TITLE
How to write scrape config for Kyverno in victoria metrics?

### ISSUE THREAD

**Issue by jyotibhanot** [VictoriaMetrics/helm-charts#377]
Hi Team,

I have integrated Kyverno (https://kyverno.io/docs/introduction/) and Policy Reporter (https://kyverno.github.io/policy-reporter/guide/helm-chart-core/#enable-metrics-endpoint) in EKS cluster in AWS 

I have enabled policy reporter metric endpoint and can do the curl from a pod using endpoint curl http://x.x.x.x:8080/metrics

Vmagent is running on a pod. How can I write scrap config for this endpoint. Can someone help

**Comment by denisgolius** [comment]
Hi @jyotibhanot !

You can try the next config:

```yaml
remoteWriteUrls:
   - http://your-remote-write-victoriametrics-url

config:
  global:
    scrape_interval: 10s

  scrape_configs:
    - job_name: vmagent
      static_configs:
        - targets: ["localhost:8429"]
    - job_name: policy-reporter
      static_configs:
        - targets: ["policy-reporter:8080"]
```
See also https://docs.victoriametrics.com/guides/k8s-monitoring-via-vm-cluster.html#3-install-vmagent-from-the-helm-chart
