### ISSUE TITLE
Can't declare VMAgent service type as LoadBalancer

### ISSUE THREAD

**Issue by littlecatherine** [VictoriaMetrics/helm-charts#389]
Once I enabled graphitePort=2003 on VMAgent, I can't declare its service type as LoadBalancer. Error msg "may not contain more than 1 protocol when type is 'LoadBalancer'", because graphite protocol listens to both UDP and TCP port by default. 

It would be nice at least to have the capability to customize the ports on service.

**Comment by ahsang** [comment]
```
vmagent:
      spec:
        serviceSpec:
          spec:
            type: LoadBalancer
```
This will create an additional service and in the spec where i have mentioned type it supports all the parameters of the a normal kubenetes sevice manifest
https://docs.victoriametrics.com/operator/api.html#servicespec
