### ISSUE TITLE
is it possible to have more than one vmagent inside one cluster?

### ISSUE THREAD

**Issue by bijancot** [VictoriaMetrics/helm-charts#392]
Hi everyone, so i have some case that vmagent become so big and use so many resources. So the question is, is it possible to make replica of it and distribute usage to separate container?

Thank you so much!

**Comment by f41gh7** [comment]
Hello, yes it  possible with cluster mode. 

```yaml
statefulset:
  enabled: true
  # -- create cluster of vmagents. See https://docs.victoriametrics.com/vmagent.html#scraping-big-number-of-targets
  # available since 1.77.2 version https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.77.2
  clusterMode: true
```

 In this case, scrape targets will be distributed between vmagent replicas https://docs.victoriametrics.com/vmagent.html#scraping-big-number-of-targets
