### ISSUE TITLE
`enabled` value not honored with vmcluster

### ISSUE THREAD

**Issue by mbrancato** [VictoriaMetrics/helm-charts#426]
While debugging a conflict, I applied the latest `victoria-metrics-k8s-stack` with the values below (basically everything disabled), but a `vmcluster` was created with 2 replicas for `vminsert`, `vmselect`, and `vmstorage` - as well as PVCs were created.

values.yaml
```yaml
tenant: "0"

victoria-metrics-operator:
  enabled: false

defaultRules:
  create: false

defaultDashboardsEnabled: false

experimentalDashboardsEnabled: false

vmsingle:
  enabled: false

vmcluster:
  enabled: false

alertmanager:
  enabled: false

vmalert:
  enabled: false

vmagent:
  enabled: false

grafana:
  enabled: false

prometheus-node-exporter:
  enabled: false

kube-state-metrics:
  enabled: false

kubelet:
  enabled: false

kubeApiServer:
  enabled: false

kubeControllerManager:
  enabled: false

kubeDns:
  enabled: false

coreDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false
```
