### ISSUE TITLE
k8s-stack: Use many notifiers for vmalert

### ISSUE THREAD

**Issue by zvlb** [VictoriaMetrics/helm-charts#431]
Chart version: 0.12.*

I want to use 2 notifiers for vmalert.
I try many variants:
1. Classic:
```yaml
  vmalert:
    spec:
       notitfiers:
        - url: "alertnamager1"
        - url: "alertnamager2"
```
But after `helm install` in CR vmalert I see only 1 notifier. 

2. With ExtraArgs:
1. Classic:
```yaml
  vmalert:
    spec:
       notitfier:
         url: "alertnamager1"
       extraArgs:
         notifier.url: "alertnamager2"
```
After `helm install` in CR vmalert I see something like:
```yaml
  spec:
    extraArgs:
      notifier.url: "alertnamager2"
    notitfier:
      url: "alertnamager1"
```
but in finish Deployment ib args exist only alertnamager2

---
I was able to set it up to make it work& But I think its not obvious
```yaml
  vmalert:
    spec:
       extraArgs:
         notifier.url: "alertnamager1,alertnamager2"
```

I think the problem [here](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/templates/_helpers.tpl#L114)

**Comment by proffust** [comment]
You must define notifiers with port number and full name, for example working configuration
```
    notifiers:
      - url: http://vmalertmanager-victoria-metrics-k8s-stack-0.vmalertmanager-victoria-metrics-k8s-stack:9093
      - url: http://vmalertmanager-victoria-metrics-k8s-stack-1.vmalertmanager-victoria-metrics-k8s-stack:9093
```

**Comment by virtualb0x** [comment]
Hi! 

Can't understand how it suppose to be working. Can anybody explain it to me?

I want vmalert to have 2 notifier.urls which are endpoint of pods of alertmanager

Helm chart applies headless service for VMalertmanager. This service points to both (I have 2) pods of alertmanager.
My efforts to list urls in notifiers failed, because I have to apply two services, one for each pod. 

I also tried to apply several alertmanager pods as urls in notifier as a selector, but it didnt work for me

```
    notifier:
      selector:
        namespaceSelector:
          any: true
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: vmalertmanager
```
But in vmagent pod I can see only:
-notifier.url="http://vmalertmanager-victoria.victoriametrics.svc:9093"

Also I wanted to do it via notifierConfigRef as it mentioned here https://docs.victoriametrics.com/operator/api.html#vmalertspec 

but helm told me it doesnt kow it
```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(VMAlert.spec): unknown field "notifierConfigRef" in com.victoriametrics.operator.v1beta1.VMAlert.spec
```

So I cant find tiny solution but for handmade 2 svc pointing to each pod
