### ISSUE TITLE
Ability to Specify Basic Auth for remoteWriteUrls for VM Agent

### ISSUE THREAD

**Issue by silverbp** [VictoriaMetrics/helm-charts#44]
Currently there doesn't seem to be a way to specify basic auth creds for remoteWriteUrls of the VM Agent.

**Comment by tenmozes** [comment]
Hi @silverbp you can use `extraArgs` for that and specify username and password pair 
example 
```yaml
extraArgs:
  "remoteWrite.basicAuth.password": foo
  "remoteWrite.basicAuth.username": bar
```

**Comment by f41gh7** [comment]
extraArgs and extraEnv allows to specify any combinations of basicAuth params. 

 Note, with extra args you have to put it in one line:
```yaml
extraArgs:
  "remoteWrite.basicAuth.password":  rw-1-password,rw-2-password
  "remoteWrite.basicAuth.username": rw-1-user,rw-2-user
```
