### ISSUE TITLE
vm-single nodeport not work

### ISSUE THREAD

**Issue by cataglyphis** [VictoriaMetrics/helm-charts#441]
chart version: 1.86.1

1. set server type to `NodePort`, and set nodePort to 30000
2. `helm install vmsingle vm/victoria-metrics-single -f values.yaml -n n9e` to install vmsingle chart
3. no `NodePort` in svc config

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/9249983/211789800-31504859-a862-44f9-8124-3c6fab2174b7.png">

```
  service:
    # -- Service annotations
    annotations: {}
    # -- Service labels
    labels: {}
    # -- Service ClusterIP
    clusterIP: ""
    # -- Service External IPs. Ref: [https://kubernetes.io/docs/user-guide/services/#external-ips]( https://kubernetes.io/docs/user-guide/services/#external-ips)
    externalIPs: []
    # -- Service load balacner IP
    loadBalancerIP: ""
    # -- Load balancer source range
    loadBalancerSourceRanges: []
    # -- Service port
    servicePort: 8428
    # -- Node port
    nodePort: 30000
    # -- Service type
    # type: ClusterIP
    type: NodePort
```
