### ISSUE TITLE
[k8s-stack] small inaccuracy in the VMagent remoteWrite URL generation

### ISSUE THREAD

**Issue by b-a-t** [VictoriaMetrics/helm-charts#450]
Hi again,

Looking through the generated manifests I persistently stumble upon doubled `//` in the `remoteWrite` URL:
```yaml
# Source: vm-core/charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmagent.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vm-stack
  namespace: default
...
  image:
    tag: v1.83.0
  remoteWrite:
  - url: http://vminsert-vm-stack.default.svc:8480//insert/0/prometheus/api/v1/write
  scrapeInterval: 25s
  selectAllByDefault: true
```
Surely not very harmаul, but a bit annoying("неаккуратненько"(с))

So, it looks like it all boils down to the following definition in the `_helpers.tpl`:
```yaml
{{- define "victoria-metrics-k8s-stack.vmWriteEndpoint" -}}
{{- if .Values.vmsingle.enabled -}}
url: {{ printf "http://%s.%s.svc:%s%s/api/v1/write" (include "victoria-metrics-k8s-stack.vmsingleName" .) .Release.Namespace (.Values.vmsingle.spec.port | default "8429") (index .Values "vmsingle" "spec" "extraArgs" "http.pathPrefix" | default "") }}
{{- else if .Values.vmcluster.enabled -}}
url: {{ printf "http://%s-%s.%s.svc:%s%s/insert/%s/prometheus/api/v1/write" "vminsert" (include "victoria-metrics-k8s-stack.fullname" .) .Release.Namespace (.Values.vmcluster.spec.vminsert.
port | default "8480") (index .Values "vmcluster" "spec" "vminsert" "extraArgs" "http.pathPrefix" | default "/") (.Values.tenant | default "0")  }}
{{- else if .Values.externalVM.write.url -}}
{{ .Values.externalVM.write | toYaml }}
{{- end }}
{{- end }}
```
Namely, it is this part for `vmcluster` branch:

`(index .Values "vmcluster" "spec" "vminsert" "extraArgs" "http.pathPrefix" | default "/")`

There is absolutely no need for `default "/"` here, as the following URL part also starts with `/`, so if there is nothing to say it should be `""`, otherwise the `http.pathPrefix` supposed to start with it's own `/prefix`.

Actually, for the `vmsingle` counterpart we have it exactly that way.

The same applies to the `vmReadEndpoint` obviously.
