### ISSUE TITLE
k8s-stack: vmstorage container should be able to run as not root user

### ISSUE THREAD

**Issue by andreivaloshyn** [VictoriaMetrics/helm-charts#461]
To fit security standards it's better to run `vmstorage` container as **non root** user(`nobody` for example).
Currently, it's possible to run `vmselect` and `vminsert` as user **nobody**

**Comment by martykuentzel** [comment]
Hi @andreivaloshyn 
not sure if this used to be a problem with previous version but I tried it with `victoria-metrics-cluster` `0.10.0` and it works fine for me. I added the following config to all three components:

```
    podSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      privileged: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL

    securityContext:
      runAsNonRoot: true
      runAsUser: 65534 # user nobody
      runAsGroup: 65534
      fsGroup: 65534
```
