### ISSUE TITLE
Support tmpfs for /cache dir on vmselect

### ISSUE THREAD

**Issue by matej-bellus-w** [VictoriaMetrics/helm-charts#462]
Currently when I tried to set tmpfs like this via `values.yml`

```
  extraVolumes:
    - name: cache-tmpfs
      emptyDir:
        medium: "Memory"
        sizeLimit: 50Mi

  extraVolumeMounts:
    - name: cache-tmpfs
      mountPath: /cache

  cacheMountPath: /cache
```

It says:
`spec.template.spec.containers[0].volumeMounts[1].mountPath: Invalid value: "/cache": must be unique`

This is the [line.
](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml#L143)
