### ISSUE TITLE
Charts appear to lack any TLS cert-related config options

### ISSUE THREAD

**Issue by XANi** [VictoriaMetrics/helm-charts#475]
`vmalert` for example have a whole slew of `remoteWrite.tls*` options yet there doesn't seem to be a way to pass it via helm config to fill the k8s config. In our particular case I have internal CA which all internal services use and want to pass it a key

**Comment by AndrewChubatiuk** [comment]
Hey @XANi. We're usually adding new properties to a spec which simplify setup a lot, like `streamAggrConfig`, which generates config map with a data from parameter, provides validation of this config and adds respective volumemount configs and cmd flags. We do not add to properties flags, which are just straightforwardly converted into cmd args only, like in case of `remoteWrite.tls*`. You can add these flags using `extraArgs`:
```yaml
vmalert:
  spec:
     extraArgs:
       remoteWrite.tlsCAFile: "ca1.pem,ca2.pem"  # means use ca1.pem for a first remote write and ca2.pem for a second one
```
