### ISSUE TITLE
Failure threshold too low

### ISSUE THREAD

**Issue by allen13** [VictoriaMetrics/helm-charts#48]
Recommend defining a failureThreshold greater than the default 3. https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml#L52

Large amounts of data will take longer to load. Currently it times out after 45 (15*3) seconds.

This is just a note gained from production experience. Feel free to close this task as soon as somone from the Victoria side has looked at it.

**Comment by tenmozes** [comment]
Hi @allen13  thank you, the probes configuration moved to values.yaml
```
 probe:
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 3
    liveness:
      initialDelaySeconds: 5
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 3
```
please try in in cluster version `0.5.16`
