### ISSUE TITLE
Metrics are not dropped with metric_relabel_configs

### ISSUE THREAD

**Issue by autokilla47** [VictoriaMetrics/helm-charts#481]
Install monitoring using a helm chart, enabled scraping for kubelet and cadvisor, but with the standard `metricRelabelConfigs`, the merics doesn't drop.
```
    # drop high cardinality label and useless metrics for cadvisor and kubelet
    metricRelabelConfigs:
      - action: labeldrop
        regex: (uid)
      - action: labeldrop
        regex: (id|name)
      - action: drop
        source_labels: [__name__]
        regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
```
```
- job_name: nodeScrape/monitoring/vm-k8s-stack-victoria-metrics-k8s-stack-kubelet/1
  scrape_interval: 1m0s
  scrape_timeout: 1m0s
  honor_labels: true
  scheme: https
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_node_name]
    target_label: node
  - target_label: job
    replacement: monitoring/vm-k8s-stack-victoria-metrics-k8s-stack-kubelet
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - source_labels: [__metrics_path__]
    target_label: metrics_path
  - action: replace
    source_labels: [kubernetes_io_hostname]
    target_label: host
  - action: labeldrop
    regex: (beta_kubernetes_io_arch|beta_kubernetes_io_os|kubernetes_io_arch|kubernetes_io_os|node|kubernetes_io_hostname)
  - action: replace
    source_labels: [__address__]
    target_label: instance
  - target_label: job
    replacement: kubelet
  metric_relabel_configs:
  - action: labeldrop
    regex: (uid)
  - action: labeldrop
    regex: (id|name)
  - action: drop
    source_labels: [__name__]
    regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
```
as you can see there are metrics, example this:
```
# HELP rest_client_request_duration_seconds [ALPHA] Request latency in seconds. Broken down by verb and URL.
# TYPE rest_client_request_duration_seconds histogram
rest_client_request_duration_seconds_bucket{url="127.0.0.1:6443",verb="DELETE",le="0.001"} 0
rest_client_request_duration_seconds_bucket{url="127.0.0.1:6443",verb="DELETE",le="0.002"} 0
rest_client_request_duration_seconds_bucket{url="127.0.0.1:6443",verb="DELETE",le="0.004"} 0
rest_client_request_duration_seconds_bucket{url="127.0.0.1:6443",verb="DELETE",le="0.008"} 0
rest_client_request_duration_seconds_bucket{url="127.0.0.1:6443",verb="DELETE",le="0.016"} 1
rest_client_request_duration_seconds_bucket{url="127.0.0.1:6443",verb="DELETE",le="0.032"} 5
rest_client_request_duration_seconds_bucket{url="127.0.0.1:6443",verb="DELETE",le="0.064"} 28
```
In addition, I try to drop metrics from other targets, I add `metricRelabelConfigs`, but the metrics are not droped.

victoriametrics/operator: v0.29.2 and v0.30.4
vmagent version: v1.85.1
chart version: 0.13.1
