### ISSUE TITLE
Possibility of using secret in values.yml for configs of alertmanager

### ISSUE THREAD

**Issue by virtualb0x** [VictoriaMetrics/helm-charts#483]
Hello!

I'm using [victoria-metrics-k8s-stack](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack)

I want to know if it is possible to use secret value in value.yaml for telegram_config

Now I have such a config
```
      - name: default-telegram
        telegram_configs:
        - api_url: https://api.telegram.org
          bot_token: "STRING WITH TOKEN"
          chat_id: -123345678
          disable_notifications: false
          http_config:
            follow_redirects: true
          send_resolved: true
          message: '{{ template "telegram.default" .}}'
``` 
I would like to understand if i can user somehow secret data in bot_token value

IN CRD  https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/crds/crd.yaml#L3688  
there is description of some Secret or their values and some boolen options, but it still quite not clear for me, because futher HELM converts config to [Secret](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/vmalertmanager.yaml)  as is

Can you plz explain how it works and what should I do to make this field more secure in values.yaml file?

#question #alertmanager
