### ISSUE TITLE
Add possibility for remote write relabel config 

### ISSUE THREAD

**Issue by joyartoun** [VictoriaMetrics/helm-charts#492]
Hi,

From what I can see and read in the documentation there is no easy way through values to add relabel configs for vmagent through helm charts. This is a huge bummer. I am forced to use the operator instead of the helm charts.

Is there a way to do this without installing the operator? Could you provide an example?

I am asking because Openshift sends two of the same metrics to Victoriametrics. One is labeled with prometheus_replica and I want to be able to drop it.

**Comment by joyartoun** [comment]
@f41gh7 do you have an example? Is it for example possible to override the scrape.yml logig so I can add my own configmap and mount that in the vmagent pod?

**Comment by b-a-t** [comment]
Maybe I'm mistaken, as there are not enough details in the question itself, but based on the title here is how I configure relabeling for the remote write URL in the k8s stack:

```yaml
  vmagent:
    spec:
      externalLabels:
        cluster: 'dev'
    additionalRemoteWrites:
      - url: https://vminsert.cluster.example.com/insert/0/prometheus/api/v1/write"
        inlineUrlRelabelConfig:
          - action: keep_if_equal
            source_labels: [foo, bar]
          - action: drop_if_equal
            source_labels: [foo, bar]
```
