### ISSUE TITLE
Creating backups using the single helm chart

### ISSUE THREAD

**Issue by WyriHaximus** [VictoriaMetrics/helm-charts#50]
Been using victoriametrics for a few months now and it's absolutely a breeze to set up with these helm charts. But what I'm missing here is a way to back up to a network drive (cifs/smb in my case). Now I'd gladly add this to the helm chart with a cronjob. But up on researching this I found that the only way it seems to backup is using direct access to the data dir. Is there a way to backup metrics over TCP/UDP from another pod?

**Comment by valyala** [comment]
As I know, the `vmbackup` ma run as a sidecar in the same pod as single-node VictoriaMetrics or `vmstorage` component in cluster version. cc'ing @tenmozes for more input

**Comment by tenmozes** [comment]
actually `vmbackup` is a cli command which can not be executed like sidecar, need to demonize it and add scheduling
this is main reason why it doesn't exist in helm chart

**Comment by WyriHaximus** [comment]
> actually `vmbackup` is a cli command which can not be executed like sidecar, need to demonize it and add scheduling
> this is main reason why it doesn't exist in helm chart

Yeah this is why I was thinking about using a cronjob for it. But if it only works with file access to the data that is going to be a bit harder

**Comment by immerrr** [comment]
I think it should be possible, I am currently working on patching the helm chart to add a sidecar container to the server pod that would run `vmbackup` instance managed by crond.

Looks like `vmbackup` image is based off alpine, and according to 

https://gist.github.com/AntonFriberg/692eb1a95d61aa001dbb4ab5ce00d291 

I only need to put an incremental vmbackup invocation into `/etc/periodic/hourly` that would invoke a snapshot-creating request via curl against localhost (btw, would be a bit less moving pieces if `vmbackup` would be able to send the "create snapshot" request itself), and then put that snapshot into the `/latest` directory. And then a daily invocation of `vmbackup` would copy the `/latest` directory a daily snapshot, that script would go into `/etc/periodic/daily`.

**Comment by ulikl** [comment]
Regarding "btw, would be a bit less moving pieces if vmbackup would be able to send the "create snapshot" request itself": 
 `vmbackup` has the option "-snapshot.createURL string" to do exactly this.

**Comment by immerrr** [comment]
@ulikl ah, thank you, good to know! 

does it mean that when i pass a `-snapshotName=<local-snapshot>` to vmbackup with `-snapshot.createURL`, it will create a snapshot automatically?

**Comment by WyriHaximus** [comment]
So does this mean we wouldn't have to go with the sidecar route and could go with a pod (cronjob) instead? Is `-snapshot.createURL` the URL of VM?

**Comment by immerrr** [comment]
I think you still need a sidecar to access the volume where snapshots are created.

**Comment by WyriHaximus** [comment]
Ok wait, then how should I read:
``` -snapshot.createURL string
    	VictoriaMetrics create snapshot url. When this is given a snapshot will automatically be created during backup. Example: http://victoriametrics:8428/snaphsot/create
 ```
(From: https://victoriametrics.github.io/vmbackup.html )

I might be missing some VM knowledge how snapshots work here tbh :D

**Comment by immerrr** [comment]
This is the URL on the VictoriaMetrics (vmstorage) instance itself, that would trigger a creation of a snapshot in its corresponding data directory. If vmbackup has access to that directory, it can then send the generated file wherever you point it (S3, GCP, etc).

**Comment by WyriHaximus** [comment]
Ahhhh ok check :+1: . Yeah then it's going to be really hard not using a sidecar

**Comment by AndrewChubatiuk** [comment]
to run backups using helm charts either license is required to run vmbackup manager or as a workaround it's possible to run additional vmbackup container with cron. For `victoria-metrics-single` chart it can be added using additional variables:
```yaml
extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: vmbackup-cron
    data:
      root: |
        * * * * * /vmbackup-prod -storageDataPath=/storage -snapshot.createURL=http://localhost:8428/snapshot/create -dst=<set-preferable-snapshot-destination>
server:
  extraContainers:
    - name: vmbackup
      image: victoriametrics/vmbackup
      command: [/usr/sbin/crond]
      args:
        - -f
        - -l8
      volumeMounts:
        - name: vmbackup-cron
          mountPath: /etc/crontabs
        - name: server-volume
          mountPath: /storage
  extraVolumes:
   - name: vmbackup-cron
      configMap:
        name: vmbackup-cron
```
