### ISSUE TITLE
[victoria-metrics-k8s-stack] VM Operator ServiceMonitor generates wrong manifest.

### ISSUE THREAD

**Issue by b-a-t** [VictoriaMetrics/helm-charts#500]
I was trying to relabel all the scraped data, generated by [victoria-metrics-k8s-stack], so tried to alter VM operator `ServiceMonitor` configuration, among other changes.

```yaml
# -- configures monitoring with serviceScrape. VMServiceScrape must be pre-installed
serviceMonitor:
  enabled: false
  extraLabels: { }
  annotations: { }
  relabelings: [ ]
```

By default it is disabled, so I guess that's the reason it wasn't spotted before.

I've enabled monitor and put my own relabeling rules:

```yaml
operator:
    serviceMonitor:
      enabled: true
      extraLabels: { }
      annotations: { }
      relabelings:
        - targetLabel: origin
          action: replace
          replacement: 'vm-core'
```

And ArgoCD(which is irrelevant in this case) failed with the message:
```
error calculating structured merge diff: error building typed value from config resource: .spec.endpoints[0].relabelings: field not declared in schema
```

That's not a surprise, as `relabelings` is the field from the Prometheus Operator `ServiceMonitor`, but VM Operator installs, of course, it's own resource:

```yaml
{{- if .Values.serviceMonitor.enabled -}}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ template "vm-operator.fullname" . }}
  namespace: {{ $.Release.Namespace }}
...
spec:
  selector:
    matchLabels:
        app.kubernetes.io/name: {{ include "vm-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
...
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
          {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
{{- end }}
```
 In this case we want `relabelConfigs` [of course](https://docs.victoriametrics.com/operator/api.html#endpoint).
