### ISSUE TITLE
[vm-operator] Allow to override WATCH_NAMESPACE environment variable

### ISSUE THREAD

**Issue by Wihrt** [VictoriaMetrics/helm-charts#503]
Hello !

Currently, it is impossible to override the value of `WATCH_NAMESPACE` environment variable
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-operator/templates/deployment.yaml#L55-L56

If you want to deploy multiple operators inside your cluster, you need to re-declare the `WATCH_NAMESPACE` environment variable, and you will 2 definitions of the same variable.

```yaml
# snip ...
env:
  WATCH_NAMESPACE: my_namespace
 # snip ...
```

It will result in this :
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-vm-operator
spec:
  template:
    spec:
      containers:
        env:
        - name: WATCH_NAMESPACE
          value: my_namespace
        - name: WATCH_NAMESPACE
```        

The idea would be to have a key in values.yaml

```yaml
watchNamespace: ""
```

And inside deployment.yaml file to have something lke this.
```yaml
            - name: WATCH_NAMESPACE
              value: {{ .Values.watchNamespace | quote }}
```

I will submit a PR soon for this change.
