### ISSUE TITLE
[victoriametrics-k8s-stack] Health alerts possibly not working

### ISSUE THREAD

**Issue by b-a-t** [VictoriaMetrics/helm-charts#515]
I talked to @hagen1778 today about the case when we didn't receive any alerts in the situation when one of the rules for `vmalert` was broken and stopped the replacement pod from starting up, staying in the infinite restart loop.

Listing pods with the `kubectl` showed a few thousand restarts of the `vmalert`. Roman pointed me to the rule in the `alerts-health.yml` for the docker deployment, which is also converted to `vm-health.yaml` for K8s stack.

It looks like:

```yaml
    - alert: TooManyRestarts
      annotations:
        description: Job {{`{{`}} $labels.job {{`}}`}} (instance {{`{{`}} $labels.instance {{`}}`}}) has restarted more than twice in the last 15 minutes. It might be crashlooping.
        summary: '{{`{{`}} $labels.job {{`}}`}} too many restarts (instance {{`{{`}} $labels.instance {{`}}`}})'
      expr: changes(process_start_time_seconds{job=~"victoriametrics|vmselect|vminsert|vmstorage|vmagent|vmalert"}[15m]) > 2
      labels:
        severity: critical
```
and never was raised for us.

Trying query `process_start_time_seconds{job=~"victoriametrics|vmselect|vminsert|vmstorage|vmagent|vmalert"}` didn't give any results either.

Extending regex with `process_start_time_seconds{job=~"(victoriametrics|vmselect|vminsert|vmstorage|vmagent|vmalert|vmsingle).*"}` finally showed me:

<img width="1546" alt="image" src="https://user-images.githubusercontent.com/1394818/232613544-e043542b-382e-4a5c-a0e1-dbcdff71b8ef.png">

So, here we see that:

1. we miss `vmsingle` in the list of jobs, in docker I guess it is `victoriametrics`.
2. `jobLabel` isn't just the name of the component. It could be that this is the result of my specific setup, where I set the:
```
victoria-metrics-k8s-stack:
  nameOverride: "vm-stack"
  fullnameOverride: "vm-stack"
```
to keep the generated pod names within 63 characters limit. Still that at least have to be taken into account.
3. On the bright side `container` label seems to be exactly what we are querying for, so maybe it's more appropriate to query it.
4. The state of the Alertmanager should also be considered here - do we want to monitor it as well as part of the stack?
`container` label for it would have the value `alertmanager`, while `job` is `vmalertmanager-vm-stack`(which accidentally matches `vmalert.*` regexp).

And of course, the whole quest started cause I didn't find any rules that utilize `kube_pod_container_status_restarts` metric, which could be a more precise metric for the number of pod restarts.
