### ISSUE TITLE
vm operator not delete completely

### ISSUE THREAD

**Issue by Tri0L** [VictoriaMetrics/helm-charts#548]
## Install:
```
helm install vmoperator vm/victoria-metrics-operator -n victoria-metrics
```

## kubectl:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: main-cluster
spec:
  retentionPeriod: "12"
  vmstorage:
    replicaCount: 1
  vmselect:
    replicaCount: 1
  vminsert:
    replicaCount: 1
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
spec:
  serviceScrapeNamespaceSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  serviceScrapeSelector: {}
  nodeScrapeSelector: {}
  nodeScrapeNamespaceSelector: {}
  staticScrapeSelector: {}
  staticScrapeNamespaceSelector: {}
  replicaCount: 1
  remoteWrite:
    - url: "http://vminsert-main-cluster.victoria-metrics.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
```

## Uninstall:
```
 % helm uninstall vmoperator -n victoria-metrics               
W0601 00:38:12.060009   37573 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
release "vmoperator" uninstalled
```

## Check.
A lot of resources still exists.
```
% kubectl get all -A | grep -i vm
victoria-metrics         pod/vmagent-vmagent-7458478449-km26q                                  2/2     Running       0              41m
victoria-metrics         pod/vminsert-main-cluster-b86978644-4gkpg                             1/1     Running       0              44m
victoria-metrics         pod/vmselect-main-cluster-0                                           1/1     Running       0              44m
victoria-metrics         pod/vmstorage-main-cluster-0                                          1/1     Running       0              44m
victoria-metrics         service/vmagent-vmagent                                            ClusterIP      10.96.232.54    <none>          8429/TCP                                         41m
victoria-metrics         service/vminsert-main-cluster                                      ClusterIP      10.96.204.234   <none>          8480/TCP                                         44m
victoria-metrics         service/vmselect-main-cluster                                      ClusterIP      None            <none>          8481/TCP                                         44m
victoria-metrics         service/vmstorage-main-cluster                                     ClusterIP      None            <none>          8482/TCP,8400/TCP,8401/TCP                       44m
victoria-metrics         deployment.apps/vmagent-vmagent                                    1/1     1            1           41m
victoria-metrics         deployment.apps/vminsert-main-cluster                              1/1     1            1           44m
victoria-metrics         replicaset.apps/vmagent-vmagent-7458478449                                    1         1         1       41m
victoria-metrics         replicaset.apps/vminsert-main-cluster-b86978644                               1         1         1       44m
victoria-metrics   statefulset.apps/vmselect-main-cluster                                  1/1     44m
victoria-metrics   statefulset.apps/vmstorage-main-cluster                                 1/1     44m
```
