### ISSUE TITLE
vmselect-statefulset.yaml template in victoria-metrics-cluster Helm chart with wrong identation

### ISSUE THREAD

**Issue by trombini77** [VictoriaMetrics/helm-charts#575]
In helm chart [victoria-metrics-cluster](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-cluster) the template vmselect-statefulset.yaml in line 150:
```
{{ toYaml .Values.vmselect.persistentVolume.accessModes | indent 10}}
```
it causes a wrong identation in the chart render:
```
  volumeClaimTemplates:
    - metadata:
        name: cache-volume
      spec:
        accessModes:
                  - ReadWriteOnce
        resources:
          requests:
            storage: "2Gi"
```
if removed the `ident 10` it will looks fine.
