### ISSUE TITLE
[victoria-metrics-k8s-stack] Vmagent scrape metrics are not what you need

### ISSUE THREAD

**Issue by kdibragimov** [VictoriaMetrics/helm-charts#578]
I installed victoria-metrics-k8s-stack, made this config for my vmagent:
```
serviceScrapeSelector:
  matchLabels:
     company/prometheus: kubernetes-system
selectAllByDefault: true
serviceScrapeNamespaceSelector: {}
```
In theory, the agent should go through all namespaces and collect metrics with this label from services, but it also collects data from other sources
For example, with the flagger pod, which does not have a service at all. It's very strange. Has anyone ever encountered this?
