### ISSUE TITLE
Unable to supply multiple storageNode 

### ISSUE THREAD

**Issue by Freakin** [VictoriaMetrics/helm-charts#58]
When attempting to deploy a cluster, I am going to run `vmstorage` nodes on traditional virtual machines and running `vminsert` and `vmselect` in k8s deployed via Helm chart.

Attempting to supply multiple values for `storageNode` in `extraArgs` for either `vminsert` or `vmselect` results in only the last value being rendered with no Helm warning being thrown. This appears to be caused due to using the same key `storageNode` multiple times.

Supply this for 
```
  extraArgs:
    replicationFactor: 2
    storageNode: fqdn1.mydomain.com:8400
    storageNode: fqdn2.mydomain.com:8400
    storageNode: fqdn3.mydomain.com:8400
    storageNode: fqdn4.mydomain.com:8400
```

This results in the following for a given pod
```
Containers:
  victoria-metrics-cluster-vminsert:
    Container ID:  docker://[REDACTED]
    Image:         victoriametrics/vminsert:v1.40.0-cluster
    Image ID:      docker-pullable://victoriametrics/vminsert@sha256:d2683a56b51a560e93b3a7ed5e0bdc660b7349d99f206fb4ae4ee6627c89e366
    Port:          8480/TCP
    Host Port:     0/TCP
    Args:
      --replicationFactor=2
      --storageNode=fqdn4.mydomain.com:8400
```

I also attempted to pass in a value like `storageNode: "fqdn1.mydomain.com:8400 --storageNode=fqdn2.mydomain.com:8400 ... "` but that definitely made things quite unhappy.

Should `storageNode` be moved out of `extraArgs` and turned into an array instead that can accept multiple values?
