### ISSUE TITLE
Alertmanager's routePrefix ignored (?) in victoria-metrics-k8s-stack

### ISSUE THREAD

**Issue by arseny-zinchenko** [VictoriaMetrics/helm-charts#613]
Using the following `values.yaml`:

```
victoria-metrics-k8s-stack:

  fullnameOverride: "vm-k8s-stack"

  victoria-metrics-operator:
    serviceAccount:
      create: true
    operator:
      disable_prometheus_converter: false

  vmsingle:
    spec:
      storage:
        storageClassName: "gp2-retain"
        resources:
          requests:
            storage: 30Gi

  alertmanager:
    enabled: true
    persistence:
      enabled: true
      storageClass: "gp2-retain"
      size: 100Mi
    spec:
      routePrefix: "/alertmanager
```

After deployment, `routePrefix` in the Alertmanager's STS it's still `--web.route-prefix=/`

**Comment by Haleygo** [comment]
Can you check the `spec. routePrefix` field under VMAlertmanager object, see if it's right?
Looks right on my side
```
# Source: victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/vmalertmanager.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: release-name-victoria-metrics-k8s-stack
  namespace: default
  labels:
    app.kubernetes.io/component: victoria-metrics-k8s-stack-alertmanager
    helm.sh/chart: victoria-metrics-k8s-stack-0.17.5
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.93.0"
    app.kubernetes.io/managed-by: Helm
spec:
  externalURL: ""
  image:
    tag: v0.25.0
  routePrefix: /test
```
