### ISSUE TITLE
vmalert: adding `spec.notifier.url` creates `-notifier.url` with two URLs

### ISSUE THREAD

**Issue by arseny-zinchenko** [VictoriaMetrics/helm-charts#625]
### Describe the bug

After adding a `spec.notifier.url="http://vmalertmanager-vm-k8s-stack.dev-monitoring-ns.svc:9093/alertmanager"` to specify a new Alertmanager's URL, VMAlert has `-notifier.url=http://vmalertmanager-vm-k8s-stack.dev-monitoring-ns.svc:9093,http://vmalertmanager-vm-k8s-stack.dev-monitoring-ns.svc:9093/alertmanager`

This results to a lot of messages:
> failed to send alerts to addr "http://vmalertmanager-vm-k8s-stack.dev-monitoring-ns.svc:9093/api/v2/alerts": invalid SC 404 from "http://vmalertmanager-vm-k8s-stack.dev-monitoring-ns.svc:9093/api/v2/alerts"; response body: 404 page not found 

### To Reproduce

Deploy VMAuth from the victoria-metrics-auth Helm chart v ~0.3.3.

Add to its `values.yaml` a new URL:

```
  vmalert:
    annotations: {}
    enabled: true
    spec:  
      notifier:
        url: "http://vmalertmanager-vm-k8s-stack.dev-monitoring-ns.svc:9093/alertmanager"
```

Deploy, and check corresponding Pod:

```
$ kk -n dev-monitoring-ns describe pod vmalert-vm-k8s-stack-554b89cdc5-96d59
...
Containers:
  vmalert:
    Container ID:  containerd://27a95f37d49d3dce175f3bba661d88779d3c7b813560405eeaf58a03bff15dda
    Image:         victoriametrics/vmalert:v1.93.0
    ...
    Args:
      -datasource.url=http://vmsingle-vm-k8s-stack.dev-monitoring-ns.svc:8429/
      -evaluationInterval=15s
      -httpListenAddr=:8080
      -notifier.url=http://vmalertmanager-vm-k8s-stack.dev-monitoring-ns.svc:9093,http://vmalertmanager-vm-k8s-stack.dev-monitoring-ns.svc:9093/alertmanager
      -remoteRead.url=http://vmsingle-vm-k8s-stack.dev-monitoring-ns.svc:8429/
...
```

### Version

`Image:         victoriametrics/vmalert:v1.93.0`

### Screenshots

![Screenshot_20230823_175328](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/132904972/24c83615-1e3d-4c8b-90df-0f088aa50ee0)

**Comment by Haleygo** [comment]
If you are using victoria-metrics-k8s-stack chart, the `vmalert.server` you have is invalid since victoria-metrics-alert is not victoria-metrics-k8s-stack's dependency.
```
  vmalert:
    annotations: {}
    enabled: true
    server:
      notifier: 
        alertmanager: 
          url: "http://vmalertmanager-vm-k8s-stack.dev-monitoring-ns.svc:9093/alertmanager" 
```

You should just use `notifier`,`notifiers` or `notifierConfigRef ` under [vmalert.spec](https://github.com/VictoriaMetrics/helm-charts/blob/fix-vmalert-notifier-check/charts/victoria-metrics-k8s-stack/values.yaml#L515).
And the `-notifier.url=http://vmalertmanager-vm-k8s-stack.dev-monitoring-ns.svc:9093` you saw is the default notifier from [another template](https://github.com/VictoriaMetrics/helm-charts/blob/fix-vmalert-notifier-check/charts/victoria-metrics-k8s-stack/templates/_helpers.tpl#L126), it will be used when .Value.vmalert.spec.notifiers is empty, see merge logic [here](https://github.com/VictoriaMetrics/helm-charts/blob/e36d247c1a69d08579d394d003101da1c4fda2f3/charts/victoria-metrics-k8s-stack/templates/_helpers.tpl#L156).
https://github.com/VictoriaMetrics/helm-charts/blob/e36d247c1a69d08579d394d003101da1c4fda2f3/charts/victoria-metrics-k8s-stack/templates/_helpers.tpl#L156
