### ISSUE TITLE
VictoriaMetricsLogs Single Server - ServiceMonitor and Authentication

### ISSUE THREAD

**Issue by m4rc3l-h3** [VictoriaMetrics/helm-charts#644]
Hello and tank you for providing & maintaining this project.
I am new to VictoriaMetricsLogs (VML) and setup an instance yesterday using Helm chart (v. 0.3.0), with, among others, the following configuration:

``` yaml
server:
  enabled: true
  name: server
  image:
    repository: victoriametrics/victoria-logs
    tag: "v0.3.0-victorialogs"
    ...
  ...
  extraArgs:
    envflag.enable: "true"
    ...
    httpAuth.username: "redacted"
    httpAuth.password: "redacted"
  ...
  serviceMonitor:
    enabled: true
```

As I received a 401 response in Prometheus, I patched the `serviceMonitor` created by the Helm chart for testing purposes with the following patch:

``` yaml
spec:
  endpoints:
  - basicAuth:
      password:
        key: password
        name: vml-auth
      username:
        key: username
        name: vml-auth
```

As I was manually creating the `secret` referenced in the `serviceMonitor` I realized that Prometheus could successfully scrap metrics although the `secret` hasn't been deployed yet. However, after deploying the `secret` with th base64 encoded secrets used for sucessfully authentication in the web ui, Prometheus showed a 401 response again.
Is that an expected behavior? 

BTW: It would be great if adding basicAuth to the `serviceMonitor` could be included in the Helm chart. If I can help with that, please let me know.
