### ISSUE TITLE
Scrape pod labels and get it to Grafana

### ISSUE THREAD

**Issue by urupaud** [VictoriaMetrics/helm-charts#673]
Hello,

I'm using victoria-metrics-k8s-stack(https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack) and I'm trying to scrape the labels from the pods running in my namespaces and display it on Grafana. I've already added the following config to the kube-state-metrics, however, I'm still unable to the see the labels in vmagent or grafana. Could you please advise on this?.

kube-state-metrics:
  enabled: true
  ## all values for kube-state-metrics helm chart can be specified here

  extraArgs:
    - --metric-labels-allowlist=pods=[app.kubernetes.io/appgroup],deployments=[app.kubernetes.io/appgroup]

**Comment by Haleygo** [comment]
Hello!
The `extraArgs` looks ok to me. Can you confirm raw data from kube-state-metrics side, see if the metrics already reserve the labels that you want
```
curl {{ksm-address}}:8080/metrics
```

**Comment by paltaa** [comment]
Hey, im having an issue with the same config not working with kube-state-metrics, ive tried:

```
kube-state-metrics:
  enabled: true
  ## all values for kube-state-metrics helm chart can be specified here

  # spec for VMServiceScrape crd
  # https://docs.victoriametrics.com/operator/api.html#vmservicescrapespec
  vmServiceScrape:
    spec: {}

  #TODO: selector override for kube-state-metrics deployed separatelly
  # Add pod labels to metrics, then used for alert routing with alertmanager
  metric-labels-allowlist:
  - pods=[*]
```

and:

```
kube-state-metrics:
  enabled: true
  ## all values for kube-state-metrics helm chart can be specified here

  # spec for VMServiceScrape crd
  # https://docs.victoriametrics.com/operator/api.html#vmservicescrapespec
  vmServiceScrape:
    spec: {}

  #TODO: selector override for kube-state-metrics deployed separatelly
  # Add pod labels to metrics, then used for alert routing with alertmanager
  extraArgs:
    metric-labels-allowlist=pods=[*]
```
According to the docs any of those should work but none of them is. Is this related to the subchart, chart names with hyphens issue?
