### ISSUE TITLE
How to use replicationFactor in helm charts

### ISSUE THREAD

**Issue by Alon-Katz** [VictoriaMetrics/helm-charts#69]
Hey,

How can I give replicationFactor to vminsert pods? Should I add it in the extraArgs field in vminsert and then also add -dedup.minScrapeInterval=1ms in extraArgs for vmselect?

Thanks!

**Comment by tenmozes** [comment]
yeap, you can use extraArgs and specify this params 
```
vmselect:
  extraArgs:
    "dedup.minScrapeInterva": 1ms

vminsert:
  extraArgs:
    replicationFactor: 2

```
