### ISSUE TITLE
labels "cluster" in alerts rules, several k8s clusters

### ISSUE THREAD

**Issue by schechev-a** [VictoriaMetrics/helm-charts#709]
Hello
Maybe this is a simple question and you can help me quickly.
I have 3 kuburnetes clusters
I launched the version: 
- name: victoria-metrics-k8s-stack
  repository: https://victoriametrics.github.io/helm-charts/
  version: 0.17.6

Only vm-agent and exporters are installed on 2 clusters

On the main I have a stack: select, insert, storage
Also vmalert and alertmanager

Structure:
vm-agent_1
vm-agent_2 --> vm-insert -> vm-storage -> vm-select -> vm-alert -> vm-alertmanager -> oncall
vm-agent_3

-------------
### **_When I receive alerts I don't see the "cluster":"name" labels_** ?

vm-agent.spec:
  

> externalLabels:
```
          spec:
              selectAllByDefault: true
              image:
                tag: v1.92.1
              scrapeInterval: 25s
              externalLabels:
                cluster: vm-agent-1{2,3}
              extraArgs:
                promscrape.streamParse: "true"
                remoteWrite.label: cluster=vm-agent-1{2,3}
              remoteWriteSettings: 
                label: 
                  cluster: vm-agent-1,{2,3}
```

 
 alertmanager:
   ```
route:
        group_by: ["alertgroup", "job", "cluster"]
```

**Comment by Haleygo** [comment]
Hello @schechev-a 
Can you see the `cluster` label when query from cluster2 vmselect directly?

**Comment by schechev-a** [comment]
Hello Haleygo

For example query:
sum(increase(container_cpu_cfs_throttled_periods_total{container!="", }[5m])) by (container, pod, namespace)
  /
sum(increase(container_cpu_cfs_periods_total{}[5m])) by (container, pod, namespace)
  > ( 50 / 100 )
  
  I get:
  
  {container="cron",namespace="production-name",pod="name_pod"}
avg:0.96115, min:0.94102, max:0.97421, last:0.96542

 I did it in:
 
![image](https://github.com/VictoriaMetrics/helm-charts/assets/141005103/5e0b22fd-58be-41d5-ac5d-f1f69c469698)


If I add in query cluster: (container, pod, namespace, cluster)
I see later this label

**Comment by Haleygo** [comment]
```
externalLabels:
  cluster: vm-agent-1{2,3}
```
should be enought.

Can you share one of your alerting rules? Since there are `cluster` labels in the raw series, did your rules also having statement like `by (container, pod, namespace)` which will remove labels beside those three.

**Comment by schechev-a** [comment]
I also added a custom rule, there is also no cluster label
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  namespace: {{ .Release.Namespace }}
  name: kube-additional-rules
  labels:
    app: {{ include "victoria-metrics-k8s-stack.name" $ }}
spec:
  groups:
  - name: kubernetes-metrics-cpu
    rules:
      - alert: Node-High-LoadAverage
        expr: node_load5 > (count without (cpu, mode) (node_cpu_seconds_total{mode="system"})) * 5
        for: 30m
        labels:
          severity: critical
        annotations:
          #description: Host high CPU load-average (instance {{ "{{" }} $labels.instance }})
          #summary: Host high CPU load (instance {{ "{{" }} $labels.instance }})
      - alert: Node-High-CPULoad
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          #summary: 'Host high CPU load (instance {{ "{{" }} $labels.instance }})'
          description: CPU load is > 80%\n 
      - alert: Node-Memory-Usage
        expr: (((node_memory_MemTotal-node_memory_MemFree-node_memory_Cached)/(node_memory_MemTotal)*100)) > 75
        for: 2m
        labels:
          severity: critical
        annotations:
          #summary: High memory usage detected"
          #description: "Host memory usage (instance {{ "{{" }} $labels.instance }})"
```
