### ISSUE TITLE
Possibility to define limits and requests for VMCluster and VMStorage when using victoria-metrics-k8s-stack

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [VictoriaMetrics/helm-charts#741]
Hey,

I was trying to define the limits and requests of VMCluster and VMStorage when as the defaults values where to high for my use case, but I wasn't able to define them, is there a possible way to make it?

`values.yaml`:
```yaml
vmcluster:
  enabled: true
  spec:
    # Data will be stored for 12 months
    retentionPeriod: "12"
    vmstorage:
      resources:
        requests:
          cpu: 0m
          memory: 0Mi    
        limits:
          memory: 1024Mi
          cpu: 1000m
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                # Request a 175Gi volume to hold metrics
                storage: 175Gi
    vmselect:
      resources:
        requests:
          cpu: 0m
          memory: 0Mi    
        limits:
          memory: 1024Mi
          cpu: 1000m
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                # Request a 5Gi volume to hold cache
                storage: 5Gi
        
    vminsert: 
      resources:
        requests:
          cpu: 0m
          memory: 0Mi    
        limits:
          memory: 1024Mi
          cpu: 1000m
vmsingle:
  enabled: false
vmalert:
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 0m
      memory: 0Mi
```

Thanks,
MiguelNdeCarvalho
