### ISSUE TITLE
VMAlert components not creating

### ISSUE THREAD

**Issue by Sam-Sundar** [VictoriaMetrics/helm-charts#754]
Hey Team,

* I'm using `victoria-metrics-k8s-stack` helm-chart to install VM. I have two queries, first is even though we enable below config, it just created a VMAlert kind and doesn't create any deployment or sts for VMAlert. Due to this, none of my recording rules are being recognised by Grafana and i'm getting below error

```
vmalert:
  annotations: {}
  enabled: true

  # Controls whether VMAlert should use VMAgent or VMInsert as a target for remotewrite
  remoteWriteVMAgent: true
  # spec for VMAlert crd
  # https://docs.victoriametrics.com/operator/api.html#vmalertspec
  spec:
    selectAllByDefault: true
    image:
      tag: v1.94.0
    evaluationInterval: 15s
    

    # External labels to add to all generated recording rules and alerts
    externalLabels: {}

  # extra vmalert annotation templates
  templateFiles:
    {}
    # template_1.tmpl: |-
    #   {{ define "hello" -}}
    #   hello, Victoria!
    #   {{- end }}
    # template_2.tmpl: ""

  ingress:
    enabled: false

```
![image](https://github.com/VictoriaMetrics/helm-charts/assets/83000807/b6747513-8974-4003-9ff7-723bec447b84)

* How do we add ExtraScrapeConfig to VMAgent ? I couldn't find a way to give ExtraScrapeConfigs and have installed VMAgent thro' different chart which makes it difficult to maintain, since we now have two charts to take care of 😞 

```
vmagent:
  enabled: false
  annotations: {}
  # https://docs.victoriametrics.com/operator/api.html#vmagentremotewritespec
  # defined spec will be added to the remoteWrite configuration of VMAgent
  additionalRemoteWrites:
    []
    #- url: http://some-remote-write/api/v1/write
  # spec for VMAgent crd
  # https://docs.victoriametrics.com/operator/api.html#vmagentspec
  spec:
    selectAllByDefault: true
    image:
      tag: v1.94.0
    scrapeInterval: 20s
    externalLabels:
      cloud: gcp
      cluster: TestApps
    extraArgs:
      promscrape.streamParse: "true"
```

Adding a configmap and referring it thro' extraArge like `promscrape.config: /etc/vm/configs/vmscrapeconfig/prometheus.yaml` is throwing error 

```
2023-11-08T13:56:56.555Z	fatal	VictoriaMetrics/lib/promscrape/scraper.go:116	cannot read "/etc/vm/configs/vmscrapeconfig/prometheus.yaml": cannot parse Prometheus config from "/etc/vm/configs/vmscrapeconfig/prometheus.yaml": cannot unmarshal data: yaml: line 3: mapping values are not allowed in this context; pass -promscrape.config.strictParse=false command-line flag for ignoring unknown fields in yaml config
```

**Comment by Sam-Sundar** [comment]
VMAlert is fixed by adding notifier
```
vmalert:
  annotations: {}
  enabled: true

  # Controls whether VMAlert should use VMAgent or VMInsert as a target for remotewrite
  remoteWriteVMAgent: false
  # spec for VMAlert crd
  # https://docs.victoriametrics.com/operator/api.html#vmalertspec
  spec:
    selectAllByDefault: true
    image:
      tag: v1.94.0
    evaluationInterval: 15s
    notifier:
      url: "http://test"
```


Only issue i face is related to VMAgent  adding ExtraScrapeConfig to VMAgent.
