### ISSUE TITLE
[vmalert] Lack of configuration reloading customization

### ISSUE THREAD

**Issue by yoyrandao** [VictoriaMetrics/helm-charts#765]
Now the changes made to ConfigMap set in the `server.configMap` parameter cannot provoke kubernetes to reload pod due to lack of `checksum/{{ file }}` annotations in pod. 

There is no functionality for `server.annotations` to template annotations of auto-reload i.e.

```yaml
server:
  annotations:
    roll/on-every-change: "{{ randAlphaNum 64 | quote }}"
```
