### ISSUE TITLE
vmalertmanager secrets

### ISSUE THREAD

**Issue by DekelDevunet** [VictoriaMetrics/helm-charts#772]
Hey, 
I wonder how one can add to alertmanager secrets via a file or via environment variable. 

That's for providing slack app bot token credential for  it.

**Comment by Haleygo** [comment]
Hello,
If you are using victoria-metrics-k8s-stack chart, you can mount your config to `.Values.alertmanager.spec.configSecret` or `.Values.alertmanager.spec.configMaps`.

**Comment by AndrewChubatiuk** [comment]
operator supports [VMAlertmanagerConfig CR](https://docs.victoriametrics.com/operator/resources/vmalertmanagerconfig/), which provides validation of configuration parameters and ability to use k8s secrets as a source for webhook urls and other secrets

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: example-slack-web
  namespace: production
spec:
  route:
    receiver: slack
    group_interval: 1m
    routes:
      - receiver: slack
        matchers:
          - {severity =~ "warning|critical", app_name = "blog"}
  receivers:
    - name: slack
      slack_configs:
        - api_url:
          name: slack
          key: webhook_url
```
