### ISSUE TITLE
Unexpected values when using extraArgs

### ISSUE THREAD

**Issue by krysennn** [VictoriaMetrics/helm-charts#8]
Hi

I would add extra args with helm cli (--set) or with values file but i facing to unexpected values in rendered template.

### **Test1:** Testing with values file
`helm template test . -f test-values.yml`
```
test-values.yml:

vmstorage:
  extraArgs:
    search.maxUniqueTimeseries: 1000000
```

**Result:**
```
containers:
  - name: victoria-metrics-cluster-vmstorage
     ...
     args:
       - "--retentionPeriod=1"
       - "--storageDataPath=/storage"
       - --search.maxUniqueTimeseries=1e+06
```

### **Test2:** Testing with --set argument
`helm template test . --set vmstorage.extraArgs.search.maxUniqueTimeseries=1000000`
```
containers:
  - name: victoria-metrics-cluster-vmstorage
     ...
     args:
       - "--retentionPeriod=1"
       - "--storageDataPath=/storage"
       - --search=map[maxUniqueTimeseries:1000000]
```

### **Test3:** Second test with --set argument
`helm template test . --set vmstorage.extraArgs=search.maxUniqueTimeseries=1000000`
```
Error: template: victoria-metrics-cluster/templates/vmstorage-statefulset.yaml:45:43: executing "victoria-metrics-cluster/templates/vmstorage-statefulset.yaml" at <.Values.vmstorage.extraArgs>: range can't iterate over search.maxUniqueTimeseries=1000000
```

I'm new in the Kubernetes and Helm world, so i'm not sure about the syntax using, i will try to make PR to have the possibility to use values file without unexpected result and `--set` command.
