### ISSUE TITLE
Deploy victoria-metrics-k8s-stack using different storageClass than default

### ISSUE THREAD

**Issue by Angel0r** [VictoriaMetrics/helm-charts#811]
Hey!
I am trying to deploy `victoria-metrics-k8s-stack` chart but our production cluster uses a different storageClass than the standard.
Since we are using flux I tried to use a specific name by adding:
```yaml
values:
      storageClassName: prod-sc
```
but this didn't work.
The PVCs contain no storageClass name so they cannot be binded.

Is there a different way to do that or am I missing something?

/Angelos

**Comment by Angel0r** [comment]
I managed to solve the problem by setting the created storageClass as default:
```yaml
annotations: 
  storageclass.kubernetes.io/is-default-class: "true"
```

**Comment by Haleygo** [comment]
Hello @Angel0r ,
Have you tried specified the `storageClassName` under their `StorageSpec`, like for vmstorage
```
kind: VMCluster
metadata:
  name: example-vmcluster
spec:
  vmstorage:
    replicaCount: 2
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: prod-sc
```

**Comment by Nabil372** [comment]
@Angel0r, It's possible to set the storageClassName via the helm values. Just make sure you follow the resource spec.

Here's a snippet where I've specified storageClassName in my helm values for [VMSingle](https://docs.victoriametrics.com/operator/api/#vmsingle):

```json
{
...
"vmsingle": {
    "annotations": {},
    "enabled": true,
    "spec": {
        "image": {
            "tag": "v1.101.0"
        },
        "retentionPeriod": "30",
        "replicaCount": 1,
        "extraArgs": {},
        "storage": {
            "storageClassName": "efs-sc",
            "accessModes": [
                "ReadWriteOnce"
            ],
            "resources": {
                "requests": {
                    "storage": "20Gi"
                }
            }
        }
    },
...
}
```

helm successfully templates the storageClassName into the VMSingle spec:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  labels:
    app.kubernetes.io/instance: vmo-helm-c8ce5482
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: v1.101.0
    helm.sh/chart: victoria-metrics-k8s-stack-0.23.2
  name: vmo
  namespace: vm
spec:
  extraArgs:
    vmalert.proxyURL: http://vmalert-vmo.vm.svc:8080
  image:
    tag: v1.101.0
  replicaCount: 1
  retentionPeriod: "30"
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: "efs-sc"
```
