### ISSUE TITLE
[K8s-Stack] Add Global Variables for Image Registry and PullSecrets

### ISSUE THREAD

**Issue by alihoda** [VictoriaMetrics/helm-charts#818]
Is there any way to add global variables for image registry and pullSecrets in k8s stack? Just like what is in Prometheus charts.
```yaml
global:
  # global:
  #   imagePullSecrets:
  #   - name: pullSecret1
  #   - name: pullSecret2
  imagePullSecrets: []
  #
  # Allow parent charts to override registry hostname
  imageRegistry: ""
```
In the way that dependencies also use it.
