### ISSUE TITLE
victoria-metrics-agent chart adjustment for relabelConfig/ multiple urlRelabConfigs deployment via Ansible

### ISSUE THREAD

**Issue by aimee-889** [VictoriaMetrics/helm-charts#821]
Hello everyone :) 

This is a request for an enhancement. 
In our project we wanted to setup vmagnt via this helm chart. 
In our Kubernetes Architecture we send all metrics from different Prometheus instances from different Clusters to one vmagent and vmagent should send metrics to two victoriametrics (standard and longterm).
For this we need to provide to remoteWriteUrls, however we want to apply different relabel configs to each remoteWrtieUrls. We need this since we want to store only certain metrics in our longterm storage. 
As described in the Documentation, Victoriametris has this option.( https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/vmagent.md#splitting-data-streams-among-multiple-systems )

The needed values can be set in the Helm Chart via the extraArgs Configs 
remoteWrite.url= (remoteWriteUrls)
remoteWrite.url= (remoteWriteUrls)
remoteWrite.urlRelabelConfig= (extraArgs)
remoteWrite.urlRelabelConfig= (extraArgs)

If we are able to set these arguments we can deploy Vmagent how we need it it. However we deploy our Infrastructure via Ansible and Ansible does not allow that two Values are defined two times.

```
extraArgs: 
  remoteWrite.urlRelabelConfig: config.yml
  remoteWrite.urlRelabelConfig: config2.yml

```
Error: "found a duplicate dict key.  Using last defined value only."
This lets us only give one remoteWrite.urlRelabelConfig.

So I would ask if you could consider changing the Helm Chart. 

Restructure default values: 
old
```
remoteWriteUrls: []
```
new 
```
remoteWrite:
  urls:
    - "http://"
    - "http://"
    # optinal - if specified, first file will get applied to first remoteWriteUrl see https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/vmagent.md#splitting-data-streams-among-multiple-systems
    # if set configs must be provided via extra Volume/VolumeMounts
  urlRelabelConfig: 
    - "addtional-config/config.yml"
    - "additional-config/config2.yml"
```
Restructure deployment: 
new
 ```
 {{- range .Values.remoteWrite.urls }}
	- -remoteWrite.url={{ . }}
  {{- end }}
  {{- range .Values.remoteWrite.urlRelabelConfig }}
	- -remoteWrite.urlRelabelConfig={{ . }}
  {{- end }}
```

This would also make it easier to understand how to set a relabel config, for metrics that are pushed and not pulled. 
One could also add the option, so that -relabelConfig could be set via the helm chart values, not only -urlRelabelConfig

Thank you so much for reading my proposal. I would be very happy if you could think over it.
