### ISSUE TITLE
ability to set resources for vmagent (and probably other components) in victoria-metrics-k8s-stack

### ISSUE THREAD

**Issue by fenio** [VictoriaMetrics/helm-charts#827]
victoria-metrics-k8s-stack comes with some defaults for example for vmagent:

```
    Limits:
      cpu:     200m
      memory:  500Mi
    Requests:
      cpu:        50m
      memory:     200Mi
```

I'm hitting these limits and I see no way to change it using that helm chart others than to switch to separate vm-single + vm-operator.

**Comment by Haleygo** [comment]
Hello,
there is no default resources setting for vmagent in victoria-metrics-k8s-stack, so vm-operator will use the default envs [VM_VMAGENTDEFAULT_RESOURCE_*](https://github.com/VictoriaMetrics/operator/blob/fix-vmauth-quick-start/vars.md#L40) if they are not specified under vmagentSpec.
You can change it by adding them in [values](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml#L581) like 
```
vmagent:
  enabled: true
  # spec for VMAgent crd
  # https://docs.victoriametrics.com/operator/api.html#vmagentspec
  spec:
    resources:
      cpu:
```

**Comment by fenio** [comment]
Thank you @Haleygo.
WIth your hint I was able to do a lot of progress.
And I got familiar with API specs.
How about setting limits/resources for config-reloader containers which are part of many components from victoria-metrics-k8s-stack?
I tried to use envs like this but it doesn't work:

  values:
    env:
      VM_VMSINGLEDEFAULT_CONFIGRELOADERCPU: null
      VM_VMALERTDEFAULT_CONFIGRELOADERCPU: null
      VM_VMAGENTDEFAULT_CONFIGRELOADERCPU: null
      
What's the correct way to set these settings?

**Comment by fenio** [comment]
https://github.com/fenio/homelab/blob/main/cluster/apps/monitor/victoria-metrics/app/helmrelease.yaml
Just in case you'd want more details this is how I'm deploying VM on my cluster.

**Comment by ben-nelson-nbcuni** [comment]
If you don't want to set any CPU you can use the following:
```
  env:
    - name: VM_VMALERTDEFAULT_CONFIGRELOADERCPU
      value: 0
    - name: VM_VMAGENTDEFAULT_CONFIGRELOADERCPU
      value: 0
    - name: VM_VMALERTMANAGER_CONFIGRELOADERCPU
      value: 0
```
But there isn't a way to set requests different from limits. Proper resource blocks should be added to the CRDs for these 3 microservices.
