### ISSUE TITLE
How to pass inline promscrape.config to vmagent

### ISSUE THREAD

**Issue by evertonspader-tomtom** [VictoriaMetrics/helm-charts#846]
I want to pass extra configuration via `promscrape.config` for the `vmagent` in the k8s-stack. 

It looks like the right pace to do it is as an extra argument under `vmagent.spec.extraArgs` but it seems that it only accepts the path to a file with the configuration ([ref](https://docs.victoriametrics.com/vmagent/#quick-start)).

So my question is how to pass this extra relabeling configuration either as a file or as the inline configuration in the values file?

Something like this:
```yaml
vmagent:
  spec:
    extraArgs:
      promscrape.config: |
        global:
          scrape_interval: 15s
        scrape_configs:
          - job_name: 'kubernetes-pods'
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - action: labelmap
                regex: "__meta_kubernetes_service_label_(.+)"
                replacement: "$1"
```
end up in the deployment/pods looking like this and the pods won't start:
```yaml
      - args:
        - -httpListenAddr=:8429
        - |
          -promscrape.config=global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'kubernetes-pods'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - action: labelmap
                  regex: "__meta_kubernetes_service_label_(.+)"
                  replacement: "$1"
```

**Comment by air3ijai** [comment]
Looks like we a limited with that and should create a file out of the chart
```yaml
vmagent:
  # https://docs.victoriametrics.com/operator/api.html#vmagentspec
  spec:
    extraArgs:
      promscrape.config: /etc/vm/configs/vmagent-prometheus-config/prometheus.yml
      promscrape.config.strictParse: "false"
    configMaps: ["vmagent-prometheus-config"]
```

```shell
config='apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: labelmap
            regex: "__meta_kubernetes_service_label_(.+)"
            replacement: "$1"
'
echo $config | kubectl create -f -

```
