### ISSUE TITLE
How to pass maxLabelsPerTimeseries?

### ISSUE THREAD

**Issue by korsar182** [VictoriaMetrics/helm-charts#849]
How to pass -maxLabelsPerTimeseries command-line flago to vmsingle in victoria-metrics-k8s-stack?

**Comment by Haleygo** [comment]
Hello!
You can add it under [VMAgentSpec.extraArgs](https://docs.victoriametrics.com/operator/api/#vmagentspec), like
```
vmsingle:
  annotations: {}
  enabled: true
  # spec for VMSingle crd
  # https://docs.victoriametrics.com/operator/api.html#vmsinglespec
  spec:
    extraArgs:
      maxLabelsPerTimeseries: 50
```
