### ISSUE TITLE
[victoria-metrics-k8s-stack] Kind VMAgent "null" value in remoteWrite cause failed to helm install

### ISSUE THREAD

**Issue by tantm3** [VictoriaMetrics/helm-charts#865]
Hi everyone!

I try to install `victoria-metrics-k8s-stack` with a custom remote write config.
When I installing the helm chart it showed an error:
```
Error: INSTALLATION FAILED: 1 error occurred:
	* VMAgent.operator.victoriametrics.com "vm-k8s-victoria-metrics-k8s-stack" is invalid: spec.remoteWrite[0]: Invalid value: "null": spec.remoteWrite[0] in body must be of type object: "null"

```
I use the helm template command and saw that there is an extra `null value` from the VMAgent remoteWrite spec 
```
# Source: victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmagent.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: test-victoria-metrics-k8s-stack
  namespace: default
  labels: 
    helm.sh/chart: victoria-metrics-k8s-stack-0.18.11
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "v1.96.0"
    app.kubernetes.io/managed-by: Helm
spec:
  externalLabels:
    cluster: vmonitor-prod
  extraArgs:
    promscrape.streamParse: "true"
    remoteWrite.maxDiskUsagePerURL: 2GB
  image:
    tag: v1.96.0
  nodeSelector:
    backend: "true"
  remoteWrite:
  - null
  - basicAuth:
      password:
        key: password
        name: vm-k8s-remote-write-prod
      username:
        key: username
        name: vm-k8s-remote-write-prod

```
- I think that `null value` causes the installation process to fail.
- Here are the helm value file that I used:
[values.zip](https://github.com/VictoriaMetrics/helm-charts/files/14326319/values.zip)

**Comment by tantm3** [comment]
More information:
I think the `null value` is caused by disabling the vmsingle component.
When we make the `vmsingle enabled=false`, it will produce the `null values`. In the opposite, the remotewrite will have the value like this
```
# Source: victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmagent.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vm-k8s-victoria-metrics-k8s-stack
  namespace: default
  labels: 
    helm.sh/chart: victoria-metrics-k8s-stack-0.18.11
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/instance: vm-k8s
    app.kubernetes.io/version: "v1.96.0"
    app.kubernetes.io/managed-by: Helm
spec:
  externalLabels:
    cluster: cluster-name
  extraArgs:
    promscrape.streamParse: "true"
  image:
    tag: v1.96.0
  remoteWrite:
  - url: http://vmsingle-vm-k8s-victoria-metrics-k8s-stack.default.svc:8429/api/v1/write
  - basicAuth:
      password:
        key: password
        name: vm-k8s-remote-write-prod
      username:
        key: username
        name: vm-k8s-remote-write-prod
    tlsConfig:
      insecureSkipVerify: true
    url: https://103.245.249.45/api/v1/write
```

**Comment by zekker6** [comment]
Hello @tantm3, this issue should be fixed in chart release [v0.19.2](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.19.2). Could you verify if it helps in your case?

**Comment by tantm3** [comment]
I tested the new version v0.19.2 and it works.
The config now does not have the null value:
```
kind: VMAgent
metadata:
  name: test-victoria-metrics-k8s-stack
  namespace: default
  labels: 
    helm.sh/chart: victoria-metrics-k8s-stack-0.19.2
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "v1.98.0"
    app.kubernetes.io/managed-by: Helm
spec:
  externalLabels:
    cluster: vmonitor-prod
  extraArgs:
    promscrape.dropOriginalLabels: "true"
    promscrape.maxScrapeSize: "206777216"
    promscrape.streamParse: "true"
    remoteWrite.maxDiskUsagePerURL: 2GB
  image:
    repository: docker.io/victoriametrics/vmagent
    tag: v1.96.0
  nodeSelector:
    backend: "true"
  remoteWrite:
  - basicAuth:
      password:
        key: password
        name: vm-k8s-remote-write-prod
      username:
        key: username
        name: vm-k8s-remote-write-prod
    tlsConfig:
      insecureSkipVerify: true
    url: https://IP/api/v1/write
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: "0.5"
      memory: 500Mi
  scrapeInterval: 30s
  selectAllByDefault: true
  tolerations:
  - effect: NoSchedule
    key: backend
    operator: Equal
    value: "true"

```
