### ISSUE TITLE
Helm Charts: missing Ingress Definition for TLS

### ISSUE THREAD

**Issue by brandshaide** [VictoriaMetrics/helm-charts#932]
Helm-Chart being used: victoria-metrics-cluster

I've been enabling `Ingress` for both `vmselect ` and `vminsert` but apparently the templating/value substitution for `Ingress.TLS` appears to be missing

https://github.com/VictoriaMetrics/helm-charts/blob/7b517bea56798e405e13f4934f1a527e5f3a293b/charts/victoria-metrics-cluster/templates/vminsert-ingress.yaml#L25 

Sample definition: 

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: private
  labels:
    app: vminsert
spec:
  ingressClassName: private
  tls:
  - hosts:
    - runtime-victoriametrics.weu.ops.runtime.private.foo-bar.com
  rules:
  - host: runtime-victoriametrics.weu.ops.runtime.private.foo-bar.com
    http:
      paths:
      - path: /insert
        pathType: Prefix
        backend:
          service:
            name: victoria-metrics-victoria-metrics-cluster-vminsert
            port:
              number: 8480
```
I'd have expected the same to be working for `Ingress.tls` as as it is working vor `Ingress` : 

```
  {{- if .Values.vminsert.ingress.tls }}
  tls:
    {{- toYaml .Values.vminsert.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
  {{- range .Values.vminsert.ingress.hosts }}
    - {{ .name }}
      http:
        paths:
          - path: {{ .path }}
          - {{- if $ingressSupportsPathType }}
          pathType: {{ $ingressPathType }}
          {{- end }}
           # ////
  {{- end }}
{{- end }}
```
