### ISSUE TITLE
Added values file option for -remoteWrite.relabelConfig & -remoteWrite.urlRelabelConfig

### ISSUE THREAD

**Issue by sushovan23** [VictoriaMetrics/helm-charts#942]
I went through the current helm chart for vmagent and I see that there is no option to pass -remoteWrite.relabelConfig or -remoteWrite.urlRelabelConfig in helm values file. 

This issue is to add that option to official helm chart:
I think it would be similar to how remoteWrite.url is read today ->
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-agent/templates/deployment.yaml#L63-L64
and create new yaml file for it ->
https://github.com/VictoriaMetrics/helm-charts/issues/930#issuecomment-2010057333

**Comment by Haleygo** [comment]
Hello!
Like https://github.com/VictoriaMetrics/helm-charts/issues/930#issuecomment-2008655708, you can add them using [.Values,extraArgs](https://github.com/VictoriaMetrics/helm-charts/blob/3af87f4947ec87a0ff970e6d8674fa8e0633291f/charts/victoria-metrics-agent/values.yaml#L78)
```
extraArgs:
  envflag.enable: "true"
  envflag.prefix: VM_
  loggerFormat: json
  
  remoteWrite.relabelConfig: test.yml
  ## remoteWrite.urlRelabelConfig: relabelDev.yml
```
Unlike `-remoteWrite.url` , `-remoteWrite.relabelConfig` and `-remoteWrite.urlRelabelConfig` point to files with relabeling configs, those files should be provided by extra configmaps or secrets.
It's better not to expose the raw config in chart's values file, since the config is normally big and not about chart itself, maintaining an extra config file would be more clear.

**Comment by sushovan23** [comment]
I'm using helm for entire deployment, are you suggesting to maintain this file separately? if it was for single setup I would have done but we provision many vmagents per client and manage everything currently using helm.
remotewrite.relabelconfig will be much smaller than scrapeconfigs which are already supported in helm values.

**Comment by Haleygo** [comment]
Personally, I prefer to keep the values.yaml shorter and only expose important configs there, gives higher readability.
So I'd still recommend to maintain separated file for `scrapeconfigs` or `remotewrite.relabelconfig` using configmap or secret and mount them to vmagent, as they're separated config file themselves.
If you don't want to maintain the config file outside the chart release, you can create a second values.yaml using `.Values. extraObjects` like
```
## relabelconfig.yaml
extraArgs:
  remoteWrite.relabelConfig: /relabelconfig/relabelconfig.yaml

# Extra Volumes for the pod
extraVolumes:
  - name: relabelconfig
    configMap:
      name: relabelconfig

# Extra Volume Mounts for the container
extraVolumeMounts:
  - name: relabelconfig
    mountPath: /relabelconfig

# add this part to the original values file or create a separate one for multiple release to use
# Add extra specs dynamically to this chart
extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: relabelconfig
    data:
      relabelconfig.yaml: |
        - source_labels: [__address__]
          target_label: instance
          regex: (.*)
          replacement: $1
        - xxx
```
And install with `helm install xxx victoria-metrics-vmagent -f relabelconfig.yaml`.
