### ISSUE TITLE
Support options for vmagent to scrape targets via a proxy

### ISSUE THREAD

**Issue by der-ali** [VictoriaMetrics/helm-charts#951]
According to the documentation VMagent [supports scraping target via a proxy](https://docs.victoriametrics.com/vmagent/#scraping-targets-via-a-proxy).
I tried adding the option under vmagent specs in values.yaml:
```
vmagent:
  spec:
    # To fine tune the vmagent add the flags to extraArgs dictionary
    # https://docs.victoriametrics.com/vmagent.html#advanced-usage
    # extraArgs:
      # <flags>
    resources:
      limits:
        memory: 1G
      requests:
        cpu: 500m
        memory: 1G
    scrape_configs:
    - job_name: etcd
      proxy_url: http://pushprox-etcd-proxy.monitoring.svc:8080
      static_configs:
        - targets: ['1.2.3.4:2381','1.2.3.5:2381','1.2.3.6:2381']
```
The vmstack operator  doesn't seem to support this option.
