### ISSUE TITLE
Duplicated VictoriaMetrics datasource

### ISSUE THREAD

**Issue by todeb** [VictoriaMetrics/helm-charts#964]
when enabled VictoriaMetrics datasource plugin for grafana
```
grafana:
  plugins:
    - "https://github.com/VictoriaMetrics/grafana-datasource/releases/download/v0.5.0/victoriametrics-datasource-v0.5.0.zip;victoriametrics-datasource"
   grafana.ini
    plugins:
      # Why VictoriaMetrics datasource is unsigned: https://github.com/VictoriaMetrics/grafana-datasource/blob/main/README.md#why-victoriametrics-datasource-is-unsigned
      allow_loading_unsigned_plugins: victoriametrics-datasource

  # Change datasource type in dashboards from Prometheus to VictoriaMetrics.
  # you can use `victoriametrics-datasource` instead of `prometheus` if enabled VictoriaMetrics Datasource above
  defaultDatasourceType: "victoriametrics-datasource"
```

instead of VictoriaMetrics prometheus datastource that was shown before, there are 2 victoriametrics datasources with slightly different name with very same configuration.
* VictoriaMetrics
* VictoriaMetrics (DS)
![image](https://github.com/VictoriaMetrics/helm-charts/assets/61552048/d34e8587-5be4-4d44-a79d-396eaac7ecdd)

It is a bit confusing and redundant.
* Any possibility to remove that?
* Any possibility to disable predefined datasource or change the name?

**Comment by Haleygo** [comment]
Hello!
No, the default one can't be disabled now when you [enabled vmsingle or vmcluster](https://github.com/VictoriaMetrics/helm-charts/blob/add-missed-resources/charts/victoria-metrics-k8s-stack/templates/grafana/datasource.yaml#L20). 
And change [.Values.grafana.defaultDatasourceType](https://github.com/VictoriaMetrics/helm-charts/blob/add-missed-resources/charts/victoria-metrics-k8s-stack/values.yaml#L704) to "victoriametrics-datasource" will make two datasources the same.
I believe the original idea is having two datasources with different types as `prometheus` and `victoriametrics`. And they can be duplicated when `.Values.grafana.defaultDatasourceType` changed to "victoriametrics" as well.

**Comment by AndrewChubatiuk** [comment]
starting next release any default datasources can be set for grafana using
```
grafana:
  sidecar:
    datasources:
      default:
        - name: VictoriaMetrics
          isDefault: true
```
url parameter is not required, it will be for all datasources in a list
