### ISSUE TITLE
[k8s-stack/kube-etcd] Cannot specify mTLS auth configuration

### ISSUE THREAD

**Issue by DvdChe** [VictoriaMetrics/helm-charts#965]
Hello there, 

I try to configure kube-etcd vmservicescrape  with kubeEtcd values and I cannot find any possibilities to specify mTLS configuration. 

As described [in the readme section](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack),  the only available parameters  to configure kubeEtcd  are : 
- `kubeEtcd.spec.endpoints[0].tlsConfig.caFile` 
- `kubeEtcd.spec.endpoints[0].tlsConfig. bearerTokenFile `. 

I would except to have the possibilities to specify same parameters as `vmservicescrape.spec.endpoints.tlsConfig`.  I wanted to make sur i am not  missing something around or if there is a regular way to authenticate on the etcd endpoint i ignore. 

I would be happy to contribute if it needs to be implemented.

Thanks for help

**Comment by Haleygo** [comment]
Hello!
All the available spec in [vmservicescrape](https://docs.victoriametrics.com/operator/api/#vmservicescrapespec) are also available here, we just don't list them all in the values file. 
You can add them like
```
kubeEtcd:
  enabled: true
  spec:
    jobLabel: jobLabel
    endpoints:
      - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        # bearerTokenSecret:
        #   key: ""
        port: http-metrics
        scheme: https
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          certFile: /var/lib/minikube/certs/etcd/peer.crt
          keyFile: /var/lib/minikube/certs/etcd/peer.key
          insecureSkipVerify: true
```
