### ISSUE TITLE
Setting Alertmanager's config-reloader container resources in victoria-metrics-k8s-stack values

### ISSUE THREAD

**Issue by arseny-zinchenko** [VictoriaMetrics/helm-charts#993]
Hello.
I'm want to update Alertmanager's `config-reloader` container `resources.requests`.
In my values file I have the following `resources`:

```
  alertmanager:
    enabled: true
    persistence:
      enabled: true
      storageClass: "gp2-retain"
      size: 100Mi
    
    spec:
      replicaCount: 1
      resources:
        requests:
          memory: 50Mi
          cpu: 10m
```
But it's applied only to the Alertmanager's container, while `config-reloader` is left untouched:

```
$ kk describe sts vmalertmanager-vm-k8s-stack
...
  Containers:
   alertmanager:
    Image:       prom/alertmanager:v0.25.0
    ...
    Requests:
      cpu:      10m
      memory:   50Mi
      ...
   config-reloader:
    Image:      jimmidyson/configmap-reload:v0.3.0
    ...
    Limits:
      cpu:     100m
      memory:  25Mi
    Requests:
      cpu:        100m
      memory:     25Mi
....
```

I can't see any mentions of the  `config-reloader` configuration possible in the [values.yaml](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml#L342) or in the [vmalertmanagerspec](https://docs.victoriametrics.com/operator/api/#vmalertmanagerspec) Docs.

So, is there any way to change it?

And the same question is about `vmagent-vm-k8s-stack` and `vmalert-vm-k8s-stack` Deployments.
